/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMCategory service. Represents a row in the &quot;GEM_CATGY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMCategoryImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMCategory
 * @see com.ihg.brandstandards.db.model.impl.GEMCategoryImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMCategoryModelImpl
 * @generated
 */
public interface GEMCategoryModel extends BaseModel<GEMCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m category model instance should use the {@link GEMCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m category.
	 *
	 * @return the primary key of this g e m category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m category.
	 *
	 * @param primaryKey the primary key of this g e m category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the category ID of this g e m category.
	 *
	 * @return the category ID of this g e m category
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this g e m category.
	 *
	 * @param categoryId the category ID of this g e m category
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the cms category ID of this g e m category.
	 *
	 * @return the cms category ID of this g e m category
	 */
	public long getCmsCategoryId();

	/**
	 * Sets the cms category ID of this g e m category.
	 *
	 * @param cmsCategoryId the cms category ID of this g e m category
	 */
	public void setCmsCategoryId(long cmsCategoryId);

	/**
	 * Returns the gem category code of this g e m category.
	 *
	 * @return the gem category code of this g e m category
	 */
	@AutoEscape
	public String getGemCategoryCode();

	/**
	 * Sets the gem category code of this g e m category.
	 *
	 * @param gemCategoryCode the gem category code of this g e m category
	 */
	public void setGemCategoryCode(String gemCategoryCode);

	/**
	 * Returns the gem prnt category ID of this g e m category.
	 *
	 * @return the gem prnt category ID of this g e m category
	 */
	@AutoEscape
	public String getGemPrntCategoryId();

	/**
	 * Sets the gem prnt category ID of this g e m category.
	 *
	 * @param gemPrntCategoryId the gem prnt category ID of this g e m category
	 */
	public void setGemPrntCategoryId(String gemPrntCategoryId);

	/**
	 * Returns the category name of this g e m category.
	 *
	 * @return the category name of this g e m category
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this g e m category.
	 *
	 * @param categoryName the category name of this g e m category
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the category view type of this g e m category.
	 *
	 * @return the category view type of this g e m category
	 */
	@AutoEscape
	public String getCategoryViewType();

	/**
	 * Sets the category view type of this g e m category.
	 *
	 * @param categoryViewType the category view type of this g e m category
	 */
	public void setCategoryViewType(String categoryViewType);

	/**
	 * Returns the category ans all of this g e m category.
	 *
	 * @return the category ans all of this g e m category
	 */
	@AutoEscape
	public String getCategoryAnsAll();

	/**
	 * Sets the category ans all of this g e m category.
	 *
	 * @param categoryAnsAll the category ans all of this g e m category
	 */
	public void setCategoryAnsAll(String categoryAnsAll);

	/**
	 * Returns the duplicatable of this g e m category.
	 *
	 * @return the duplicatable of this g e m category
	 */
	@AutoEscape
	public String getDuplicatable();

	/**
	 * Sets the duplicatable of this g e m category.
	 *
	 * @param duplicatable the duplicatable of this g e m category
	 */
	public void setDuplicatable(String duplicatable);

	/**
	 * Returns the display order number of this g e m category.
	 *
	 * @return the display order number of this g e m category
	 */
	public long getDisplayOrderNumber();

	/**
	 * Sets the display order number of this g e m category.
	 *
	 * @param displayOrderNumber the display order number of this g e m category
	 */
	public void setDisplayOrderNumber(long displayOrderNumber);

	/**
	 * Returns the creator ID of this g e m category.
	 *
	 * @return the creator ID of this g e m category
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m category.
	 *
	 * @param creatorId the creator ID of this g e m category
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m category.
	 *
	 * @return the created date of this g e m category
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m category.
	 *
	 * @param createdDate the created date of this g e m category
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m category.
	 *
	 * @return the updated by of this g e m category
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m category.
	 *
	 * @param updatedBy the updated by of this g e m category
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m category.
	 *
	 * @return the updated date of this g e m category
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m category.
	 *
	 * @param updatedDate the updated date of this g e m category
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMCategory gemCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMCategory> toCacheModel();

	@Override
	public GEMCategory toEscapedModel();

	@Override
	public GEMCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}