/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMQlReport service. Represents a row in the &quot;QLTY_LEAD_RPT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMQlReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMQlReportImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMQlReport
 * @see com.ihg.brandstandards.db.model.impl.GEMQlReportImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMQlReportModelImpl
 * @generated
 */
public interface GEMQlReportModel extends BaseModel<GEMQlReport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m ql report model instance should use the {@link GEMQlReport} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m ql report.
	 *
	 * @return the primary key of this g e m ql report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m ql report.
	 *
	 * @param primaryKey the primary key of this g e m ql report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ql report ID of this g e m ql report.
	 *
	 * @return the ql report ID of this g e m ql report
	 */
	public long getQlReportId();

	/**
	 * Sets the ql report ID of this g e m ql report.
	 *
	 * @param qlReportId the ql report ID of this g e m ql report
	 */
	public void setQlReportId(long qlReportId);

	/**
	 * Returns the publish dept ID of this g e m ql report.
	 *
	 * @return the publish dept ID of this g e m ql report
	 */
	public long getPublishDeptId();

	/**
	 * Sets the publish dept ID of this g e m ql report.
	 *
	 * @param publishDeptId the publish dept ID of this g e m ql report
	 */
	public void setPublishDeptId(long publishDeptId);

	/**
	 * Returns the publish ID of this g e m ql report.
	 *
	 * @return the publish ID of this g e m ql report
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this g e m ql report.
	 *
	 * @param publishId the publish ID of this g e m ql report
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the std ID of this g e m ql report.
	 *
	 * @return the std ID of this g e m ql report
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this g e m ql report.
	 *
	 * @param stdId the std ID of this g e m ql report
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the bucket ID of this g e m ql report.
	 *
	 * @return the bucket ID of this g e m ql report
	 */
	public long getBucketId();

	/**
	 * Sets the bucket ID of this g e m ql report.
	 *
	 * @param bucketId the bucket ID of this g e m ql report
	 */
	public void setBucketId(long bucketId);

	/**
	 * Returns the severity ID of this g e m ql report.
	 *
	 * @return the severity ID of this g e m ql report
	 */
	public long getSeverityId();

	/**
	 * Sets the severity ID of this g e m ql report.
	 *
	 * @param severityId the severity ID of this g e m ql report
	 */
	public void setSeverityId(long severityId);

	/**
	 * Returns the measurement ID of this g e m ql report.
	 *
	 * @return the measurement ID of this g e m ql report
	 */
	public long getMeasurementId();

	/**
	 * Sets the measurement ID of this g e m ql report.
	 *
	 * @param measurementId the measurement ID of this g e m ql report
	 */
	public void setMeasurementId(long measurementId);

	/**
	 * Returns the trigger ID of this g e m ql report.
	 *
	 * @return the trigger ID of this g e m ql report
	 */
	public long getTriggerId();

	/**
	 * Sets the trigger ID of this g e m ql report.
	 *
	 * @param triggerId the trigger ID of this g e m ql report
	 */
	public void setTriggerId(long triggerId);

	/**
	 * Returns the category ID of this g e m ql report.
	 *
	 * @return the category ID of this g e m ql report
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this g e m ql report.
	 *
	 * @param categoryId the category ID of this g e m ql report
	 */
	public void setCategoryId(long categoryId);

	/**
	 * Returns the display order number of this g e m ql report.
	 *
	 * @return the display order number of this g e m ql report
	 */
	public long getDisplayOrderNumber();

	/**
	 * Sets the display order number of this g e m ql report.
	 *
	 * @param displayOrderNumber the display order number of this g e m ql report
	 */
	public void setDisplayOrderNumber(long displayOrderNumber);

	/**
	 * Returns the region ID of this g e m ql report.
	 *
	 * @return the region ID of this g e m ql report
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this g e m ql report.
	 *
	 * @param regionId the region ID of this g e m ql report
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the compliance due days of this g e m ql report.
	 *
	 * @return the compliance due days of this g e m ql report
	 */
	public long getComplianceDueDays();

	/**
	 * Sets the compliance due days of this g e m ql report.
	 *
	 * @param complianceDueDays the compliance due days of this g e m ql report
	 */
	public void setComplianceDueDays(long complianceDueDays);

	/**
	 * Returns the glbl must measure of this g e m ql report.
	 *
	 * @return the glbl must measure of this g e m ql report
	 */
	@AutoEscape
	public String getGlblMustMeasure();

	/**
	 * Sets the glbl must measure of this g e m ql report.
	 *
	 * @param glblMustMeasure the glbl must measure of this g e m ql report
	 */
	public void setGlblMustMeasure(String glblMustMeasure);

	/**
	 * Returns the creator ID of this g e m ql report.
	 *
	 * @return the creator ID of this g e m ql report
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m ql report.
	 *
	 * @param creatorId the creator ID of this g e m ql report
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m ql report.
	 *
	 * @return the created date of this g e m ql report
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m ql report.
	 *
	 * @param createdDate the created date of this g e m ql report
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m ql report.
	 *
	 * @return the updated by of this g e m ql report
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m ql report.
	 *
	 * @param updatedBy the updated by of this g e m ql report
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m ql report.
	 *
	 * @return the updated date of this g e m ql report
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m ql report.
	 *
	 * @param updatedDate the updated date of this g e m ql report
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMQlReport gemQlReport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMQlReport> toCacheModel();

	@Override
	public GEMQlReport toEscapedModel();

	@Override
	public GEMQlReport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}