/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the GlossaryExt service. Represents a row in the &quot;GLOSSARY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GlossaryExtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GlossaryExtImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GlossaryExt
 * @see com.ihg.brandstandards.db.model.impl.GlossaryExtImpl
 * @see com.ihg.brandstandards.db.model.impl.GlossaryExtModelImpl
 * @generated
 */
public interface GlossaryExtModel extends BaseModel<GlossaryExt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a glossary ext model instance should use the {@link GlossaryExt} interface instead.
	 */

	/**
	 * Returns the primary key of this glossary ext.
	 *
	 * @return the primary key of this glossary ext
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this glossary ext.
	 *
	 * @param primaryKey the primary key of this glossary ext
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the glossary ID of this glossary ext.
	 *
	 * @return the glossary ID of this glossary ext
	 */
	public long getGlossaryId();

	/**
	 * Sets the glossary ID of this glossary ext.
	 *
	 * @param glossaryId the glossary ID of this glossary ext
	 */
	public void setGlossaryId(long glossaryId);

	/**
	 * Returns the active ind of this glossary ext.
	 *
	 * @return the active ind of this glossary ext
	 */
	@AutoEscape
	public String getActiveInd();

	/**
	 * Sets the active ind of this glossary ext.
	 *
	 * @param activeInd the active ind of this glossary ext
	 */
	public void setActiveInd(String activeInd);

	/**
	 * Returns the glossary term text of this glossary ext.
	 *
	 * @return the glossary term text of this glossary ext
	 */
	@AutoEscape
	public String getGlossaryTermText();

	/**
	 * Sets the glossary term text of this glossary ext.
	 *
	 * @param glossaryTermText the glossary term text of this glossary ext
	 */
	public void setGlossaryTermText(String glossaryTermText);

	/**
	 * Returns the glossary term desc of this glossary ext.
	 *
	 * @return the glossary term desc of this glossary ext
	 */
	@AutoEscape
	public String getGlossaryTermDesc();

	/**
	 * Sets the glossary term desc of this glossary ext.
	 *
	 * @param glossaryTermDesc the glossary term desc of this glossary ext
	 */
	public void setGlossaryTermDesc(String glossaryTermDesc);

	/**
	 * Returns the glossary regions of this glossary ext.
	 *
	 * @return the glossary regions of this glossary ext
	 */
	@AutoEscape
	public String getGlossaryRegions();

	/**
	 * Sets the glossary regions of this glossary ext.
	 *
	 * @param glossaryRegions the glossary regions of this glossary ext
	 */
	public void setGlossaryRegions(String glossaryRegions);

	/**
	 * Returns the glossary chains of this glossary ext.
	 *
	 * @return the glossary chains of this glossary ext
	 */
	@AutoEscape
	public String getGlossaryChains();

	/**
	 * Sets the glossary chains of this glossary ext.
	 *
	 * @param glossaryChains the glossary chains of this glossary ext
	 */
	public void setGlossaryChains(String glossaryChains);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GlossaryExt glossaryExt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GlossaryExt> toCacheModel();

	@Override
	public GlossaryExt toEscapedModel();

	@Override
	public GlossaryExt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}