/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the HistManuals service. Represents a row in the &quot;HIST_MNL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.HistManualsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.HistManualsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see HistManuals
 * @see com.ihg.brandstandards.db.model.impl.HistManualsImpl
 * @see com.ihg.brandstandards.db.model.impl.HistManualsModelImpl
 * @generated
 */
public interface HistManualsModel extends BaseModel<HistManuals> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a hist manuals model instance should use the {@link HistManuals} interface instead.
	 */

	/**
	 * Returns the primary key of this hist manuals.
	 *
	 * @return the primary key of this hist manuals
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this hist manuals.
	 *
	 * @param primaryKey the primary key of this hist manuals
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the hist manual ID of this hist manuals.
	 *
	 * @return the hist manual ID of this hist manuals
	 */
	public long getHistManualId();

	/**
	 * Sets the hist manual ID of this hist manuals.
	 *
	 * @param histManualId the hist manual ID of this hist manuals
	 */
	public void setHistManualId(long histManualId);

	/**
	 * Returns the title of this hist manuals.
	 *
	 * @return the title of this hist manuals
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this hist manuals.
	 *
	 * @param title the title of this hist manuals
	 */
	public void setTitle(String title);

	/**
	 * Returns the type of this hist manuals.
	 *
	 * @return the type of this hist manuals
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this hist manuals.
	 *
	 * @param type the type of this hist manuals
	 */
	public void setType(String type);

	/**
	 * Returns the pub date of this hist manuals.
	 *
	 * @return the pub date of this hist manuals
	 */
	public Date getPubDate();

	/**
	 * Sets the pub date of this hist manuals.
	 *
	 * @param pubDate the pub date of this hist manuals
	 */
	public void setPubDate(Date pubDate);

	/**
	 * Returns the status of this hist manuals.
	 *
	 * @return the status of this hist manuals
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this hist manuals.
	 *
	 * @param status the status of this hist manuals
	 */
	public void setStatus(String status);

	/**
	 * Returns the creator ID of this hist manuals.
	 *
	 * @return the creator ID of this hist manuals
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this hist manuals.
	 *
	 * @param creatorId the creator ID of this hist manuals
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this hist manuals.
	 *
	 * @return the created date of this hist manuals
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this hist manuals.
	 *
	 * @param createdDate the created date of this hist manuals
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this hist manuals.
	 *
	 * @return the updated by of this hist manuals
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this hist manuals.
	 *
	 * @param updatedBy the updated by of this hist manuals
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this hist manuals.
	 *
	 * @return the updated date of this hist manuals
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this hist manuals.
	 *
	 * @param updatedDate the updated date of this hist manuals
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(HistManuals histManuals);

	@Override
	public int hashCode();

	@Override
	public CacheModel<HistManuals> toCacheModel();

	@Override
	public HistManuals toEscapedModel();

	@Override
	public HistManuals toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}