/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsLocale service. Represents a row in the &quot;BRNDSTND_LOCALE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsLocaleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsLocaleImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsLocale
 * @see com.ihg.brandstandards.db.model.impl.StandardsLocaleImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsLocaleModelImpl
 * @generated
 */
public interface StandardsLocaleModel extends BaseModel<StandardsLocale> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards locale model instance should use the {@link StandardsLocale} interface instead.
	 */

	/**
	 * Returns the primary key of this standards locale.
	 *
	 * @return the primary key of this standards locale
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this standards locale.
	 *
	 * @param primaryKey the primary key of this standards locale
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the locale code of this standards locale.
	 *
	 * @return the locale code of this standards locale
	 */
	@AutoEscape
	public String getLocaleCode();

	/**
	 * Sets the locale code of this standards locale.
	 *
	 * @param localeCode the locale code of this standards locale
	 */
	public void setLocaleCode(String localeCode);

	/**
	 * Returns the country code of this standards locale.
	 *
	 * @return the country code of this standards locale
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this standards locale.
	 *
	 * @param countryCode the country code of this standards locale
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the locale name of this standards locale.
	 *
	 * @return the locale name of this standards locale
	 */
	@AutoEscape
	public String getLocaleName();

	/**
	 * Sets the locale name of this standards locale.
	 *
	 * @param localeName the locale name of this standards locale
	 */
	public void setLocaleName(String localeName);

	/**
	 * Returns the language code of this standards locale.
	 *
	 * @return the language code of this standards locale
	 */
	@AutoEscape
	public String getLanguageCode();

	/**
	 * Sets the language code of this standards locale.
	 *
	 * @param languageCode the language code of this standards locale
	 */
	public void setLanguageCode(String languageCode);

	/**
	 * Returns the order number of this standards locale.
	 *
	 * @return the order number of this standards locale
	 */
	public long getOrderNumber();

	/**
	 * Sets the order number of this standards locale.
	 *
	 * @param orderNumber the order number of this standards locale
	 */
	public void setOrderNumber(long orderNumber);

	/**
	 * Returns the is active of this standards locale.
	 *
	 * @return the is active of this standards locale
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this standards locale.
	 *
	 * @param isActive the is active of this standards locale
	 */
	public void setIsActive(String isActive);

	/**
	 * Returns the creator ID of this standards locale.
	 *
	 * @return the creator ID of this standards locale
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards locale.
	 *
	 * @param creatorId the creator ID of this standards locale
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards locale.
	 *
	 * @return the created date of this standards locale
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards locale.
	 *
	 * @param createdDate the created date of this standards locale
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards locale.
	 *
	 * @return the updated by of this standards locale
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards locale.
	 *
	 * @param updatedBy the updated by of this standards locale
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards locale.
	 *
	 * @return the updated date of this standards locale
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards locale.
	 *
	 * @param updatedDate the updated date of this standards locale
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsLocale standardsLocale);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsLocale> toCacheModel();

	@Override
	public StandardsLocale toEscapedModel();

	@Override
	public StandardsLocale toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}