/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.ihg.brandstandards.db.service.persistence.StandardsChainImagesPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsChainImages service. Represents a row in the &quot;STD_IMAGE_CHAIN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsChainImagesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsChainImagesImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsChainImages
 * @see com.ihg.brandstandards.db.model.impl.StandardsChainImagesImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsChainImagesModelImpl
 * @generated
 */
public interface StandardsChainImagesModel extends BaseModel<StandardsChainImages> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards chain images model instance should use the {@link StandardsChainImages} interface instead.
	 */

	/**
	 * Returns the primary key of this standards chain images.
	 *
	 * @return the primary key of this standards chain images
	 */
	public StandardsChainImagesPK getPrimaryKey();

	/**
	 * Sets the primary key of this standards chain images.
	 *
	 * @param primaryKey the primary key of this standards chain images
	 */
	public void setPrimaryKey(StandardsChainImagesPK primaryKey);

	/**
	 * Returns the std image ID of this standards chain images.
	 *
	 * @return the std image ID of this standards chain images
	 */
	public long getStdImageId();

	/**
	 * Sets the std image ID of this standards chain images.
	 *
	 * @param stdImageId the std image ID of this standards chain images
	 */
	public void setStdImageId(long stdImageId);

	/**
	 * Returns the chain code of this standards chain images.
	 *
	 * @return the chain code of this standards chain images
	 */
	@AutoEscape
	public String getChainCode();

	/**
	 * Sets the chain code of this standards chain images.
	 *
	 * @param chainCode the chain code of this standards chain images
	 */
	public void setChainCode(String chainCode);

	/**
	 * Returns the creator ID of this standards chain images.
	 *
	 * @return the creator ID of this standards chain images
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards chain images.
	 *
	 * @param creatorId the creator ID of this standards chain images
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards chain images.
	 *
	 * @return the created date of this standards chain images
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards chain images.
	 *
	 * @param createdDate the created date of this standards chain images
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards chain images.
	 *
	 * @return the updated by of this standards chain images
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards chain images.
	 *
	 * @param updatedBy the updated by of this standards chain images
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards chain images.
	 *
	 * @return the updated date of this standards chain images
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards chain images.
	 *
	 * @param updatedDate the updated date of this standards chain images
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsChainImages standardsChainImages);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsChainImages> toCacheModel();

	@Override
	public StandardsChainImages toEscapedModel();

	@Override
	public StandardsChainImages toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}