/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TaxonomyExt service. Represents a row in the &quot;Taxonomy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.TaxonomyExtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.TaxonomyExtImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see TaxonomyExt
 * @see com.ihg.brandstandards.db.model.impl.TaxonomyExtImpl
 * @see com.ihg.brandstandards.db.model.impl.TaxonomyExtModelImpl
 * @generated
 */
public interface TaxonomyExtModel extends BaseModel<TaxonomyExt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Custom Query mapping to create index path. model instance should use the {@link TaxonomyExt} interface instead.
	 */

	/**
	 * Returns the primary key of this Custom Query mapping to create index path..
	 *
	 * @return the primary key of this Custom Query mapping to create index path.
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Custom Query mapping to create index path..
	 *
	 * @param primaryKey the primary key of this Custom Query mapping to create index path.
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tax ID of this Custom Query mapping to create index path..
	 *
	 * @return the tax ID of this Custom Query mapping to create index path.
	 */
	public long getTaxId();

	/**
	 * Sets the tax ID of this Custom Query mapping to create index path..
	 *
	 * @param taxId the tax ID of this Custom Query mapping to create index path.
	 */
	public void setTaxId(long taxId);

	/**
	 * Returns the parent ID of this Custom Query mapping to create index path..
	 *
	 * @return the parent ID of this Custom Query mapping to create index path.
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this Custom Query mapping to create index path..
	 *
	 * @param parentId the parent ID of this Custom Query mapping to create index path.
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the title of this Custom Query mapping to create index path..
	 *
	 * @return the title of this Custom Query mapping to create index path.
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this Custom Query mapping to create index path..
	 *
	 * @param title the title of this Custom Query mapping to create index path.
	 */
	public void setTitle(String title);

	/**
	 * Returns the desc of this Custom Query mapping to create index path..
	 *
	 * @return the desc of this Custom Query mapping to create index path.
	 */
	@AutoEscape
	public String getDesc();

	/**
	 * Sets the desc of this Custom Query mapping to create index path..
	 *
	 * @param desc the desc of this Custom Query mapping to create index path.
	 */
	public void setDesc(String desc);

	/**
	 * Returns the image loc of this Custom Query mapping to create index path..
	 *
	 * @return the image loc of this Custom Query mapping to create index path.
	 */
	@AutoEscape
	public String getImageLoc();

	/**
	 * Sets the image loc of this Custom Query mapping to create index path..
	 *
	 * @param imageLoc the image loc of this Custom Query mapping to create index path.
	 */
	public void setImageLoc(String imageLoc);

	/**
	 * Returns the lvl of this Custom Query mapping to create index path..
	 *
	 * @return the lvl of this Custom Query mapping to create index path.
	 */
	@AutoEscape
	public String getLvl();

	/**
	 * Sets the lvl of this Custom Query mapping to create index path..
	 *
	 * @param lvl the lvl of this Custom Query mapping to create index path.
	 */
	public void setLvl(String lvl);

	/**
	 * Returns the path of this Custom Query mapping to create index path..
	 *
	 * @return the path of this Custom Query mapping to create index path.
	 */
	@AutoEscape
	public String getPath();

	/**
	 * Sets the path of this Custom Query mapping to create index path..
	 *
	 * @param path the path of this Custom Query mapping to create index path.
	 */
	public void setPath(String path);

	/**
	 * Returns the level sort order of this Custom Query mapping to create index path..
	 *
	 * @return the level sort order of this Custom Query mapping to create index path.
	 */
	public long getLevelSortOrder();

	/**
	 * Sets the level sort order of this Custom Query mapping to create index path..
	 *
	 * @param levelSortOrder the level sort order of this Custom Query mapping to create index path.
	 */
	public void setLevelSortOrder(long levelSortOrder);

	/**
	 * Returns the index order of this Custom Query mapping to create index path..
	 *
	 * @return the index order of this Custom Query mapping to create index path.
	 */
	public long getIndexOrder();

	/**
	 * Sets the index order of this Custom Query mapping to create index path..
	 *
	 * @param indexOrder the index order of this Custom Query mapping to create index path.
	 */
	public void setIndexOrder(long indexOrder);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaxonomyExt taxonomyExt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaxonomyExt> toCacheModel();

	@Override
	public TaxonomyExt toEscapedModel();

	@Override
	public TaxonomyExt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}