/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserSearchCriteria service. Represents a row in the &quot;USR_SEARCH_CRIT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.UserSearchCriteriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.UserSearchCriteriaImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see UserSearchCriteria
 * @see com.ihg.brandstandards.db.model.impl.UserSearchCriteriaImpl
 * @see com.ihg.brandstandards.db.model.impl.UserSearchCriteriaModelImpl
 * @generated
 */
public interface UserSearchCriteriaModel extends BaseModel<UserSearchCriteria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user search criteria model instance should use the {@link UserSearchCriteria} interface instead.
	 */

	/**
	 * Returns the primary key of this user search criteria.
	 *
	 * @return the primary key of this user search criteria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user search criteria.
	 *
	 * @param primaryKey the primary key of this user search criteria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user search ID of this user search criteria.
	 *
	 * @return the user search ID of this user search criteria
	 */
	public long getUserSearchId();

	/**
	 * Sets the user search ID of this user search criteria.
	 *
	 * @param userSearchId the user search ID of this user search criteria
	 */
	public void setUserSearchId(long userSearchId);

	/**
	 * Returns the search name of this user search criteria.
	 *
	 * @return the search name of this user search criteria
	 */
	@AutoEscape
	public String getSearchName();

	/**
	 * Sets the search name of this user search criteria.
	 *
	 * @param searchName the search name of this user search criteria
	 */
	public void setSearchName(String searchName);

	/**
	 * Returns the search criteria of this user search criteria.
	 *
	 * @return the search criteria of this user search criteria
	 */
	@AutoEscape
	public String getSearchCriteria();

	/**
	 * Sets the search criteria of this user search criteria.
	 *
	 * @param searchCriteria the search criteria of this user search criteria
	 */
	public void setSearchCriteria(String searchCriteria);

	/**
	 * Returns the creator ID of this user search criteria.
	 *
	 * @return the creator ID of this user search criteria
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this user search criteria.
	 *
	 * @param creatorId the creator ID of this user search criteria
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this user search criteria.
	 *
	 * @return the created date of this user search criteria
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this user search criteria.
	 *
	 * @param createdDate the created date of this user search criteria
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this user search criteria.
	 *
	 * @return the updated by of this user search criteria
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this user search criteria.
	 *
	 * @param updatedBy the updated by of this user search criteria
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this user search criteria.
	 *
	 * @return the updated date of this user search criteria
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this user search criteria.
	 *
	 * @param updatedDate the updated date of this user search criteria
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the module name of this user search criteria.
	 *
	 * @return the module name of this user search criteria
	 */
	@AutoEscape
	public String getModuleName();

	/**
	 * Sets the module name of this user search criteria.
	 *
	 * @param moduleName the module name of this user search criteria
	 */
	public void setModuleName(String moduleName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserSearchCriteria userSearchCriteria);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserSearchCriteria> toCacheModel();

	@Override
	public UserSearchCriteria toEscapedModel();

	@Override
	public UserSearchCriteria toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}