/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Workflow service. Represents a row in the &quot;WORKFLOW_ACTV_LOG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.WorkflowModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.WorkflowImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see Workflow
 * @see com.ihg.brandstandards.db.model.impl.WorkflowImpl
 * @see com.ihg.brandstandards.db.model.impl.WorkflowModelImpl
 * @generated
 */
public interface WorkflowModel extends BaseModel<Workflow> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a workflow model instance should use the {@link Workflow} interface instead.
	 */

	/**
	 * Returns the primary key of this workflow.
	 *
	 * @return the primary key of this workflow
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this workflow.
	 *
	 * @param primaryKey the primary key of this workflow
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the workflow actvt ID of this workflow.
	 *
	 * @return the workflow actvt ID of this workflow
	 */
	public long getWorkflowActvtId();

	/**
	 * Sets the workflow actvt ID of this workflow.
	 *
	 * @param workflowActvtId the workflow actvt ID of this workflow
	 */
	public void setWorkflowActvtId(long workflowActvtId);

	/**
	 * Returns the object ID of this workflow.
	 *
	 * @return the object ID of this workflow
	 */
	public long getObjectId();

	/**
	 * Sets the object ID of this workflow.
	 *
	 * @param objectId the object ID of this workflow
	 */
	public void setObjectId(long objectId);

	/**
	 * Returns the object type of this workflow.
	 *
	 * @return the object type of this workflow
	 */
	@AutoEscape
	public String getObjectType();

	/**
	 * Sets the object type of this workflow.
	 *
	 * @param objectType the object type of this workflow
	 */
	public void setObjectType(String objectType);

	/**
	 * Returns the status of this workflow.
	 *
	 * @return the status of this workflow
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this workflow.
	 *
	 * @param status the status of this workflow
	 */
	public void setStatus(String status);

	/**
	 * Returns the prev status of this workflow.
	 *
	 * @return the prev status of this workflow
	 */
	@AutoEscape
	public String getPrevStatus();

	/**
	 * Sets the prev status of this workflow.
	 *
	 * @param prevStatus the prev status of this workflow
	 */
	public void setPrevStatus(String prevStatus);

	/**
	 * Returns the title of this workflow.
	 *
	 * @return the title of this workflow
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this workflow.
	 *
	 * @param title the title of this workflow
	 */
	public void setTitle(String title);

	/**
	 * Returns the comment of this workflow.
	 *
	 * @return the comment of this workflow
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this workflow.
	 *
	 * @param comment the comment of this workflow
	 */
	public void setComment(String comment);

	/**
	 * Returns the created by of this workflow.
	 *
	 * @return the created by of this workflow
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this workflow.
	 *
	 * @param createdBy the created by of this workflow
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the chain code of this workflow.
	 *
	 * @return the chain code of this workflow
	 */
	@AutoEscape
	public String getChainCode();

	/**
	 * Sets the chain code of this workflow.
	 *
	 * @param chainCode the chain code of this workflow
	 */
	public void setChainCode(String chainCode);

	/**
	 * Returns the creator ID of this workflow.
	 *
	 * @return the creator ID of this workflow
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this workflow.
	 *
	 * @param creatorId the creator ID of this workflow
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this workflow.
	 *
	 * @return the created date of this workflow
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this workflow.
	 *
	 * @param createdDate the created date of this workflow
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this workflow.
	 *
	 * @return the updated by of this workflow
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this workflow.
	 *
	 * @param updatedBy the updated by of this workflow
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this workflow.
	 *
	 * @return the updated date of this workflow
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this workflow.
	 *
	 * @param updatedDate the updated date of this workflow
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Workflow workflow);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Workflow> toCacheModel();

	@Override
	public Workflow toEscapedModel();

	@Override
	public Workflow toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}