/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.BrandTaxonomy;
import com.ihg.brandstandards.db.model.BrandTaxonomyModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the BrandTaxonomy service. Represents a row in the &quot;Brand_Taxonomy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.BrandTaxonomyModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BrandTaxonomyImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see BrandTaxonomyImpl
 * @see com.ihg.brandstandards.db.model.BrandTaxonomy
 * @see com.ihg.brandstandards.db.model.BrandTaxonomyModel
 * @generated
 */
public class BrandTaxonomyModelImpl extends BaseModelImpl<BrandTaxonomy>
	implements BrandTaxonomyModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a brand taxonomy model instance should use the {@link com.ihg.brandstandards.db.model.BrandTaxonomy} interface instead.
	 */
	public static final String TABLE_NAME = "Brand_Taxonomy";
	public static final Object[][] TABLE_COLUMNS = {
			{ "BRAND_TAXONOMY_ID", Types.BIGINT },
			{ "TAXONOMY_ID", Types.BIGINT },
			{ "CHAIN_CD", Types.VARCHAR },
			{ "TITLE_TXT", Types.VARCHAR },
			{ "BRAND_TAXOMOMY_DESC", Types.VARCHAR },
			{ "IMAGE_PATH_TXT", Types.VARCHAR },
			{ "CREATOR_SCRN_NM", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table Brand_Taxonomy (BRAND_TAXONOMY_ID LONG not null primary key,TAXONOMY_ID LONG,CHAIN_CD VARCHAR(75) null,TITLE_TXT VARCHAR(75) null,BRAND_TAXOMOMY_DESC VARCHAR(75) null,IMAGE_PATH_TXT VARCHAR(75) null,CREATOR_SCRN_NM VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table Brand_Taxonomy";
	public static final String ORDER_BY_JPQL = " ORDER BY brandTaxonomy.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Brand_Taxonomy.BRAND_TAXONOMY_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.BrandTaxonomy"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.BrandTaxonomy"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.BrandTaxonomy"),
			true);
	public static long CHAIN_COLUMN_BITMASK = 1L;
	public static long CREATORID_COLUMN_BITMASK = 2L;
	public static long ID_COLUMN_BITMASK = 4L;
	public static long TAXID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.BrandTaxonomy"));

	public BrandTaxonomyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BrandTaxonomy.class;
	}

	@Override
	public String getModelClassName() {
		return BrandTaxonomy.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("taxId", getTaxId());
		attributes.put("chain", getChain());
		attributes.put("title", getTitle());
		attributes.put("desc", getDesc());
		attributes.put("imageLoc", getImageLoc());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long taxId = (Long)attributes.get("taxId");

		if (taxId != null) {
			setTaxId(taxId);
		}

		String chain = (String)attributes.get("chain");

		if (chain != null) {
			setChain(chain);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String desc = (String)attributes.get("desc");

		if (desc != null) {
			setDesc(desc);
		}

		String imageLoc = (String)attributes.get("imageLoc");

		if (imageLoc != null) {
			setImageLoc(imageLoc);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask |= ID_COLUMN_BITMASK;

		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	@Override
	public long getTaxId() {
		return _taxId;
	}

	@Override
	public void setTaxId(long taxId) {
		_columnBitmask |= TAXID_COLUMN_BITMASK;

		if (!_setOriginalTaxId) {
			_setOriginalTaxId = true;

			_originalTaxId = _taxId;
		}

		_taxId = taxId;
	}

	public long getOriginalTaxId() {
		return _originalTaxId;
	}

	@Override
	public String getChain() {
		if (_chain == null) {
			return StringPool.BLANK;
		}
		else {
			return _chain;
		}
	}

	@Override
	public void setChain(String chain) {
		_columnBitmask |= CHAIN_COLUMN_BITMASK;

		if (_originalChain == null) {
			_originalChain = _chain;
		}

		_chain = chain;
	}

	public String getOriginalChain() {
		return GetterUtil.getString(_originalChain);
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getDesc() {
		if (_desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _desc;
		}
	}

	@Override
	public void setDesc(String desc) {
		_desc = desc;
	}

	@Override
	public String getImageLoc() {
		if (_imageLoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageLoc;
		}
	}

	@Override
	public void setImageLoc(String imageLoc) {
		_imageLoc = imageLoc;
	}

	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_columnBitmask |= CREATORID_COLUMN_BITMASK;

		if (_originalCreatorId == null) {
			_originalCreatorId = _creatorId;
		}

		_creatorId = creatorId;
	}

	public String getOriginalCreatorId() {
		return GetterUtil.getString(_originalCreatorId);
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			BrandTaxonomy.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BrandTaxonomy toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BrandTaxonomy)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BrandTaxonomyImpl brandTaxonomyImpl = new BrandTaxonomyImpl();

		brandTaxonomyImpl.setId(getId());
		brandTaxonomyImpl.setTaxId(getTaxId());
		brandTaxonomyImpl.setChain(getChain());
		brandTaxonomyImpl.setTitle(getTitle());
		brandTaxonomyImpl.setDesc(getDesc());
		brandTaxonomyImpl.setImageLoc(getImageLoc());
		brandTaxonomyImpl.setCreatedBy(getCreatedBy());
		brandTaxonomyImpl.setCreatorId(getCreatorId());
		brandTaxonomyImpl.setCreatedDate(getCreatedDate());
		brandTaxonomyImpl.setUpdatedBy(getUpdatedBy());
		brandTaxonomyImpl.setUpdatedDate(getUpdatedDate());

		brandTaxonomyImpl.resetOriginalValues();

		return brandTaxonomyImpl;
	}

	@Override
	public int compareTo(BrandTaxonomy brandTaxonomy) {
		long primaryKey = brandTaxonomy.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BrandTaxonomy)) {
			return false;
		}

		BrandTaxonomy brandTaxonomy = (BrandTaxonomy)obj;

		long primaryKey = brandTaxonomy.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BrandTaxonomyModelImpl brandTaxonomyModelImpl = this;

		brandTaxonomyModelImpl._originalId = brandTaxonomyModelImpl._id;

		brandTaxonomyModelImpl._setOriginalId = false;

		brandTaxonomyModelImpl._originalTaxId = brandTaxonomyModelImpl._taxId;

		brandTaxonomyModelImpl._setOriginalTaxId = false;

		brandTaxonomyModelImpl._originalChain = brandTaxonomyModelImpl._chain;

		brandTaxonomyModelImpl._originalCreatorId = brandTaxonomyModelImpl._creatorId;

		brandTaxonomyModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BrandTaxonomy> toCacheModel() {
		BrandTaxonomyCacheModel brandTaxonomyCacheModel = new BrandTaxonomyCacheModel();

		brandTaxonomyCacheModel.id = getId();

		brandTaxonomyCacheModel.taxId = getTaxId();

		brandTaxonomyCacheModel.chain = getChain();

		String chain = brandTaxonomyCacheModel.chain;

		if ((chain != null) && (chain.length() == 0)) {
			brandTaxonomyCacheModel.chain = null;
		}

		brandTaxonomyCacheModel.title = getTitle();

		String title = brandTaxonomyCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			brandTaxonomyCacheModel.title = null;
		}

		brandTaxonomyCacheModel.desc = getDesc();

		String desc = brandTaxonomyCacheModel.desc;

		if ((desc != null) && (desc.length() == 0)) {
			brandTaxonomyCacheModel.desc = null;
		}

		brandTaxonomyCacheModel.imageLoc = getImageLoc();

		String imageLoc = brandTaxonomyCacheModel.imageLoc;

		if ((imageLoc != null) && (imageLoc.length() == 0)) {
			brandTaxonomyCacheModel.imageLoc = null;
		}

		brandTaxonomyCacheModel.createdBy = getCreatedBy();

		String createdBy = brandTaxonomyCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			brandTaxonomyCacheModel.createdBy = null;
		}

		brandTaxonomyCacheModel.creatorId = getCreatorId();

		String creatorId = brandTaxonomyCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			brandTaxonomyCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			brandTaxonomyCacheModel.createdDate = createdDate.getTime();
		}
		else {
			brandTaxonomyCacheModel.createdDate = Long.MIN_VALUE;
		}

		brandTaxonomyCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = brandTaxonomyCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			brandTaxonomyCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			brandTaxonomyCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			brandTaxonomyCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return brandTaxonomyCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", taxId=");
		sb.append(getTaxId());
		sb.append(", chain=");
		sb.append(getChain());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", desc=");
		sb.append(getDesc());
		sb.append(", imageLoc=");
		sb.append(getImageLoc());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.BrandTaxonomy");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>taxId</column-name><column-value><![CDATA[");
		sb.append(getTaxId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chain</column-name><column-value><![CDATA[");
		sb.append(getChain());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>desc</column-name><column-value><![CDATA[");
		sb.append(getDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageLoc</column-name><column-value><![CDATA[");
		sb.append(getImageLoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = BrandTaxonomy.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			BrandTaxonomy.class
		};
	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private long _taxId;
	private long _originalTaxId;
	private boolean _setOriginalTaxId;
	private String _chain;
	private String _originalChain;
	private String _title;
	private String _desc;
	private String _imageLoc;
	private String _createdBy;
	private String _creatorId;
	private String _originalCreatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private BrandTaxonomy _escapedModel;
}