/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.FlagStandards;
import com.ihg.brandstandards.db.model.FlagStandardsModel;
import com.ihg.brandstandards.db.service.persistence.FlagStandardsPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the FlagStandards service. Represents a row in the &quot;FLAG_STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.FlagStandardsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FlagStandardsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see FlagStandardsImpl
 * @see com.ihg.brandstandards.db.model.FlagStandards
 * @see com.ihg.brandstandards.db.model.FlagStandardsModel
 * @generated
 */
public class FlagStandardsModelImpl extends BaseModelImpl<FlagStandards>
	implements FlagStandardsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a flag standards model instance should use the {@link com.ihg.brandstandards.db.model.FlagStandards} interface instead.
	 */
	public static final String TABLE_NAME = "FLAG_STD";
	public static final Object[][] TABLE_COLUMNS = {
			{ "FLAG_CATGY_ID", Types.BIGINT },
			{ "STD_ID", Types.BIGINT },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table FLAG_STD (FLAG_CATGY_ID LONG not null,STD_ID LONG not null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null,primary key (FLAG_CATGY_ID, STD_ID))";
	public static final String TABLE_SQL_DROP = "drop table FLAG_STD";
	public static final String ORDER_BY_JPQL = " ORDER BY flagStandards.id.flagCatId ASC, flagStandards.id.stdId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FLAG_STD.FLAG_CATGY_ID ASC, FLAG_STD.STD_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.FlagStandards"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.FlagStandards"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.FlagStandards"),
			true);
	public static long FLAGCATID_COLUMN_BITMASK = 1L;
	public static long STDID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.FlagStandards"));

	public FlagStandardsModelImpl() {
	}

	@Override
	public FlagStandardsPK getPrimaryKey() {
		return new FlagStandardsPK(_flagCatId, _stdId);
	}

	@Override
	public void setPrimaryKey(FlagStandardsPK primaryKey) {
		setFlagCatId(primaryKey.flagCatId);
		setStdId(primaryKey.stdId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new FlagStandardsPK(_flagCatId, _stdId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((FlagStandardsPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return FlagStandards.class;
	}

	@Override
	public String getModelClassName() {
		return FlagStandards.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("flagCatId", getFlagCatId());
		attributes.put("stdId", getStdId());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long flagCatId = (Long)attributes.get("flagCatId");

		if (flagCatId != null) {
			setFlagCatId(flagCatId);
		}

		Long stdId = (Long)attributes.get("stdId");

		if (stdId != null) {
			setStdId(stdId);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getFlagCatId() {
		return _flagCatId;
	}

	@Override
	public void setFlagCatId(long flagCatId) {
		_columnBitmask |= FLAGCATID_COLUMN_BITMASK;

		if (!_setOriginalFlagCatId) {
			_setOriginalFlagCatId = true;

			_originalFlagCatId = _flagCatId;
		}

		_flagCatId = flagCatId;
	}

	public long getOriginalFlagCatId() {
		return _originalFlagCatId;
	}

	@Override
	public long getStdId() {
		return _stdId;
	}

	@Override
	public void setStdId(long stdId) {
		_columnBitmask |= STDID_COLUMN_BITMASK;

		if (!_setOriginalStdId) {
			_setOriginalStdId = true;

			_originalStdId = _stdId;
		}

		_stdId = stdId;
	}

	public long getOriginalStdId() {
		return _originalStdId;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public FlagStandards toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (FlagStandards)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FlagStandardsImpl flagStandardsImpl = new FlagStandardsImpl();

		flagStandardsImpl.setFlagCatId(getFlagCatId());
		flagStandardsImpl.setStdId(getStdId());
		flagStandardsImpl.setCreatorId(getCreatorId());
		flagStandardsImpl.setCreatedDate(getCreatedDate());
		flagStandardsImpl.setUpdatedBy(getUpdatedBy());
		flagStandardsImpl.setUpdatedDate(getUpdatedDate());

		flagStandardsImpl.resetOriginalValues();

		return flagStandardsImpl;
	}

	@Override
	public int compareTo(FlagStandards flagStandards) {
		FlagStandardsPK primaryKey = flagStandards.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof FlagStandards)) {
			return false;
		}

		FlagStandards flagStandards = (FlagStandards)obj;

		FlagStandardsPK primaryKey = flagStandards.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		FlagStandardsModelImpl flagStandardsModelImpl = this;

		flagStandardsModelImpl._originalFlagCatId = flagStandardsModelImpl._flagCatId;

		flagStandardsModelImpl._setOriginalFlagCatId = false;

		flagStandardsModelImpl._originalStdId = flagStandardsModelImpl._stdId;

		flagStandardsModelImpl._setOriginalStdId = false;

		flagStandardsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<FlagStandards> toCacheModel() {
		FlagStandardsCacheModel flagStandardsCacheModel = new FlagStandardsCacheModel();

		flagStandardsCacheModel.flagCatId = getFlagCatId();

		flagStandardsCacheModel.stdId = getStdId();

		flagStandardsCacheModel.creatorId = getCreatorId();

		String creatorId = flagStandardsCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			flagStandardsCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			flagStandardsCacheModel.createdDate = createdDate.getTime();
		}
		else {
			flagStandardsCacheModel.createdDate = Long.MIN_VALUE;
		}

		flagStandardsCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = flagStandardsCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			flagStandardsCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			flagStandardsCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			flagStandardsCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return flagStandardsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{flagCatId=");
		sb.append(getFlagCatId());
		sb.append(", stdId=");
		sb.append(getStdId());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.FlagStandards");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>flagCatId</column-name><column-value><![CDATA[");
		sb.append(getFlagCatId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stdId</column-name><column-value><![CDATA[");
		sb.append(getStdId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = FlagStandards.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			FlagStandards.class
		};
	private long _flagCatId;
	private long _originalFlagCatId;
	private boolean _setOriginalFlagCatId;
	private long _stdId;
	private long _originalStdId;
	private boolean _setOriginalStdId;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private FlagStandards _escapedModel;
}