/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.grs.common.model.impl;

import com.ihg.grs.common.model.FeedbackDetail;
import com.ihg.grs.common.service.FeedbackDetailLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the FeedbackDetail service. Represents a row in the &quot;GRS_COMM.PORTAL_FEEDBACK_DTL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FeedbackDetailImpl}.
 * </p>
 *
 * @author gulam.vora
 * @see FeedbackDetailImpl
 * @see com.ihg.grs.common.model.FeedbackDetail
 * @generated
 */
public abstract class FeedbackDetailBaseImpl extends FeedbackDetailModelImpl
	implements FeedbackDetail {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a feedback detail model instance should use the {@link FeedbackDetail} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			FeedbackDetailLocalServiceUtil.addFeedbackDetail(this);
		}
		else {
			FeedbackDetailLocalServiceUtil.updateFeedbackDetail(this);
		}
	}
}