/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.PublishDept;
import com.ihg.brandstandards.db.model.PublishDeptModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the PublishDept service. Represents a row in the &quot;GEM_PUBLISH_DEPT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.PublishDeptModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PublishDeptImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see PublishDeptImpl
 * @see com.ihg.brandstandards.db.model.PublishDept
 * @see com.ihg.brandstandards.db.model.PublishDeptModel
 * @generated
 */
public class PublishDeptModelImpl extends BaseModelImpl<PublishDept>
	implements PublishDeptModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a publish dept model instance should use the {@link com.ihg.brandstandards.db.model.PublishDept} interface instead.
	 */
	public static final String TABLE_NAME = "GEM_PUBLISH_DEPT";
	public static final Object[][] TABLE_COLUMNS = {
			{ "GEM_PUBLISH_DEPT_ID", Types.BIGINT },
			{ "GEM_DEPT_ID", Types.BIGINT },
			{ "PUBLISH_ID", Types.BIGINT },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table GEM_PUBLISH_DEPT (GEM_PUBLISH_DEPT_ID LONG not null primary key,GEM_DEPT_ID LONG,PUBLISH_ID LONG,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table GEM_PUBLISH_DEPT";
	public static final String ORDER_BY_JPQL = " ORDER BY publishDept.publishDeptId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GEM_PUBLISH_DEPT.GEM_PUBLISH_DEPT_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.PublishDept"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.PublishDept"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.PublishDept"),
			true);
	public static long DEPTID_COLUMN_BITMASK = 1L;
	public static long PUBLISHID_COLUMN_BITMASK = 2L;
	public static long PUBLISHDEPTID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.PublishDept"));

	public PublishDeptModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _publishDeptId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPublishDeptId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _publishDeptId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PublishDept.class;
	}

	@Override
	public String getModelClassName() {
		return PublishDept.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("publishDeptId", getPublishDeptId());
		attributes.put("deptId", getDeptId());
		attributes.put("publishId", getPublishId());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long publishDeptId = (Long)attributes.get("publishDeptId");

		if (publishDeptId != null) {
			setPublishDeptId(publishDeptId);
		}

		Long deptId = (Long)attributes.get("deptId");

		if (deptId != null) {
			setDeptId(deptId);
		}

		Long publishId = (Long)attributes.get("publishId");

		if (publishId != null) {
			setPublishId(publishId);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getPublishDeptId() {
		return _publishDeptId;
	}

	@Override
	public void setPublishDeptId(long publishDeptId) {
		_columnBitmask = -1L;

		_publishDeptId = publishDeptId;
	}

	@Override
	public long getDeptId() {
		return _deptId;
	}

	@Override
	public void setDeptId(long deptId) {
		_columnBitmask |= DEPTID_COLUMN_BITMASK;

		if (!_setOriginalDeptId) {
			_setOriginalDeptId = true;

			_originalDeptId = _deptId;
		}

		_deptId = deptId;
	}

	public long getOriginalDeptId() {
		return _originalDeptId;
	}

	@Override
	public long getPublishId() {
		return _publishId;
	}

	@Override
	public void setPublishId(long publishId) {
		_columnBitmask |= PUBLISHID_COLUMN_BITMASK;

		if (!_setOriginalPublishId) {
			_setOriginalPublishId = true;

			_originalPublishId = _publishId;
		}

		_publishId = publishId;
	}

	public long getOriginalPublishId() {
		return _originalPublishId;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			PublishDept.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PublishDept toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (PublishDept)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PublishDeptImpl publishDeptImpl = new PublishDeptImpl();

		publishDeptImpl.setPublishDeptId(getPublishDeptId());
		publishDeptImpl.setDeptId(getDeptId());
		publishDeptImpl.setPublishId(getPublishId());
		publishDeptImpl.setCreatorId(getCreatorId());
		publishDeptImpl.setCreatedDate(getCreatedDate());
		publishDeptImpl.setUpdatedBy(getUpdatedBy());
		publishDeptImpl.setUpdatedDate(getUpdatedDate());

		publishDeptImpl.resetOriginalValues();

		return publishDeptImpl;
	}

	@Override
	public int compareTo(PublishDept publishDept) {
		int value = 0;

		if (getPublishDeptId() < publishDept.getPublishDeptId()) {
			value = -1;
		}
		else if (getPublishDeptId() > publishDept.getPublishDeptId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof PublishDept)) {
			return false;
		}

		PublishDept publishDept = (PublishDept)obj;

		long primaryKey = publishDept.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		PublishDeptModelImpl publishDeptModelImpl = this;

		publishDeptModelImpl._originalDeptId = publishDeptModelImpl._deptId;

		publishDeptModelImpl._setOriginalDeptId = false;

		publishDeptModelImpl._originalPublishId = publishDeptModelImpl._publishId;

		publishDeptModelImpl._setOriginalPublishId = false;

		publishDeptModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PublishDept> toCacheModel() {
		PublishDeptCacheModel publishDeptCacheModel = new PublishDeptCacheModel();

		publishDeptCacheModel.publishDeptId = getPublishDeptId();

		publishDeptCacheModel.deptId = getDeptId();

		publishDeptCacheModel.publishId = getPublishId();

		publishDeptCacheModel.creatorId = getCreatorId();

		String creatorId = publishDeptCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			publishDeptCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			publishDeptCacheModel.createdDate = createdDate.getTime();
		}
		else {
			publishDeptCacheModel.createdDate = Long.MIN_VALUE;
		}

		publishDeptCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = publishDeptCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			publishDeptCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			publishDeptCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			publishDeptCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return publishDeptCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{publishDeptId=");
		sb.append(getPublishDeptId());
		sb.append(", deptId=");
		sb.append(getDeptId());
		sb.append(", publishId=");
		sb.append(getPublishId());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.PublishDept");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>publishDeptId</column-name><column-value><![CDATA[");
		sb.append(getPublishDeptId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deptId</column-name><column-value><![CDATA[");
		sb.append(getDeptId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publishId</column-name><column-value><![CDATA[");
		sb.append(getPublishId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = PublishDept.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			PublishDept.class
		};
	private long _publishDeptId;
	private long _deptId;
	private long _originalDeptId;
	private boolean _setOriginalDeptId;
	private long _publishId;
	private long _originalPublishId;
	private boolean _setOriginalPublishId;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private PublishDept _escapedModel;
}