/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.StandardsCrossReference;
import com.ihg.brandstandards.db.model.StandardsCrossReferenceModel;
import com.ihg.brandstandards.db.service.persistence.StandardsCrossReferencePK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the StandardsCrossReference service. Represents a row in the &quot;STD_XREF&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.StandardsCrossReferenceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StandardsCrossReferenceImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsCrossReferenceImpl
 * @see com.ihg.brandstandards.db.model.StandardsCrossReference
 * @see com.ihg.brandstandards.db.model.StandardsCrossReferenceModel
 * @generated
 */
public class StandardsCrossReferenceModelImpl extends BaseModelImpl<StandardsCrossReference>
	implements StandardsCrossReferenceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a standards cross reference model instance should use the {@link com.ihg.brandstandards.db.model.StandardsCrossReference} interface instead.
	 */
	public static final String TABLE_NAME = "STD_XREF";
	public static final Object[][] TABLE_COLUMNS = {
			{ "REFERRING_STD_ID", Types.BIGINT },
			{ "REFERENCED_STD_ID", Types.BIGINT },
			{ "DISP_ORDER_NBR", Types.BIGINT },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table STD_XREF (REFERRING_STD_ID LONG not null,REFERENCED_STD_ID LONG not null,DISP_ORDER_NBR LONG,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null,primary key (REFERRING_STD_ID, REFERENCED_STD_ID))";
	public static final String TABLE_SQL_DROP = "drop table STD_XREF";
	public static final String ORDER_BY_JPQL = " ORDER BY standardsCrossReference.id.stdId ASC, standardsCrossReference.id.xrefStdId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY STD_XREF.REFERRING_STD_ID ASC, STD_XREF.REFERENCED_STD_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.StandardsCrossReference"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.StandardsCrossReference"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.StandardsCrossReference"),
			true);
	public static long STDID_COLUMN_BITMASK = 1L;
	public static long XREFSTDID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.StandardsCrossReference"));

	public StandardsCrossReferenceModelImpl() {
	}

	@Override
	public StandardsCrossReferencePK getPrimaryKey() {
		return new StandardsCrossReferencePK(_stdId, _xrefStdId);
	}

	@Override
	public void setPrimaryKey(StandardsCrossReferencePK primaryKey) {
		setStdId(primaryKey.stdId);
		setXrefStdId(primaryKey.xrefStdId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new StandardsCrossReferencePK(_stdId, _xrefStdId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((StandardsCrossReferencePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return StandardsCrossReference.class;
	}

	@Override
	public String getModelClassName() {
		return StandardsCrossReference.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("stdId", getStdId());
		attributes.put("xrefStdId", getXrefStdId());
		attributes.put("dispOrderNumber", getDispOrderNumber());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long stdId = (Long)attributes.get("stdId");

		if (stdId != null) {
			setStdId(stdId);
		}

		Long xrefStdId = (Long)attributes.get("xrefStdId");

		if (xrefStdId != null) {
			setXrefStdId(xrefStdId);
		}

		Long dispOrderNumber = (Long)attributes.get("dispOrderNumber");

		if (dispOrderNumber != null) {
			setDispOrderNumber(dispOrderNumber);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getStdId() {
		return _stdId;
	}

	@Override
	public void setStdId(long stdId) {
		_columnBitmask |= STDID_COLUMN_BITMASK;

		if (!_setOriginalStdId) {
			_setOriginalStdId = true;

			_originalStdId = _stdId;
		}

		_stdId = stdId;
	}

	public long getOriginalStdId() {
		return _originalStdId;
	}

	@Override
	public long getXrefStdId() {
		return _xrefStdId;
	}

	@Override
	public void setXrefStdId(long xrefStdId) {
		_columnBitmask |= XREFSTDID_COLUMN_BITMASK;

		if (!_setOriginalXrefStdId) {
			_setOriginalXrefStdId = true;

			_originalXrefStdId = _xrefStdId;
		}

		_xrefStdId = xrefStdId;
	}

	public long getOriginalXrefStdId() {
		return _originalXrefStdId;
	}

	@Override
	public long getDispOrderNumber() {
		return _dispOrderNumber;
	}

	@Override
	public void setDispOrderNumber(long dispOrderNumber) {
		_dispOrderNumber = dispOrderNumber;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public StandardsCrossReference toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StandardsCrossReference)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StandardsCrossReferenceImpl standardsCrossReferenceImpl = new StandardsCrossReferenceImpl();

		standardsCrossReferenceImpl.setStdId(getStdId());
		standardsCrossReferenceImpl.setXrefStdId(getXrefStdId());
		standardsCrossReferenceImpl.setDispOrderNumber(getDispOrderNumber());
		standardsCrossReferenceImpl.setCreatorId(getCreatorId());
		standardsCrossReferenceImpl.setCreatedDate(getCreatedDate());
		standardsCrossReferenceImpl.setUpdatedBy(getUpdatedBy());
		standardsCrossReferenceImpl.setUpdatedDate(getUpdatedDate());

		standardsCrossReferenceImpl.resetOriginalValues();

		return standardsCrossReferenceImpl;
	}

	@Override
	public int compareTo(StandardsCrossReference standardsCrossReference) {
		StandardsCrossReferencePK primaryKey = standardsCrossReference.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StandardsCrossReference)) {
			return false;
		}

		StandardsCrossReference standardsCrossReference = (StandardsCrossReference)obj;

		StandardsCrossReferencePK primaryKey = standardsCrossReference.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		StandardsCrossReferenceModelImpl standardsCrossReferenceModelImpl = this;

		standardsCrossReferenceModelImpl._originalStdId = standardsCrossReferenceModelImpl._stdId;

		standardsCrossReferenceModelImpl._setOriginalStdId = false;

		standardsCrossReferenceModelImpl._originalXrefStdId = standardsCrossReferenceModelImpl._xrefStdId;

		standardsCrossReferenceModelImpl._setOriginalXrefStdId = false;

		standardsCrossReferenceModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<StandardsCrossReference> toCacheModel() {
		StandardsCrossReferenceCacheModel standardsCrossReferenceCacheModel = new StandardsCrossReferenceCacheModel();

		standardsCrossReferenceCacheModel.stdId = getStdId();

		standardsCrossReferenceCacheModel.xrefStdId = getXrefStdId();

		standardsCrossReferenceCacheModel.dispOrderNumber = getDispOrderNumber();

		standardsCrossReferenceCacheModel.creatorId = getCreatorId();

		String creatorId = standardsCrossReferenceCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			standardsCrossReferenceCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			standardsCrossReferenceCacheModel.createdDate = createdDate.getTime();
		}
		else {
			standardsCrossReferenceCacheModel.createdDate = Long.MIN_VALUE;
		}

		standardsCrossReferenceCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = standardsCrossReferenceCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			standardsCrossReferenceCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			standardsCrossReferenceCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			standardsCrossReferenceCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return standardsCrossReferenceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{stdId=");
		sb.append(getStdId());
		sb.append(", xrefStdId=");
		sb.append(getXrefStdId());
		sb.append(", dispOrderNumber=");
		sb.append(getDispOrderNumber());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.StandardsCrossReference");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>stdId</column-name><column-value><![CDATA[");
		sb.append(getStdId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>xrefStdId</column-name><column-value><![CDATA[");
		sb.append(getXrefStdId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dispOrderNumber</column-name><column-value><![CDATA[");
		sb.append(getDispOrderNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = StandardsCrossReference.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			StandardsCrossReference.class
		};
	private long _stdId;
	private long _originalStdId;
	private boolean _setOriginalStdId;
	private long _xrefStdId;
	private long _originalXrefStdId;
	private boolean _setOriginalXrefStdId;
	private long _dispOrderNumber;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private StandardsCrossReference _escapedModel;
}