/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsRegion service. Represents a row in the &quot;BRNDSTND_RGN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsRegionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsRegionImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsRegion
 * @see com.ihg.brandstandards.db.model.impl.StandardsRegionImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsRegionModelImpl
 * @generated
 */
public interface StandardsRegionModel extends BaseModel<StandardsRegion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards region model instance should use the {@link StandardsRegion} interface instead.
	 */

	/**
	 * Returns the primary key of this standards region.
	 *
	 * @return the primary key of this standards region
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this standards region.
	 *
	 * @param primaryKey the primary key of this standards region
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the region ID of this standards region.
	 *
	 * @return the region ID of this standards region
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this standards region.
	 *
	 * @param regionId the region ID of this standards region
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the region code of this standards region.
	 *
	 * @return the region code of this standards region
	 */
	@AutoEscape
	public String getRegionCode();

	/**
	 * Sets the region code of this standards region.
	 *
	 * @param regionCode the region code of this standards region
	 */
	public void setRegionCode(String regionCode);

	/**
	 * Returns the region type of this standards region.
	 *
	 * @return the region type of this standards region
	 */
	@AutoEscape
	public String getRegionType();

	/**
	 * Sets the region type of this standards region.
	 *
	 * @param regionType the region type of this standards region
	 */
	public void setRegionType(String regionType);

	/**
	 * Returns the region name of this standards region.
	 *
	 * @return the region name of this standards region
	 */
	@AutoEscape
	public String getRegionName();

	/**
	 * Sets the region name of this standards region.
	 *
	 * @param regionName the region name of this standards region
	 */
	public void setRegionName(String regionName);

	/**
	 * Returns the is active of this standards region.
	 *
	 * @return the is active of this standards region
	 */
	@AutoEscape
	public String getIsActive();

	/**
	 * Sets the is active of this standards region.
	 *
	 * @param isActive the is active of this standards region
	 */
	public void setIsActive(String isActive);

	/**
	 * Returns the creator ID of this standards region.
	 *
	 * @return the creator ID of this standards region
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards region.
	 *
	 * @param creatorId the creator ID of this standards region
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards region.
	 *
	 * @return the created date of this standards region
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards region.
	 *
	 * @param createdDate the created date of this standards region
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards region.
	 *
	 * @return the updated by of this standards region
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards region.
	 *
	 * @param updatedBy the updated by of this standards region
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards region.
	 *
	 * @return the updated date of this standards region
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards region.
	 *
	 * @param updatedDate the updated date of this standards region
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsRegion standardsRegion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsRegion> toCacheModel();

	@Override
	public StandardsRegion toEscapedModel();

	@Override
	public StandardsRegion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}