/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.GEMScoringValue;
import com.ihg.brandstandards.db.model.GEMScoringValueModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the GEMScoringValue service. Represents a row in the &quot;SCORING_VAL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.GEMScoringValueModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GEMScoringValueImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMScoringValueImpl
 * @see com.ihg.brandstandards.db.model.GEMScoringValue
 * @see com.ihg.brandstandards.db.model.GEMScoringValueModel
 * @generated
 */
public class GEMScoringValueModelImpl extends BaseModelImpl<GEMScoringValue>
	implements GEMScoringValueModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a g e m scoring value model instance should use the {@link com.ihg.brandstandards.db.model.GEMScoringValue} interface instead.
	 */
	public static final String TABLE_NAME = "SCORING_VAL";
	public static final Object[][] TABLE_COLUMNS = {
			{ "SCORING_VAL_ID", Types.BIGINT },
			{ "GEM_MSRMNT_BUCKET_CHAIN_ID", Types.BIGINT },
			{ "TOT_MSRMNT_QTY", Types.BIGINT },
			{ "NET_MSRMNT_QTY", Types.BIGINT },
			{ "NON_COMPLIANT_MSRMNT_QTY", Types.BIGINT },
			{ "NON_COMPLIANT_MSRMNT_PCT", Types.BIGINT },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SCORING_VAL (SCORING_VAL_ID LONG not null primary key,GEM_MSRMNT_BUCKET_CHAIN_ID LONG,TOT_MSRMNT_QTY LONG,NET_MSRMNT_QTY LONG,NON_COMPLIANT_MSRMNT_QTY LONG,NON_COMPLIANT_MSRMNT_PCT LONG,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table SCORING_VAL";
	public static final String ORDER_BY_JPQL = " ORDER BY gemScoringValue.scoringId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY SCORING_VAL.SCORING_VAL_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.GEMScoringValue"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.GEMScoringValue"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.GEMScoringValue"));

	public GEMScoringValueModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scoringId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScoringId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scoringId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GEMScoringValue.class;
	}

	@Override
	public String getModelClassName() {
		return GEMScoringValue.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("scoringId", getScoringId());
		attributes.put("measurementBucketChainId", getMeasurementBucketChainId());
		attributes.put("totalMeasurement", getTotalMeasurement());
		attributes.put("netMeasurement", getNetMeasurement());
		attributes.put("nonCompliantMeasurement", getNonCompliantMeasurement());
		attributes.put("nonCompliantMeasurementPercent",
			getNonCompliantMeasurementPercent());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long scoringId = (Long)attributes.get("scoringId");

		if (scoringId != null) {
			setScoringId(scoringId);
		}

		Long measurementBucketChainId = (Long)attributes.get(
				"measurementBucketChainId");

		if (measurementBucketChainId != null) {
			setMeasurementBucketChainId(measurementBucketChainId);
		}

		Long totalMeasurement = (Long)attributes.get("totalMeasurement");

		if (totalMeasurement != null) {
			setTotalMeasurement(totalMeasurement);
		}

		Long netMeasurement = (Long)attributes.get("netMeasurement");

		if (netMeasurement != null) {
			setNetMeasurement(netMeasurement);
		}

		Long nonCompliantMeasurement = (Long)attributes.get(
				"nonCompliantMeasurement");

		if (nonCompliantMeasurement != null) {
			setNonCompliantMeasurement(nonCompliantMeasurement);
		}

		Long nonCompliantMeasurementPercent = (Long)attributes.get(
				"nonCompliantMeasurementPercent");

		if (nonCompliantMeasurementPercent != null) {
			setNonCompliantMeasurementPercent(nonCompliantMeasurementPercent);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getScoringId() {
		return _scoringId;
	}

	@Override
	public void setScoringId(long scoringId) {
		_scoringId = scoringId;
	}

	@Override
	public long getMeasurementBucketChainId() {
		return _measurementBucketChainId;
	}

	@Override
	public void setMeasurementBucketChainId(long measurementBucketChainId) {
		_measurementBucketChainId = measurementBucketChainId;
	}

	@Override
	public long getTotalMeasurement() {
		return _totalMeasurement;
	}

	@Override
	public void setTotalMeasurement(long totalMeasurement) {
		_totalMeasurement = totalMeasurement;
	}

	@Override
	public long getNetMeasurement() {
		return _netMeasurement;
	}

	@Override
	public void setNetMeasurement(long netMeasurement) {
		_netMeasurement = netMeasurement;
	}

	@Override
	public long getNonCompliantMeasurement() {
		return _nonCompliantMeasurement;
	}

	@Override
	public void setNonCompliantMeasurement(long nonCompliantMeasurement) {
		_nonCompliantMeasurement = nonCompliantMeasurement;
	}

	@Override
	public long getNonCompliantMeasurementPercent() {
		return _nonCompliantMeasurementPercent;
	}

	@Override
	public void setNonCompliantMeasurementPercent(
		long nonCompliantMeasurementPercent) {
		_nonCompliantMeasurementPercent = nonCompliantMeasurementPercent;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			GEMScoringValue.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GEMScoringValue toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (GEMScoringValue)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GEMScoringValueImpl gemScoringValueImpl = new GEMScoringValueImpl();

		gemScoringValueImpl.setScoringId(getScoringId());
		gemScoringValueImpl.setMeasurementBucketChainId(getMeasurementBucketChainId());
		gemScoringValueImpl.setTotalMeasurement(getTotalMeasurement());
		gemScoringValueImpl.setNetMeasurement(getNetMeasurement());
		gemScoringValueImpl.setNonCompliantMeasurement(getNonCompliantMeasurement());
		gemScoringValueImpl.setNonCompliantMeasurementPercent(getNonCompliantMeasurementPercent());
		gemScoringValueImpl.setCreatorId(getCreatorId());
		gemScoringValueImpl.setCreatedDate(getCreatedDate());
		gemScoringValueImpl.setUpdatedBy(getUpdatedBy());
		gemScoringValueImpl.setUpdatedDate(getUpdatedDate());

		gemScoringValueImpl.resetOriginalValues();

		return gemScoringValueImpl;
	}

	@Override
	public int compareTo(GEMScoringValue gemScoringValue) {
		long primaryKey = gemScoringValue.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GEMScoringValue)) {
			return false;
		}

		GEMScoringValue gemScoringValue = (GEMScoringValue)obj;

		long primaryKey = gemScoringValue.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<GEMScoringValue> toCacheModel() {
		GEMScoringValueCacheModel gemScoringValueCacheModel = new GEMScoringValueCacheModel();

		gemScoringValueCacheModel.scoringId = getScoringId();

		gemScoringValueCacheModel.measurementBucketChainId = getMeasurementBucketChainId();

		gemScoringValueCacheModel.totalMeasurement = getTotalMeasurement();

		gemScoringValueCacheModel.netMeasurement = getNetMeasurement();

		gemScoringValueCacheModel.nonCompliantMeasurement = getNonCompliantMeasurement();

		gemScoringValueCacheModel.nonCompliantMeasurementPercent = getNonCompliantMeasurementPercent();

		gemScoringValueCacheModel.creatorId = getCreatorId();

		String creatorId = gemScoringValueCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			gemScoringValueCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			gemScoringValueCacheModel.createdDate = createdDate.getTime();
		}
		else {
			gemScoringValueCacheModel.createdDate = Long.MIN_VALUE;
		}

		gemScoringValueCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = gemScoringValueCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			gemScoringValueCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			gemScoringValueCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			gemScoringValueCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return gemScoringValueCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{scoringId=");
		sb.append(getScoringId());
		sb.append(", measurementBucketChainId=");
		sb.append(getMeasurementBucketChainId());
		sb.append(", totalMeasurement=");
		sb.append(getTotalMeasurement());
		sb.append(", netMeasurement=");
		sb.append(getNetMeasurement());
		sb.append(", nonCompliantMeasurement=");
		sb.append(getNonCompliantMeasurement());
		sb.append(", nonCompliantMeasurementPercent=");
		sb.append(getNonCompliantMeasurementPercent());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.GEMScoringValue");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>scoringId</column-name><column-value><![CDATA[");
		sb.append(getScoringId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>measurementBucketChainId</column-name><column-value><![CDATA[");
		sb.append(getMeasurementBucketChainId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>totalMeasurement</column-name><column-value><![CDATA[");
		sb.append(getTotalMeasurement());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>netMeasurement</column-name><column-value><![CDATA[");
		sb.append(getNetMeasurement());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nonCompliantMeasurement</column-name><column-value><![CDATA[");
		sb.append(getNonCompliantMeasurement());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nonCompliantMeasurementPercent</column-name><column-value><![CDATA[");
		sb.append(getNonCompliantMeasurementPercent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = GEMScoringValue.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			GEMScoringValue.class
		};
	private long _scoringId;
	private long _measurementBucketChainId;
	private long _totalMeasurement;
	private long _netMeasurement;
	private long _nonCompliantMeasurement;
	private long _nonCompliantMeasurementPercent;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private GEMScoringValue _escapedModel;
}