/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.grs.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.sql.Blob;

import java.util.Date;

/**
 * The base model interface for the FeedbackDetail service. Represents a row in the &quot;GRS_COMM.PORTAL_FEEDBACK_DTL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.grs.common.model.impl.FeedbackDetailModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.grs.common.model.impl.FeedbackDetailImpl}.
 * </p>
 *
 * @author gulam.vora
 * @see FeedbackDetail
 * @see com.ihg.grs.common.model.impl.FeedbackDetailImpl
 * @see com.ihg.grs.common.model.impl.FeedbackDetailModelImpl
 * @generated
 */
public interface FeedbackDetailModel extends BaseModel<FeedbackDetail> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a feedback detail model instance should use the {@link FeedbackDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this feedback detail.
	 *
	 * @return the primary key of this feedback detail
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this feedback detail.
	 *
	 * @param primaryKey the primary key of this feedback detail
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the p o r t a l_ f e e d b a c k_ d t l_ i d of this feedback detail.
	 *
	 * @return the p o r t a l_ f e e d b a c k_ d t l_ i d of this feedback detail
	 */
	public int getPORTAL_FEEDBACK_DTL_ID();

	/**
	 * Sets the p o r t a l_ f e e d b a c k_ d t l_ i d of this feedback detail.
	 *
	 * @param PORTAL_FEEDBACK_DTL_ID the p o r t a l_ f e e d b a c k_ d t l_ i d of this feedback detail
	 */
	public void setPORTAL_FEEDBACK_DTL_ID(int PORTAL_FEEDBACK_DTL_ID);

	/**
	 * Returns the feedback ID of this feedback detail.
	 *
	 * @return the feedback ID of this feedback detail
	 */
	public int getFeedbackId();

	/**
	 * Sets the feedback ID of this feedback detail.
	 *
	 * @param feedbackId the feedback ID of this feedback detail
	 */
	public void setFeedbackId(int feedbackId);

	/**
	 * Returns the feedback type of this feedback detail.
	 *
	 * @return the feedback type of this feedback detail
	 */
	@AutoEscape
	public String getFeedbackType();

	/**
	 * Sets the feedback type of this feedback detail.
	 *
	 * @param feedbackType the feedback type of this feedback detail
	 */
	public void setFeedbackType(String feedbackType);

	/**
	 * Returns the subject of this feedback detail.
	 *
	 * @return the subject of this feedback detail
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this feedback detail.
	 *
	 * @param subject the subject of this feedback detail
	 */
	public void setSubject(String subject);

	/**
	 * Returns the message of this feedback detail.
	 *
	 * @return the message of this feedback detail
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this feedback detail.
	 *
	 * @param message the message of this feedback detail
	 */
	public void setMessage(String message);

	/**
	 * Returns the file name of this feedback detail.
	 *
	 * @return the file name of this feedback detail
	 */
	@AutoEscape
	public String getFileName();

	/**
	 * Sets the file name of this feedback detail.
	 *
	 * @param fileName the file name of this feedback detail
	 */
	public void setFileName(String fileName);

	/**
	 * Returns the file content of this feedback detail.
	 *
	 * @return the file content of this feedback detail
	 */
	public Blob getFileContent();

	/**
	 * Sets the file content of this feedback detail.
	 *
	 * @param fileContent the file content of this feedback detail
	 */
	public void setFileContent(Blob fileContent);

	/**
	 * Returns the create user ID of this feedback detail.
	 *
	 * @return the create user ID of this feedback detail
	 */
	@AutoEscape
	public String getCreateUserId();

	/**
	 * Sets the create user ID of this feedback detail.
	 *
	 * @param createUserId the create user ID of this feedback detail
	 */
	public void setCreateUserId(String createUserId);

	/**
	 * Returns the createdate of this feedback detail.
	 *
	 * @return the createdate of this feedback detail
	 */
	public Date getCreatedate();

	/**
	 * Sets the createdate of this feedback detail.
	 *
	 * @param createdate the createdate of this feedback detail
	 */
	public void setCreatedate(Date createdate);

	/**
	 * Returns the last update user ID of this feedback detail.
	 *
	 * @return the last update user ID of this feedback detail
	 */
	@AutoEscape
	public String getLastUpdateUserId();

	/**
	 * Sets the last update user ID of this feedback detail.
	 *
	 * @param lastUpdateUserId the last update user ID of this feedback detail
	 */
	public void setLastUpdateUserId(String lastUpdateUserId);

	/**
	 * Returns the updatedate of this feedback detail.
	 *
	 * @return the updatedate of this feedback detail
	 */
	public Date getUpdatedate();

	/**
	 * Sets the updatedate of this feedback detail.
	 *
	 * @param updatedate the updatedate of this feedback detail
	 */
	public void setUpdatedate(Date updatedate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.ihg.grs.common.model.FeedbackDetail feedbackDetail);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.ihg.grs.common.model.FeedbackDetail> toCacheModel();

	@Override
	public com.ihg.grs.common.model.FeedbackDetail toEscapedModel();

	@Override
	public com.ihg.grs.common.model.FeedbackDetail toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}