/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.grs.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Glossary service. Represents a row in the &quot;GRS_COMM.GLOSSARY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.grs.common.model.impl.GlossaryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.grs.common.model.impl.GlossaryImpl}.
 * </p>
 *
 * @author gulam.vora
 * @see Glossary
 * @see com.ihg.grs.common.model.impl.GlossaryImpl
 * @see com.ihg.grs.common.model.impl.GlossaryModelImpl
 * @generated
 */
public interface GlossaryModel extends BaseModel<Glossary> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a glossary model instance should use the {@link Glossary} interface instead.
	 */

	/**
	 * Returns the primary key of this glossary.
	 *
	 * @return the primary key of this glossary
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this glossary.
	 *
	 * @param primaryKey the primary key of this glossary
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the glossary ID of this glossary.
	 *
	 * @return the glossary ID of this glossary
	 */
	public int getGlossaryId();

	/**
	 * Sets the glossary ID of this glossary.
	 *
	 * @param glossaryId the glossary ID of this glossary
	 */
	public void setGlossaryId(int glossaryId);

	/**
	 * Returns the term of this glossary.
	 *
	 * @return the term of this glossary
	 */
	@AutoEscape
	public String getTerm();

	/**
	 * Sets the term of this glossary.
	 *
	 * @param term the term of this glossary
	 */
	public void setTerm(String term);

	/**
	 * Returns the description of this glossary.
	 *
	 * @return the description of this glossary
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this glossary.
	 *
	 * @param description the description of this glossary
	 */
	public void setDescription(String description);

	/**
	 * Returns the active indicator of this glossary.
	 *
	 * @return the active indicator of this glossary
	 */
	@AutoEscape
	public String getActiveIndicator();

	/**
	 * Sets the active indicator of this glossary.
	 *
	 * @param activeIndicator the active indicator of this glossary
	 */
	public void setActiveIndicator(String activeIndicator);

	/**
	 * Returns the create user ID of this glossary.
	 *
	 * @return the create user ID of this glossary
	 */
	@AutoEscape
	public String getCreateUserId();

	/**
	 * Sets the create user ID of this glossary.
	 *
	 * @param createUserId the create user ID of this glossary
	 */
	public void setCreateUserId(String createUserId);

	/**
	 * Returns the createdate of this glossary.
	 *
	 * @return the createdate of this glossary
	 */
	public Date getCreatedate();

	/**
	 * Sets the createdate of this glossary.
	 *
	 * @param createdate the createdate of this glossary
	 */
	public void setCreatedate(Date createdate);

	/**
	 * Returns the last update user ID of this glossary.
	 *
	 * @return the last update user ID of this glossary
	 */
	@AutoEscape
	public String getLastUpdateUserId();

	/**
	 * Sets the last update user ID of this glossary.
	 *
	 * @param lastUpdateUserId the last update user ID of this glossary
	 */
	public void setLastUpdateUserId(String lastUpdateUserId);

	/**
	 * Returns the updatedate of this glossary.
	 *
	 * @return the updatedate of this glossary
	 */
	public Date getUpdatedate();

	/**
	 * Sets the updatedate of this glossary.
	 *
	 * @param updatedate the updatedate of this glossary
	 */
	public void setUpdatedate(Date updatedate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.ihg.grs.common.model.Glossary glossary);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.ihg.grs.common.model.Glossary> toCacheModel();

	@Override
	public com.ihg.grs.common.model.Glossary toEscapedModel();

	@Override
	public com.ihg.grs.common.model.Glossary toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}