/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UIElement service. Represents a row in the &quot;UI_ELEM&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.UIElementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.UIElementImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see UIElement
 * @see com.ihg.brandstandards.db.model.impl.UIElementImpl
 * @see com.ihg.brandstandards.db.model.impl.UIElementModelImpl
 * @generated
 */
public interface UIElementModel extends BaseModel<UIElement> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a u i element model instance should use the {@link UIElement} interface instead.
	 */

	/**
	 * Returns the primary key of this u i element.
	 *
	 * @return the primary key of this u i element
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this u i element.
	 *
	 * @param primaryKey the primary key of this u i element
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the element ID of this u i element.
	 *
	 * @return the element ID of this u i element
	 */
	public long getElementId();

	/**
	 * Sets the element ID of this u i element.
	 *
	 * @param elementId the element ID of this u i element
	 */
	public void setElementId(long elementId);

	/**
	 * Returns the element key of this u i element.
	 *
	 * @return the element key of this u i element
	 */
	@AutoEscape
	public String getElementKey();

	/**
	 * Sets the element key of this u i element.
	 *
	 * @param elementKey the element key of this u i element
	 */
	public void setElementKey(String elementKey);

	/**
	 * Returns the module name of this u i element.
	 *
	 * @return the module name of this u i element
	 */
	@AutoEscape
	public String getModuleName();

	/**
	 * Sets the module name of this u i element.
	 *
	 * @param moduleName the module name of this u i element
	 */
	public void setModuleName(String moduleName);

	/**
	 * Returns the creator ID of this u i element.
	 *
	 * @return the creator ID of this u i element
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this u i element.
	 *
	 * @param creatorId the creator ID of this u i element
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this u i element.
	 *
	 * @return the created date of this u i element
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this u i element.
	 *
	 * @param createdDate the created date of this u i element
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this u i element.
	 *
	 * @return the updated by of this u i element
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this u i element.
	 *
	 * @param updatedBy the updated by of this u i element
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this u i element.
	 *
	 * @return the updated date of this u i element
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this u i element.
	 *
	 * @param updatedDate the updated date of this u i element
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UIElement uiElement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UIElement> toCacheModel();

	@Override
	public UIElement toEscapedModel();

	@Override
	public UIElement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}