/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.CountryStandards;
import com.ihg.brandstandards.db.model.CountryStandardsModel;
import com.ihg.brandstandards.db.service.persistence.CountryStandardsPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CountryStandards service. Represents a row in the &quot;CTRY_STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.CountryStandardsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CountryStandardsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see CountryStandardsImpl
 * @see com.ihg.brandstandards.db.model.CountryStandards
 * @see com.ihg.brandstandards.db.model.CountryStandardsModel
 * @generated
 */
public class CountryStandardsModelImpl extends BaseModelImpl<CountryStandards>
	implements CountryStandardsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a country standards model instance should use the {@link com.ihg.brandstandards.db.model.CountryStandards} interface instead.
	 */
	public static final String TABLE_NAME = "CTRY_STD";
	public static final Object[][] TABLE_COLUMNS = {
			{ "CTRY_NM_CD", Types.VARCHAR },
			{ "STD_ID", Types.BIGINT },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table CTRY_STD (CTRY_NM_CD VARCHAR(75) not null,STD_ID LONG not null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null,primary key (CTRY_NM_CD, STD_ID))";
	public static final String TABLE_SQL_DROP = "drop table CTRY_STD";
	public static final String ORDER_BY_JPQL = " ORDER BY countryStandards.id.country ASC, countryStandards.id.stdId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CTRY_STD.CTRY_NM_CD ASC, CTRY_STD.STD_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.CountryStandards"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.CountryStandards"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.CountryStandards"),
			true);
	public static long STDID_COLUMN_BITMASK = 1L;
	public static long COUNTRY_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.CountryStandards"));

	public CountryStandardsModelImpl() {
	}

	@Override
	public CountryStandardsPK getPrimaryKey() {
		return new CountryStandardsPK(_country, _stdId);
	}

	@Override
	public void setPrimaryKey(CountryStandardsPK primaryKey) {
		setCountry(primaryKey.country);
		setStdId(primaryKey.stdId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new CountryStandardsPK(_country, _stdId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((CountryStandardsPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return CountryStandards.class;
	}

	@Override
	public String getModelClassName() {
		return CountryStandards.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("country", getCountry());
		attributes.put("stdId", getStdId());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String country = (String)attributes.get("country");

		if (country != null) {
			setCountry(country);
		}

		Long stdId = (Long)attributes.get("stdId");

		if (stdId != null) {
			setStdId(stdId);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public String getCountry() {
		if (_country == null) {
			return StringPool.BLANK;
		}
		else {
			return _country;
		}
	}

	@Override
	public void setCountry(String country) {
		_country = country;
	}

	@Override
	public long getStdId() {
		return _stdId;
	}

	@Override
	public void setStdId(long stdId) {
		_columnBitmask |= STDID_COLUMN_BITMASK;

		if (!_setOriginalStdId) {
			_setOriginalStdId = true;

			_originalStdId = _stdId;
		}

		_stdId = stdId;
	}

	public long getOriginalStdId() {
		return _originalStdId;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public CountryStandards toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CountryStandards)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CountryStandardsImpl countryStandardsImpl = new CountryStandardsImpl();

		countryStandardsImpl.setCountry(getCountry());
		countryStandardsImpl.setStdId(getStdId());
		countryStandardsImpl.setCreatorId(getCreatorId());
		countryStandardsImpl.setCreatedDate(getCreatedDate());
		countryStandardsImpl.setUpdatedBy(getUpdatedBy());
		countryStandardsImpl.setUpdatedDate(getUpdatedDate());

		countryStandardsImpl.resetOriginalValues();

		return countryStandardsImpl;
	}

	@Override
	public int compareTo(CountryStandards countryStandards) {
		CountryStandardsPK primaryKey = countryStandards.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CountryStandards)) {
			return false;
		}

		CountryStandards countryStandards = (CountryStandards)obj;

		CountryStandardsPK primaryKey = countryStandards.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		CountryStandardsModelImpl countryStandardsModelImpl = this;

		countryStandardsModelImpl._originalStdId = countryStandardsModelImpl._stdId;

		countryStandardsModelImpl._setOriginalStdId = false;

		countryStandardsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CountryStandards> toCacheModel() {
		CountryStandardsCacheModel countryStandardsCacheModel = new CountryStandardsCacheModel();

		countryStandardsCacheModel.country = getCountry();

		String country = countryStandardsCacheModel.country;

		if ((country != null) && (country.length() == 0)) {
			countryStandardsCacheModel.country = null;
		}

		countryStandardsCacheModel.stdId = getStdId();

		countryStandardsCacheModel.creatorId = getCreatorId();

		String creatorId = countryStandardsCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			countryStandardsCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			countryStandardsCacheModel.createdDate = createdDate.getTime();
		}
		else {
			countryStandardsCacheModel.createdDate = Long.MIN_VALUE;
		}

		countryStandardsCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = countryStandardsCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			countryStandardsCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			countryStandardsCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			countryStandardsCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return countryStandardsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{country=");
		sb.append(getCountry());
		sb.append(", stdId=");
		sb.append(getStdId());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.CountryStandards");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>country</column-name><column-value><![CDATA[");
		sb.append(getCountry());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stdId</column-name><column-value><![CDATA[");
		sb.append(getStdId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CountryStandards.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CountryStandards.class
		};
	private String _country;
	private long _stdId;
	private long _originalStdId;
	private boolean _setOriginalStdId;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private CountryStandards _escapedModel;
}