/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.GEMManagementId;
import com.ihg.brandstandards.db.model.GEMManagementIdModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the GEMManagementId service. Represents a row in the &quot;GEM_MGT_ID&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.GEMManagementIdModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GEMManagementIdImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMManagementIdImpl
 * @see com.ihg.brandstandards.db.model.GEMManagementId
 * @see com.ihg.brandstandards.db.model.GEMManagementIdModel
 * @generated
 */
public class GEMManagementIdModelImpl extends BaseModelImpl<GEMManagementId>
	implements GEMManagementIdModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a g e m management ID model instance should use the {@link com.ihg.brandstandards.db.model.GEMManagementId} interface instead.
	 */
	public static final String TABLE_NAME = "GEM_MGT_ID";
	public static final Object[][] TABLE_COLUMNS = {
			{ "GEM_MGT_ID_KEY", Types.BIGINT },
			{ "BRAND_CD", Types.VARCHAR },
			{ "CTRY_NM_CD", Types.VARCHAR },
			{ "GEM_MGT_ID", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table GEM_MGT_ID (GEM_MGT_ID_KEY LONG not null primary key,BRAND_CD VARCHAR(75) null,CTRY_NM_CD VARCHAR(75) null,GEM_MGT_ID VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table GEM_MGT_ID";
	public static final String ORDER_BY_JPQL = " ORDER BY gemManagementId.createdDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GEM_MGT_ID.CREAT_TS ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.GEMManagementId"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.GEMManagementId"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.GEMManagementId"),
			true);
	public static long CHAINCODE_COLUMN_BITMASK = 1L;
	public static long COUNTRYCODE_COLUMN_BITMASK = 2L;
	public static long CREATEDDATE_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.GEMManagementId"));

	public GEMManagementIdModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _managementId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setManagementId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _managementId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GEMManagementId.class;
	}

	@Override
	public String getModelClassName() {
		return GEMManagementId.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("managementId", getManagementId());
		attributes.put("chainCode", getChainCode());
		attributes.put("countryCode", getCountryCode());
		attributes.put("value", getValue());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long managementId = (Long)attributes.get("managementId");

		if (managementId != null) {
			setManagementId(managementId);
		}

		String chainCode = (String)attributes.get("chainCode");

		if (chainCode != null) {
			setChainCode(chainCode);
		}

		String countryCode = (String)attributes.get("countryCode");

		if (countryCode != null) {
			setCountryCode(countryCode);
		}

		String value = (String)attributes.get("value");

		if (value != null) {
			setValue(value);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getManagementId() {
		return _managementId;
	}

	@Override
	public void setManagementId(long managementId) {
		_managementId = managementId;
	}

	@Override
	public String getChainCode() {
		if (_chainCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _chainCode;
		}
	}

	@Override
	public void setChainCode(String chainCode) {
		_columnBitmask |= CHAINCODE_COLUMN_BITMASK;

		if (_originalChainCode == null) {
			_originalChainCode = _chainCode;
		}

		_chainCode = chainCode;
	}

	public String getOriginalChainCode() {
		return GetterUtil.getString(_originalChainCode);
	}

	@Override
	public String getCountryCode() {
		if (_countryCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _countryCode;
		}
	}

	@Override
	public void setCountryCode(String countryCode) {
		_columnBitmask |= COUNTRYCODE_COLUMN_BITMASK;

		if (_originalCountryCode == null) {
			_originalCountryCode = _countryCode;
		}

		_countryCode = countryCode;
	}

	public String getOriginalCountryCode() {
		return GetterUtil.getString(_originalCountryCode);
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return StringPool.BLANK;
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		_value = value;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_columnBitmask = -1L;

		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			GEMManagementId.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GEMManagementId toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (GEMManagementId)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GEMManagementIdImpl gemManagementIdImpl = new GEMManagementIdImpl();

		gemManagementIdImpl.setManagementId(getManagementId());
		gemManagementIdImpl.setChainCode(getChainCode());
		gemManagementIdImpl.setCountryCode(getCountryCode());
		gemManagementIdImpl.setValue(getValue());
		gemManagementIdImpl.setCreatorId(getCreatorId());
		gemManagementIdImpl.setCreatedDate(getCreatedDate());
		gemManagementIdImpl.setUpdatedBy(getUpdatedBy());
		gemManagementIdImpl.setUpdatedDate(getUpdatedDate());

		gemManagementIdImpl.resetOriginalValues();

		return gemManagementIdImpl;
	}

	@Override
	public int compareTo(GEMManagementId gemManagementId) {
		int value = 0;

		value = DateUtil.compareTo(getCreatedDate(),
				gemManagementId.getCreatedDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GEMManagementId)) {
			return false;
		}

		GEMManagementId gemManagementId = (GEMManagementId)obj;

		long primaryKey = gemManagementId.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		GEMManagementIdModelImpl gemManagementIdModelImpl = this;

		gemManagementIdModelImpl._originalChainCode = gemManagementIdModelImpl._chainCode;

		gemManagementIdModelImpl._originalCountryCode = gemManagementIdModelImpl._countryCode;

		gemManagementIdModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GEMManagementId> toCacheModel() {
		GEMManagementIdCacheModel gemManagementIdCacheModel = new GEMManagementIdCacheModel();

		gemManagementIdCacheModel.managementId = getManagementId();

		gemManagementIdCacheModel.chainCode = getChainCode();

		String chainCode = gemManagementIdCacheModel.chainCode;

		if ((chainCode != null) && (chainCode.length() == 0)) {
			gemManagementIdCacheModel.chainCode = null;
		}

		gemManagementIdCacheModel.countryCode = getCountryCode();

		String countryCode = gemManagementIdCacheModel.countryCode;

		if ((countryCode != null) && (countryCode.length() == 0)) {
			gemManagementIdCacheModel.countryCode = null;
		}

		gemManagementIdCacheModel.value = getValue();

		String value = gemManagementIdCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			gemManagementIdCacheModel.value = null;
		}

		gemManagementIdCacheModel.creatorId = getCreatorId();

		String creatorId = gemManagementIdCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			gemManagementIdCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			gemManagementIdCacheModel.createdDate = createdDate.getTime();
		}
		else {
			gemManagementIdCacheModel.createdDate = Long.MIN_VALUE;
		}

		gemManagementIdCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = gemManagementIdCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			gemManagementIdCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			gemManagementIdCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			gemManagementIdCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return gemManagementIdCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{managementId=");
		sb.append(getManagementId());
		sb.append(", chainCode=");
		sb.append(getChainCode());
		sb.append(", countryCode=");
		sb.append(getCountryCode());
		sb.append(", value=");
		sb.append(getValue());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.GEMManagementId");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>managementId</column-name><column-value><![CDATA[");
		sb.append(getManagementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chainCode</column-name><column-value><![CDATA[");
		sb.append(getChainCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>countryCode</column-name><column-value><![CDATA[");
		sb.append(getCountryCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>value</column-name><column-value><![CDATA[");
		sb.append(getValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = GEMManagementId.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			GEMManagementId.class
		};
	private long _managementId;
	private String _chainCode;
	private String _originalChainCode;
	private String _countryCode;
	private String _originalCountryCode;
	private String _value;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private GEMManagementId _escapedModel;
}