/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.HistManuals;
import com.ihg.brandstandards.db.model.HistManualsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the HistManuals service. Represents a row in the &quot;HIST_MNL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.HistManualsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link HistManualsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see HistManualsImpl
 * @see com.ihg.brandstandards.db.model.HistManuals
 * @see com.ihg.brandstandards.db.model.HistManualsModel
 * @generated
 */
public class HistManualsModelImpl extends BaseModelImpl<HistManuals>
	implements HistManualsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a hist manuals model instance should use the {@link com.ihg.brandstandards.db.model.HistManuals} interface instead.
	 */
	public static final String TABLE_NAME = "HIST_MNL";
	public static final Object[][] TABLE_COLUMNS = {
			{ "HST_MNL_ID", Types.BIGINT },
			{ "MNL_TITLE", Types.VARCHAR },
			{ "MNL_TYP", Types.VARCHAR },
			{ "PUBLISH_DT", Types.TIMESTAMP },
			{ "STAT_DESC", Types.VARCHAR },
			{ "CREATE_BY", Types.VARCHAR },
			{ "CREATE_DATE", Types.TIMESTAMP },
			{ "LAST_UPD_BY", Types.VARCHAR },
			{ "LAST_UPD_DATE", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table HIST_MNL (HST_MNL_ID LONG not null primary key,MNL_TITLE VARCHAR(75) null,MNL_TYP VARCHAR(75) null,PUBLISH_DT DATE null,STAT_DESC VARCHAR(75) null,CREATE_BY VARCHAR(75) null,CREATE_DATE DATE null,LAST_UPD_BY VARCHAR(75) null,LAST_UPD_DATE DATE null)";
	public static final String TABLE_SQL_DROP = "drop table HIST_MNL";
	public static final String ORDER_BY_JPQL = " ORDER BY histManuals.histManualId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY HIST_MNL.HST_MNL_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.HistManuals"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.HistManuals"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.HistManuals"));

	public HistManualsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _histManualId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setHistManualId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _histManualId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return HistManuals.class;
	}

	@Override
	public String getModelClassName() {
		return HistManuals.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("histManualId", getHistManualId());
		attributes.put("title", getTitle());
		attributes.put("type", getType());
		attributes.put("pubDate", getPubDate());
		attributes.put("status", getStatus());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long histManualId = (Long)attributes.get("histManualId");

		if (histManualId != null) {
			setHistManualId(histManualId);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String type = (String)attributes.get("type");

		if (type != null) {
			setType(type);
		}

		Date pubDate = (Date)attributes.get("pubDate");

		if (pubDate != null) {
			setPubDate(pubDate);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getHistManualId() {
		return _histManualId;
	}

	@Override
	public void setHistManualId(long histManualId) {
		_histManualId = histManualId;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getType() {
		if (_type == null) {
			return StringPool.BLANK;
		}
		else {
			return _type;
		}
	}

	@Override
	public void setType(String type) {
		_type = type;
	}

	@Override
	public Date getPubDate() {
		return _pubDate;
	}

	@Override
	public void setPubDate(Date pubDate) {
		_pubDate = pubDate;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			HistManuals.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public HistManuals toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (HistManuals)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		HistManualsImpl histManualsImpl = new HistManualsImpl();

		histManualsImpl.setHistManualId(getHistManualId());
		histManualsImpl.setTitle(getTitle());
		histManualsImpl.setType(getType());
		histManualsImpl.setPubDate(getPubDate());
		histManualsImpl.setStatus(getStatus());
		histManualsImpl.setCreatorId(getCreatorId());
		histManualsImpl.setCreatedDate(getCreatedDate());
		histManualsImpl.setUpdatedBy(getUpdatedBy());
		histManualsImpl.setUpdatedDate(getUpdatedDate());

		histManualsImpl.resetOriginalValues();

		return histManualsImpl;
	}

	@Override
	public int compareTo(HistManuals histManuals) {
		long primaryKey = histManuals.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof HistManuals)) {
			return false;
		}

		HistManuals histManuals = (HistManuals)obj;

		long primaryKey = histManuals.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<HistManuals> toCacheModel() {
		HistManualsCacheModel histManualsCacheModel = new HistManualsCacheModel();

		histManualsCacheModel.histManualId = getHistManualId();

		histManualsCacheModel.title = getTitle();

		String title = histManualsCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			histManualsCacheModel.title = null;
		}

		histManualsCacheModel.type = getType();

		String type = histManualsCacheModel.type;

		if ((type != null) && (type.length() == 0)) {
			histManualsCacheModel.type = null;
		}

		Date pubDate = getPubDate();

		if (pubDate != null) {
			histManualsCacheModel.pubDate = pubDate.getTime();
		}
		else {
			histManualsCacheModel.pubDate = Long.MIN_VALUE;
		}

		histManualsCacheModel.status = getStatus();

		String status = histManualsCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			histManualsCacheModel.status = null;
		}

		histManualsCacheModel.creatorId = getCreatorId();

		String creatorId = histManualsCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			histManualsCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			histManualsCacheModel.createdDate = createdDate.getTime();
		}
		else {
			histManualsCacheModel.createdDate = Long.MIN_VALUE;
		}

		histManualsCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = histManualsCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			histManualsCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			histManualsCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			histManualsCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return histManualsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{histManualId=");
		sb.append(getHistManualId());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", type=");
		sb.append(getType());
		sb.append(", pubDate=");
		sb.append(getPubDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.HistManuals");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>histManualId</column-name><column-value><![CDATA[");
		sb.append(getHistManualId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>type</column-name><column-value><![CDATA[");
		sb.append(getType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pubDate</column-name><column-value><![CDATA[");
		sb.append(getPubDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = HistManuals.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			HistManuals.class
		};
	private long _histManualId;
	private String _title;
	private String _type;
	private Date _pubDate;
	private String _status;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private HistManuals _escapedModel;
}