/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.Standards;
import com.ihg.brandstandards.db.model.StandardsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Standards service. Represents a row in the &quot;STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.StandardsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StandardsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsImpl
 * @see com.ihg.brandstandards.db.model.Standards
 * @see com.ihg.brandstandards.db.model.StandardsModel
 * @generated
 */
public class StandardsModelImpl extends BaseModelImpl<Standards>
	implements StandardsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a standards model instance should use the {@link com.ihg.brandstandards.db.model.Standards} interface instead.
	 */
	public static final String TABLE_NAME = "STD";
	public static final Object[][] TABLE_COLUMNS = {
			{ "STD_ID", Types.BIGINT },
			{ "PRNT_STD_ID", Types.BIGINT },
			{ "STD_TYP", Types.VARCHAR },
			{ "TITLE_TXT", Types.VARCHAR },
			{ "STD_DESC", Types.VARCHAR },
			{ "AUTHOR_NM_TXT", Types.VARCHAR },
			{ "BUS_OWNER_NM", Types.VARCHAR },
			{ "EFF_DT", Types.TIMESTAMP },
			{ "IMPLMNT_DEADLINE_DT", Types.TIMESTAMP },
			{ "WAIVER_IND", Types.VARCHAR },
			{ "STAT_DESC", Types.VARCHAR },
			{ "AREA_CATGY_CD", Types.VARCHAR },
			{ "CREATOR_SCRN_NM", Types.VARCHAR },
			{ "CHNG_DESC", Types.VARCHAR },
			{ "GBL_RGN_IND", Types.VARCHAR },
			{ "RGN_CD", Types.VARCHAR },
			{ "NOTE_TXT", Types.VARCHAR },
			{ "FRAMEWORK_STD_IND", Types.VARCHAR },
			{ "STD_MGR_ID", Types.VARCHAR },
			{ "DISP_ORDER_NBR", Types.BIGINT },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP },
			{ "STAT_ID", Types.BIGINT },
			{ "RGN_ID", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table STD (STD_ID LONG not null primary key,PRNT_STD_ID LONG,STD_TYP VARCHAR(75) null,TITLE_TXT VARCHAR(75) null,STD_DESC VARCHAR(75) null,AUTHOR_NM_TXT VARCHAR(75) null,BUS_OWNER_NM VARCHAR(75) null,EFF_DT DATE null,IMPLMNT_DEADLINE_DT DATE null,WAIVER_IND VARCHAR(75) null,STAT_DESC VARCHAR(75) null,AREA_CATGY_CD VARCHAR(75) null,CREATOR_SCRN_NM VARCHAR(75) null,CHNG_DESC VARCHAR(75) null,GBL_RGN_IND VARCHAR(75) null,RGN_CD VARCHAR(75) null,NOTE_TXT VARCHAR(75) null,FRAMEWORK_STD_IND VARCHAR(75) null,STD_MGR_ID VARCHAR(75) null,DISP_ORDER_NBR LONG,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null,STAT_ID LONG,RGN_ID LONG)";
	public static final String TABLE_SQL_DROP = "drop table STD";
	public static final String ORDER_BY_JPQL = " ORDER BY standards.stdId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY STD.STD_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.Standards"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.Standards"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.Standards"),
			true);
	public static long AUTHOR_COLUMN_BITMASK = 1L;
	public static long BUSINESSOWNER_COLUMN_BITMASK = 2L;
	public static long PARENTID_COLUMN_BITMASK = 4L;
	public static long REGIONCODE_COLUMN_BITMASK = 8L;
	public static long STATUS_COLUMN_BITMASK = 16L;
	public static long STDID_COLUMN_BITMASK = 32L;
	public static long STDTYP_COLUMN_BITMASK = 64L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.Standards"));

	public StandardsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _stdId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setStdId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _stdId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Standards.class;
	}

	@Override
	public String getModelClassName() {
		return Standards.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("stdId", getStdId());
		attributes.put("parentId", getParentId());
		attributes.put("stdTyp", getStdTyp());
		attributes.put("title", getTitle());
		attributes.put("description", getDescription());
		attributes.put("author", getAuthor());
		attributes.put("businessOwner", getBusinessOwner());
		attributes.put("effectiveDate", getEffectiveDate());
		attributes.put("implDate", getImplDate());
		attributes.put("waiver", getWaiver());
		attributes.put("status", getStatus());
		attributes.put("category", getCategory());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("change", getChange());
		attributes.put("isGlobal", getIsGlobal());
		attributes.put("regionCode", getRegionCode());
		attributes.put("notes", getNotes());
		attributes.put("framework", getFramework());
		attributes.put("internalReference", getInternalReference());
		attributes.put("orderNumber", getOrderNumber());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());
		attributes.put("statusId", getStatusId());
		attributes.put("regionId", getRegionId());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long stdId = (Long)attributes.get("stdId");

		if (stdId != null) {
			setStdId(stdId);
		}

		Long parentId = (Long)attributes.get("parentId");

		if (parentId != null) {
			setParentId(parentId);
		}

		String stdTyp = (String)attributes.get("stdTyp");

		if (stdTyp != null) {
			setStdTyp(stdTyp);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String author = (String)attributes.get("author");

		if (author != null) {
			setAuthor(author);
		}

		String businessOwner = (String)attributes.get("businessOwner");

		if (businessOwner != null) {
			setBusinessOwner(businessOwner);
		}

		Date effectiveDate = (Date)attributes.get("effectiveDate");

		if (effectiveDate != null) {
			setEffectiveDate(effectiveDate);
		}

		Date implDate = (Date)attributes.get("implDate");

		if (implDate != null) {
			setImplDate(implDate);
		}

		String waiver = (String)attributes.get("waiver");

		if (waiver != null) {
			setWaiver(waiver);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String category = (String)attributes.get("category");

		if (category != null) {
			setCategory(category);
		}

		String createdBy = (String)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		String change = (String)attributes.get("change");

		if (change != null) {
			setChange(change);
		}

		String isGlobal = (String)attributes.get("isGlobal");

		if (isGlobal != null) {
			setIsGlobal(isGlobal);
		}

		String regionCode = (String)attributes.get("regionCode");

		if (regionCode != null) {
			setRegionCode(regionCode);
		}

		String notes = (String)attributes.get("notes");

		if (notes != null) {
			setNotes(notes);
		}

		String framework = (String)attributes.get("framework");

		if (framework != null) {
			setFramework(framework);
		}

		String internalReference = (String)attributes.get("internalReference");

		if (internalReference != null) {
			setInternalReference(internalReference);
		}

		Long orderNumber = (Long)attributes.get("orderNumber");

		if (orderNumber != null) {
			setOrderNumber(orderNumber);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}

		Long statusId = (Long)attributes.get("statusId");

		if (statusId != null) {
			setStatusId(statusId);
		}

		Long regionId = (Long)attributes.get("regionId");

		if (regionId != null) {
			setRegionId(regionId);
		}
	}

	@Override
	public long getStdId() {
		return _stdId;
	}

	@Override
	public void setStdId(long stdId) {
		_columnBitmask |= STDID_COLUMN_BITMASK;

		if (!_setOriginalStdId) {
			_setOriginalStdId = true;

			_originalStdId = _stdId;
		}

		_stdId = stdId;
	}

	public long getOriginalStdId() {
		return _originalStdId;
	}

	@Override
	public long getParentId() {
		return _parentId;
	}

	@Override
	public void setParentId(long parentId) {
		_columnBitmask |= PARENTID_COLUMN_BITMASK;

		if (!_setOriginalParentId) {
			_setOriginalParentId = true;

			_originalParentId = _parentId;
		}

		_parentId = parentId;
	}

	public long getOriginalParentId() {
		return _originalParentId;
	}

	@Override
	public String getStdTyp() {
		if (_stdTyp == null) {
			return StringPool.BLANK;
		}
		else {
			return _stdTyp;
		}
	}

	@Override
	public void setStdTyp(String stdTyp) {
		_columnBitmask |= STDTYP_COLUMN_BITMASK;

		if (_originalStdTyp == null) {
			_originalStdTyp = _stdTyp;
		}

		_stdTyp = stdTyp;
	}

	public String getOriginalStdTyp() {
		return GetterUtil.getString(_originalStdTyp);
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getAuthor() {
		if (_author == null) {
			return StringPool.BLANK;
		}
		else {
			return _author;
		}
	}

	@Override
	public void setAuthor(String author) {
		_columnBitmask |= AUTHOR_COLUMN_BITMASK;

		if (_originalAuthor == null) {
			_originalAuthor = _author;
		}

		_author = author;
	}

	public String getOriginalAuthor() {
		return GetterUtil.getString(_originalAuthor);
	}

	@Override
	public String getBusinessOwner() {
		if (_businessOwner == null) {
			return StringPool.BLANK;
		}
		else {
			return _businessOwner;
		}
	}

	@Override
	public void setBusinessOwner(String businessOwner) {
		_columnBitmask |= BUSINESSOWNER_COLUMN_BITMASK;

		if (_originalBusinessOwner == null) {
			_originalBusinessOwner = _businessOwner;
		}

		_businessOwner = businessOwner;
	}

	public String getOriginalBusinessOwner() {
		return GetterUtil.getString(_originalBusinessOwner);
	}

	@Override
	public Date getEffectiveDate() {
		return _effectiveDate;
	}

	@Override
	public void setEffectiveDate(Date effectiveDate) {
		_effectiveDate = effectiveDate;
	}

	@Override
	public Date getImplDate() {
		return _implDate;
	}

	@Override
	public void setImplDate(Date implDate) {
		_implDate = implDate;
	}

	@Override
	public String getWaiver() {
		if (_waiver == null) {
			return StringPool.BLANK;
		}
		else {
			return _waiver;
		}
	}

	@Override
	public void setWaiver(String waiver) {
		_waiver = waiver;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (_originalStatus == null) {
			_originalStatus = _status;
		}

		_status = status;
	}

	public String getOriginalStatus() {
		return GetterUtil.getString(_originalStatus);
	}

	@Override
	public String getCategory() {
		if (_category == null) {
			return StringPool.BLANK;
		}
		else {
			return _category;
		}
	}

	@Override
	public void setCategory(String category) {
		_category = category;
	}

	@Override
	public String getCreatedBy() {
		if (_createdBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _createdBy;
		}
	}

	@Override
	public void setCreatedBy(String createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public String getChange() {
		if (_change == null) {
			return StringPool.BLANK;
		}
		else {
			return _change;
		}
	}

	@Override
	public void setChange(String change) {
		_change = change;
	}

	@Override
	public String getIsGlobal() {
		if (_isGlobal == null) {
			return StringPool.BLANK;
		}
		else {
			return _isGlobal;
		}
	}

	@Override
	public void setIsGlobal(String isGlobal) {
		_isGlobal = isGlobal;
	}

	@Override
	public String getRegionCode() {
		if (_regionCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _regionCode;
		}
	}

	@Override
	public void setRegionCode(String regionCode) {
		_columnBitmask |= REGIONCODE_COLUMN_BITMASK;

		if (_originalRegionCode == null) {
			_originalRegionCode = _regionCode;
		}

		_regionCode = regionCode;
	}

	public String getOriginalRegionCode() {
		return GetterUtil.getString(_originalRegionCode);
	}

	@Override
	public String getNotes() {
		if (_notes == null) {
			return StringPool.BLANK;
		}
		else {
			return _notes;
		}
	}

	@Override
	public void setNotes(String notes) {
		_notes = notes;
	}

	@Override
	public String getFramework() {
		if (_framework == null) {
			return StringPool.BLANK;
		}
		else {
			return _framework;
		}
	}

	@Override
	public void setFramework(String framework) {
		_framework = framework;
	}

	@Override
	public String getInternalReference() {
		if (_internalReference == null) {
			return StringPool.BLANK;
		}
		else {
			return _internalReference;
		}
	}

	@Override
	public void setInternalReference(String internalReference) {
		_internalReference = internalReference;
	}

	@Override
	public long getOrderNumber() {
		return _orderNumber;
	}

	@Override
	public void setOrderNumber(long orderNumber) {
		_orderNumber = orderNumber;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@Override
	public long getStatusId() {
		return _statusId;
	}

	@Override
	public void setStatusId(long statusId) {
		_statusId = statusId;
	}

	@Override
	public long getRegionId() {
		return _regionId;
	}

	@Override
	public void setRegionId(long regionId) {
		_regionId = regionId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Standards.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Standards toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Standards)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StandardsImpl standardsImpl = new StandardsImpl();

		standardsImpl.setStdId(getStdId());
		standardsImpl.setParentId(getParentId());
		standardsImpl.setStdTyp(getStdTyp());
		standardsImpl.setTitle(getTitle());
		standardsImpl.setDescription(getDescription());
		standardsImpl.setAuthor(getAuthor());
		standardsImpl.setBusinessOwner(getBusinessOwner());
		standardsImpl.setEffectiveDate(getEffectiveDate());
		standardsImpl.setImplDate(getImplDate());
		standardsImpl.setWaiver(getWaiver());
		standardsImpl.setStatus(getStatus());
		standardsImpl.setCategory(getCategory());
		standardsImpl.setCreatedBy(getCreatedBy());
		standardsImpl.setChange(getChange());
		standardsImpl.setIsGlobal(getIsGlobal());
		standardsImpl.setRegionCode(getRegionCode());
		standardsImpl.setNotes(getNotes());
		standardsImpl.setFramework(getFramework());
		standardsImpl.setInternalReference(getInternalReference());
		standardsImpl.setOrderNumber(getOrderNumber());
		standardsImpl.setCreatorId(getCreatorId());
		standardsImpl.setCreatedDate(getCreatedDate());
		standardsImpl.setUpdatedBy(getUpdatedBy());
		standardsImpl.setUpdatedDate(getUpdatedDate());
		standardsImpl.setStatusId(getStatusId());
		standardsImpl.setRegionId(getRegionId());

		standardsImpl.resetOriginalValues();

		return standardsImpl;
	}

	@Override
	public int compareTo(Standards standards) {
		long primaryKey = standards.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Standards)) {
			return false;
		}

		Standards standards = (Standards)obj;

		long primaryKey = standards.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		StandardsModelImpl standardsModelImpl = this;

		standardsModelImpl._originalStdId = standardsModelImpl._stdId;

		standardsModelImpl._setOriginalStdId = false;

		standardsModelImpl._originalParentId = standardsModelImpl._parentId;

		standardsModelImpl._setOriginalParentId = false;

		standardsModelImpl._originalStdTyp = standardsModelImpl._stdTyp;

		standardsModelImpl._originalAuthor = standardsModelImpl._author;

		standardsModelImpl._originalBusinessOwner = standardsModelImpl._businessOwner;

		standardsModelImpl._originalStatus = standardsModelImpl._status;

		standardsModelImpl._originalRegionCode = standardsModelImpl._regionCode;

		standardsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Standards> toCacheModel() {
		StandardsCacheModel standardsCacheModel = new StandardsCacheModel();

		standardsCacheModel.stdId = getStdId();

		standardsCacheModel.parentId = getParentId();

		standardsCacheModel.stdTyp = getStdTyp();

		String stdTyp = standardsCacheModel.stdTyp;

		if ((stdTyp != null) && (stdTyp.length() == 0)) {
			standardsCacheModel.stdTyp = null;
		}

		standardsCacheModel.title = getTitle();

		String title = standardsCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			standardsCacheModel.title = null;
		}

		standardsCacheModel.description = getDescription();

		String description = standardsCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			standardsCacheModel.description = null;
		}

		standardsCacheModel.author = getAuthor();

		String author = standardsCacheModel.author;

		if ((author != null) && (author.length() == 0)) {
			standardsCacheModel.author = null;
		}

		standardsCacheModel.businessOwner = getBusinessOwner();

		String businessOwner = standardsCacheModel.businessOwner;

		if ((businessOwner != null) && (businessOwner.length() == 0)) {
			standardsCacheModel.businessOwner = null;
		}

		Date effectiveDate = getEffectiveDate();

		if (effectiveDate != null) {
			standardsCacheModel.effectiveDate = effectiveDate.getTime();
		}
		else {
			standardsCacheModel.effectiveDate = Long.MIN_VALUE;
		}

		Date implDate = getImplDate();

		if (implDate != null) {
			standardsCacheModel.implDate = implDate.getTime();
		}
		else {
			standardsCacheModel.implDate = Long.MIN_VALUE;
		}

		standardsCacheModel.waiver = getWaiver();

		String waiver = standardsCacheModel.waiver;

		if ((waiver != null) && (waiver.length() == 0)) {
			standardsCacheModel.waiver = null;
		}

		standardsCacheModel.status = getStatus();

		String status = standardsCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			standardsCacheModel.status = null;
		}

		standardsCacheModel.category = getCategory();

		String category = standardsCacheModel.category;

		if ((category != null) && (category.length() == 0)) {
			standardsCacheModel.category = null;
		}

		standardsCacheModel.createdBy = getCreatedBy();

		String createdBy = standardsCacheModel.createdBy;

		if ((createdBy != null) && (createdBy.length() == 0)) {
			standardsCacheModel.createdBy = null;
		}

		standardsCacheModel.change = getChange();

		String change = standardsCacheModel.change;

		if ((change != null) && (change.length() == 0)) {
			standardsCacheModel.change = null;
		}

		standardsCacheModel.isGlobal = getIsGlobal();

		String isGlobal = standardsCacheModel.isGlobal;

		if ((isGlobal != null) && (isGlobal.length() == 0)) {
			standardsCacheModel.isGlobal = null;
		}

		standardsCacheModel.regionCode = getRegionCode();

		String regionCode = standardsCacheModel.regionCode;

		if ((regionCode != null) && (regionCode.length() == 0)) {
			standardsCacheModel.regionCode = null;
		}

		standardsCacheModel.notes = getNotes();

		String notes = standardsCacheModel.notes;

		if ((notes != null) && (notes.length() == 0)) {
			standardsCacheModel.notes = null;
		}

		standardsCacheModel.framework = getFramework();

		String framework = standardsCacheModel.framework;

		if ((framework != null) && (framework.length() == 0)) {
			standardsCacheModel.framework = null;
		}

		standardsCacheModel.internalReference = getInternalReference();

		String internalReference = standardsCacheModel.internalReference;

		if ((internalReference != null) && (internalReference.length() == 0)) {
			standardsCacheModel.internalReference = null;
		}

		standardsCacheModel.orderNumber = getOrderNumber();

		standardsCacheModel.creatorId = getCreatorId();

		String creatorId = standardsCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			standardsCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			standardsCacheModel.createdDate = createdDate.getTime();
		}
		else {
			standardsCacheModel.createdDate = Long.MIN_VALUE;
		}

		standardsCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = standardsCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			standardsCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			standardsCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			standardsCacheModel.updatedDate = Long.MIN_VALUE;
		}

		standardsCacheModel.statusId = getStatusId();

		standardsCacheModel.regionId = getRegionId();

		return standardsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(53);

		sb.append("{stdId=");
		sb.append(getStdId());
		sb.append(", parentId=");
		sb.append(getParentId());
		sb.append(", stdTyp=");
		sb.append(getStdTyp());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", author=");
		sb.append(getAuthor());
		sb.append(", businessOwner=");
		sb.append(getBusinessOwner());
		sb.append(", effectiveDate=");
		sb.append(getEffectiveDate());
		sb.append(", implDate=");
		sb.append(getImplDate());
		sb.append(", waiver=");
		sb.append(getWaiver());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", category=");
		sb.append(getCategory());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", change=");
		sb.append(getChange());
		sb.append(", isGlobal=");
		sb.append(getIsGlobal());
		sb.append(", regionCode=");
		sb.append(getRegionCode());
		sb.append(", notes=");
		sb.append(getNotes());
		sb.append(", framework=");
		sb.append(getFramework());
		sb.append(", internalReference=");
		sb.append(getInternalReference());
		sb.append(", orderNumber=");
		sb.append(getOrderNumber());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append(", statusId=");
		sb.append(getStatusId());
		sb.append(", regionId=");
		sb.append(getRegionId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(82);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.Standards");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>stdId</column-name><column-value><![CDATA[");
		sb.append(getStdId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>parentId</column-name><column-value><![CDATA[");
		sb.append(getParentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stdTyp</column-name><column-value><![CDATA[");
		sb.append(getStdTyp());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>author</column-name><column-value><![CDATA[");
		sb.append(getAuthor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>businessOwner</column-name><column-value><![CDATA[");
		sb.append(getBusinessOwner());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>effectiveDate</column-name><column-value><![CDATA[");
		sb.append(getEffectiveDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>implDate</column-name><column-value><![CDATA[");
		sb.append(getImplDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>waiver</column-name><column-value><![CDATA[");
		sb.append(getWaiver());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>category</column-name><column-value><![CDATA[");
		sb.append(getCategory());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>change</column-name><column-value><![CDATA[");
		sb.append(getChange());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>isGlobal</column-name><column-value><![CDATA[");
		sb.append(getIsGlobal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>regionCode</column-name><column-value><![CDATA[");
		sb.append(getRegionCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>notes</column-name><column-value><![CDATA[");
		sb.append(getNotes());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>framework</column-name><column-value><![CDATA[");
		sb.append(getFramework());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>internalReference</column-name><column-value><![CDATA[");
		sb.append(getInternalReference());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>orderNumber</column-name><column-value><![CDATA[");
		sb.append(getOrderNumber());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>statusId</column-name><column-value><![CDATA[");
		sb.append(getStatusId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>regionId</column-name><column-value><![CDATA[");
		sb.append(getRegionId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Standards.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			Standards.class
		};
	private long _stdId;
	private long _originalStdId;
	private boolean _setOriginalStdId;
	private long _parentId;
	private long _originalParentId;
	private boolean _setOriginalParentId;
	private String _stdTyp;
	private String _originalStdTyp;
	private String _title;
	private String _description;
	private String _author;
	private String _originalAuthor;
	private String _businessOwner;
	private String _originalBusinessOwner;
	private Date _effectiveDate;
	private Date _implDate;
	private String _waiver;
	private String _status;
	private String _originalStatus;
	private String _category;
	private String _createdBy;
	private String _change;
	private String _isGlobal;
	private String _regionCode;
	private String _originalRegionCode;
	private String _notes;
	private String _framework;
	private String _internalReference;
	private long _orderNumber;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _statusId;
	private long _regionId;
	private long _columnBitmask;
	private Standards _escapedModel;
}