/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.UIElementTranslate;
import com.ihg.brandstandards.db.model.UIElementTranslateModel;
import com.ihg.brandstandards.db.service.persistence.UIElementTranslatePK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the UIElementTranslate service. Represents a row in the &quot;UI_ELEM_XLAT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.UIElementTranslateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UIElementTranslateImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see UIElementTranslateImpl
 * @see com.ihg.brandstandards.db.model.UIElementTranslate
 * @see com.ihg.brandstandards.db.model.UIElementTranslateModel
 * @generated
 */
public class UIElementTranslateModelImpl extends BaseModelImpl<UIElementTranslate>
	implements UIElementTranslateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a u i element translate model instance should use the {@link com.ihg.brandstandards.db.model.UIElementTranslate} interface instead.
	 */
	public static final String TABLE_NAME = "UI_ELEM_XLAT";
	public static final Object[][] TABLE_COLUMNS = {
			{ "UI_ELEM_ID", Types.BIGINT },
			{ "LOCALE_CD", Types.VARCHAR },
			{ "ELEM_VAL", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table UI_ELEM_XLAT (UI_ELEM_ID LONG not null,LOCALE_CD VARCHAR(75) not null,ELEM_VAL VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null,primary key (UI_ELEM_ID, LOCALE_CD))";
	public static final String TABLE_SQL_DROP = "drop table UI_ELEM_XLAT";
	public static final String ORDER_BY_JPQL = " ORDER BY uiElementTranslate.id.elementId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY UI_ELEM_XLAT.UI_ELEM_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.UIElementTranslate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.UIElementTranslate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.UIElementTranslate"),
			true);
	public static long ELEMENTID_COLUMN_BITMASK = 1L;
	public static long LOCALECODE_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.UIElementTranslate"));

	public UIElementTranslateModelImpl() {
	}

	@Override
	public UIElementTranslatePK getPrimaryKey() {
		return new UIElementTranslatePK(_elementId, _localeCode);
	}

	@Override
	public void setPrimaryKey(UIElementTranslatePK primaryKey) {
		setElementId(primaryKey.elementId);
		setLocaleCode(primaryKey.localeCode);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new UIElementTranslatePK(_elementId, _localeCode);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((UIElementTranslatePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return UIElementTranslate.class;
	}

	@Override
	public String getModelClassName() {
		return UIElementTranslate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("elementId", getElementId());
		attributes.put("localeCode", getLocaleCode());
		attributes.put("elementValue", getElementValue());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long elementId = (Long)attributes.get("elementId");

		if (elementId != null) {
			setElementId(elementId);
		}

		String localeCode = (String)attributes.get("localeCode");

		if (localeCode != null) {
			setLocaleCode(localeCode);
		}

		String elementValue = (String)attributes.get("elementValue");

		if (elementValue != null) {
			setElementValue(elementValue);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getElementId() {
		return _elementId;
	}

	@Override
	public void setElementId(long elementId) {
		_columnBitmask = -1L;

		if (!_setOriginalElementId) {
			_setOriginalElementId = true;

			_originalElementId = _elementId;
		}

		_elementId = elementId;
	}

	public long getOriginalElementId() {
		return _originalElementId;
	}

	@Override
	public String getLocaleCode() {
		if (_localeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _localeCode;
		}
	}

	@Override
	public void setLocaleCode(String localeCode) {
		_columnBitmask |= LOCALECODE_COLUMN_BITMASK;

		if (_originalLocaleCode == null) {
			_originalLocaleCode = _localeCode;
		}

		_localeCode = localeCode;
	}

	public String getOriginalLocaleCode() {
		return GetterUtil.getString(_originalLocaleCode);
	}

	@Override
	public String getElementValue() {
		if (_elementValue == null) {
			return StringPool.BLANK;
		}
		else {
			return _elementValue;
		}
	}

	@Override
	public void setElementValue(String elementValue) {
		_elementValue = elementValue;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public UIElementTranslate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UIElementTranslate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UIElementTranslateImpl uiElementTranslateImpl = new UIElementTranslateImpl();

		uiElementTranslateImpl.setElementId(getElementId());
		uiElementTranslateImpl.setLocaleCode(getLocaleCode());
		uiElementTranslateImpl.setElementValue(getElementValue());
		uiElementTranslateImpl.setCreatorId(getCreatorId());
		uiElementTranslateImpl.setCreatedDate(getCreatedDate());
		uiElementTranslateImpl.setUpdatedBy(getUpdatedBy());
		uiElementTranslateImpl.setUpdatedDate(getUpdatedDate());

		uiElementTranslateImpl.resetOriginalValues();

		return uiElementTranslateImpl;
	}

	@Override
	public int compareTo(UIElementTranslate uiElementTranslate) {
		int value = 0;

		if (getElementId() < uiElementTranslate.getElementId()) {
			value = -1;
		}
		else if (getElementId() > uiElementTranslate.getElementId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UIElementTranslate)) {
			return false;
		}

		UIElementTranslate uiElementTranslate = (UIElementTranslate)obj;

		UIElementTranslatePK primaryKey = uiElementTranslate.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
		UIElementTranslateModelImpl uiElementTranslateModelImpl = this;

		uiElementTranslateModelImpl._originalElementId = uiElementTranslateModelImpl._elementId;

		uiElementTranslateModelImpl._setOriginalElementId = false;

		uiElementTranslateModelImpl._originalLocaleCode = uiElementTranslateModelImpl._localeCode;

		uiElementTranslateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<UIElementTranslate> toCacheModel() {
		UIElementTranslateCacheModel uiElementTranslateCacheModel = new UIElementTranslateCacheModel();

		uiElementTranslateCacheModel.elementId = getElementId();

		uiElementTranslateCacheModel.localeCode = getLocaleCode();

		String localeCode = uiElementTranslateCacheModel.localeCode;

		if ((localeCode != null) && (localeCode.length() == 0)) {
			uiElementTranslateCacheModel.localeCode = null;
		}

		uiElementTranslateCacheModel.elementValue = getElementValue();

		String elementValue = uiElementTranslateCacheModel.elementValue;

		if ((elementValue != null) && (elementValue.length() == 0)) {
			uiElementTranslateCacheModel.elementValue = null;
		}

		uiElementTranslateCacheModel.creatorId = getCreatorId();

		String creatorId = uiElementTranslateCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			uiElementTranslateCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			uiElementTranslateCacheModel.createdDate = createdDate.getTime();
		}
		else {
			uiElementTranslateCacheModel.createdDate = Long.MIN_VALUE;
		}

		uiElementTranslateCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = uiElementTranslateCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			uiElementTranslateCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			uiElementTranslateCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			uiElementTranslateCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return uiElementTranslateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{elementId=");
		sb.append(getElementId());
		sb.append(", localeCode=");
		sb.append(getLocaleCode());
		sb.append(", elementValue=");
		sb.append(getElementValue());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.UIElementTranslate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>elementId</column-name><column-value><![CDATA[");
		sb.append(getElementId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>localeCode</column-name><column-value><![CDATA[");
		sb.append(getLocaleCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>elementValue</column-name><column-value><![CDATA[");
		sb.append(getElementValue());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UIElementTranslate.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UIElementTranslate.class
		};
	private long _elementId;
	private long _originalElementId;
	private boolean _setOriginalElementId;
	private String _localeCode;
	private String _originalLocaleCode;
	private String _elementValue;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private UIElementTranslate _escapedModel;
}