/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.GEMTemplate;
import com.ihg.brandstandards.db.model.GEMTemplateModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the GEMTemplate service. Represents a row in the &quot;GEM_TEMPLATE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.GEMTemplateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GEMTemplateImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMTemplateImpl
 * @see com.ihg.brandstandards.db.model.GEMTemplate
 * @see com.ihg.brandstandards.db.model.GEMTemplateModel
 * @generated
 */
public class GEMTemplateModelImpl extends BaseModelImpl<GEMTemplate>
	implements GEMTemplateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a g e m template model instance should use the {@link com.ihg.brandstandards.db.model.GEMTemplate} interface instead.
	 */
	public static final String TABLE_NAME = "GEM_TEMPLATE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "GEM_TEMPLATE_ID", Types.BIGINT },
			{ "TEMPLATE_NM", Types.VARCHAR },
			{ "PUBLISH_ID", Types.BIGINT },
			{ "RGN_ID", Types.BIGINT },
			{ "TEMPLATE_TYP_CD", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table GEM_TEMPLATE (GEM_TEMPLATE_ID LONG not null primary key,TEMPLATE_NM VARCHAR(75) null,PUBLISH_ID LONG,RGN_ID LONG,TEMPLATE_TYP_CD VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table GEM_TEMPLATE";
	public static final String ORDER_BY_JPQL = " ORDER BY gemTemplate.templateId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GEM_TEMPLATE.GEM_TEMPLATE_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.GEMTemplate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.GEMTemplate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.GEMTemplate"),
			true);
	public static long PUBLISHID_COLUMN_BITMASK = 1L;
	public static long REGIONID_COLUMN_BITMASK = 2L;
	public static long TEMPLATETYPE_COLUMN_BITMASK = 4L;
	public static long TEMPLATEID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.GEMTemplate"));

	public GEMTemplateModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _templateId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTemplateId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _templateId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GEMTemplate.class;
	}

	@Override
	public String getModelClassName() {
		return GEMTemplate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("templateId", getTemplateId());
		attributes.put("templateName", getTemplateName());
		attributes.put("publishId", getPublishId());
		attributes.put("regionId", getRegionId());
		attributes.put("templateType", getTemplateType());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long templateId = (Long)attributes.get("templateId");

		if (templateId != null) {
			setTemplateId(templateId);
		}

		String templateName = (String)attributes.get("templateName");

		if (templateName != null) {
			setTemplateName(templateName);
		}

		Long publishId = (Long)attributes.get("publishId");

		if (publishId != null) {
			setPublishId(publishId);
		}

		Long regionId = (Long)attributes.get("regionId");

		if (regionId != null) {
			setRegionId(regionId);
		}

		String templateType = (String)attributes.get("templateType");

		if (templateType != null) {
			setTemplateType(templateType);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getTemplateId() {
		return _templateId;
	}

	@Override
	public void setTemplateId(long templateId) {
		_templateId = templateId;
	}

	@Override
	public String getTemplateName() {
		if (_templateName == null) {
			return StringPool.BLANK;
		}
		else {
			return _templateName;
		}
	}

	@Override
	public void setTemplateName(String templateName) {
		_templateName = templateName;
	}

	@Override
	public long getPublishId() {
		return _publishId;
	}

	@Override
	public void setPublishId(long publishId) {
		_columnBitmask |= PUBLISHID_COLUMN_BITMASK;

		if (!_setOriginalPublishId) {
			_setOriginalPublishId = true;

			_originalPublishId = _publishId;
		}

		_publishId = publishId;
	}

	public long getOriginalPublishId() {
		return _originalPublishId;
	}

	@Override
	public long getRegionId() {
		return _regionId;
	}

	@Override
	public void setRegionId(long regionId) {
		_columnBitmask |= REGIONID_COLUMN_BITMASK;

		if (!_setOriginalRegionId) {
			_setOriginalRegionId = true;

			_originalRegionId = _regionId;
		}

		_regionId = regionId;
	}

	public long getOriginalRegionId() {
		return _originalRegionId;
	}

	@Override
	public String getTemplateType() {
		if (_templateType == null) {
			return StringPool.BLANK;
		}
		else {
			return _templateType;
		}
	}

	@Override
	public void setTemplateType(String templateType) {
		_columnBitmask |= TEMPLATETYPE_COLUMN_BITMASK;

		if (_originalTemplateType == null) {
			_originalTemplateType = _templateType;
		}

		_templateType = templateType;
	}

	public String getOriginalTemplateType() {
		return GetterUtil.getString(_originalTemplateType);
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			GEMTemplate.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GEMTemplate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (GEMTemplate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GEMTemplateImpl gemTemplateImpl = new GEMTemplateImpl();

		gemTemplateImpl.setTemplateId(getTemplateId());
		gemTemplateImpl.setTemplateName(getTemplateName());
		gemTemplateImpl.setPublishId(getPublishId());
		gemTemplateImpl.setRegionId(getRegionId());
		gemTemplateImpl.setTemplateType(getTemplateType());
		gemTemplateImpl.setCreatorId(getCreatorId());
		gemTemplateImpl.setCreatedDate(getCreatedDate());
		gemTemplateImpl.setUpdatedBy(getUpdatedBy());
		gemTemplateImpl.setUpdatedDate(getUpdatedDate());

		gemTemplateImpl.resetOriginalValues();

		return gemTemplateImpl;
	}

	@Override
	public int compareTo(GEMTemplate gemTemplate) {
		long primaryKey = gemTemplate.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GEMTemplate)) {
			return false;
		}

		GEMTemplate gemTemplate = (GEMTemplate)obj;

		long primaryKey = gemTemplate.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		GEMTemplateModelImpl gemTemplateModelImpl = this;

		gemTemplateModelImpl._originalPublishId = gemTemplateModelImpl._publishId;

		gemTemplateModelImpl._setOriginalPublishId = false;

		gemTemplateModelImpl._originalRegionId = gemTemplateModelImpl._regionId;

		gemTemplateModelImpl._setOriginalRegionId = false;

		gemTemplateModelImpl._originalTemplateType = gemTemplateModelImpl._templateType;

		gemTemplateModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GEMTemplate> toCacheModel() {
		GEMTemplateCacheModel gemTemplateCacheModel = new GEMTemplateCacheModel();

		gemTemplateCacheModel.templateId = getTemplateId();

		gemTemplateCacheModel.templateName = getTemplateName();

		String templateName = gemTemplateCacheModel.templateName;

		if ((templateName != null) && (templateName.length() == 0)) {
			gemTemplateCacheModel.templateName = null;
		}

		gemTemplateCacheModel.publishId = getPublishId();

		gemTemplateCacheModel.regionId = getRegionId();

		gemTemplateCacheModel.templateType = getTemplateType();

		String templateType = gemTemplateCacheModel.templateType;

		if ((templateType != null) && (templateType.length() == 0)) {
			gemTemplateCacheModel.templateType = null;
		}

		gemTemplateCacheModel.creatorId = getCreatorId();

		String creatorId = gemTemplateCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			gemTemplateCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			gemTemplateCacheModel.createdDate = createdDate.getTime();
		}
		else {
			gemTemplateCacheModel.createdDate = Long.MIN_VALUE;
		}

		gemTemplateCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = gemTemplateCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			gemTemplateCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			gemTemplateCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			gemTemplateCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return gemTemplateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{templateId=");
		sb.append(getTemplateId());
		sb.append(", templateName=");
		sb.append(getTemplateName());
		sb.append(", publishId=");
		sb.append(getPublishId());
		sb.append(", regionId=");
		sb.append(getRegionId());
		sb.append(", templateType=");
		sb.append(getTemplateType());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.GEMTemplate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>templateId</column-name><column-value><![CDATA[");
		sb.append(getTemplateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>templateName</column-name><column-value><![CDATA[");
		sb.append(getTemplateName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publishId</column-name><column-value><![CDATA[");
		sb.append(getPublishId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>regionId</column-name><column-value><![CDATA[");
		sb.append(getRegionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>templateType</column-name><column-value><![CDATA[");
		sb.append(getTemplateType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = GEMTemplate.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			GEMTemplate.class
		};
	private long _templateId;
	private String _templateName;
	private long _publishId;
	private long _originalPublishId;
	private boolean _setOriginalPublishId;
	private long _regionId;
	private long _originalRegionId;
	private boolean _setOriginalRegionId;
	private String _templateType;
	private String _originalTemplateType;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private GEMTemplate _escapedModel;
}