/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.ihg.brandstandards.db.service.persistence.BridgePublishStateExPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the BridgePublishStateEx service. Represents a row in the &quot;BRIDGE_PUBLISH_STAT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.BridgePublishStateExModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.BridgePublishStateExImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see BridgePublishStateEx
 * @see com.ihg.brandstandards.db.model.impl.BridgePublishStateExImpl
 * @see com.ihg.brandstandards.db.model.impl.BridgePublishStateExModelImpl
 * @generated
 */
public interface BridgePublishStateExModel extends BaseModel<BridgePublishStateEx> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bridge publish state ex model instance should use the {@link BridgePublishStateEx} interface instead.
	 */

	/**
	 * Returns the primary key of this bridge publish state ex.
	 *
	 * @return the primary key of this bridge publish state ex
	 */
	public BridgePublishStateExPK getPrimaryKey();

	/**
	 * Sets the primary key of this bridge publish state ex.
	 *
	 * @param primaryKey the primary key of this bridge publish state ex
	 */
	public void setPrimaryKey(BridgePublishStateExPK primaryKey);

	/**
	 * Returns the publish ID of this bridge publish state ex.
	 *
	 * @return the publish ID of this bridge publish state ex
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this bridge publish state ex.
	 *
	 * @param publishId the publish ID of this bridge publish state ex
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the std ID of this bridge publish state ex.
	 *
	 * @return the std ID of this bridge publish state ex
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this bridge publish state ex.
	 *
	 * @param stdId the std ID of this bridge publish state ex
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the taxonomy title of this bridge publish state ex.
	 *
	 * @return the taxonomy title of this bridge publish state ex
	 */
	@AutoEscape
	public String getTaxonomyTitle();

	/**
	 * Sets the taxonomy title of this bridge publish state ex.
	 *
	 * @param taxonomyTitle the taxonomy title of this bridge publish state ex
	 */
	public void setTaxonomyTitle(String taxonomyTitle);

	/**
	 * Returns the title of this bridge publish state ex.
	 *
	 * @return the title of this bridge publish state ex
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this bridge publish state ex.
	 *
	 * @param title the title of this bridge publish state ex
	 */
	public void setTitle(String title);

	/**
	 * Returns the path of this bridge publish state ex.
	 *
	 * @return the path of this bridge publish state ex
	 */
	@AutoEscape
	public String getPath();

	/**
	 * Sets the path of this bridge publish state ex.
	 *
	 * @param path the path of this bridge publish state ex
	 */
	public void setPath(String path);

	/**
	 * Returns the parent std ID of this bridge publish state ex.
	 *
	 * @return the parent std ID of this bridge publish state ex
	 */
	public long getParentStdId();

	/**
	 * Sets the parent std ID of this bridge publish state ex.
	 *
	 * @param parentStdId the parent std ID of this bridge publish state ex
	 */
	public void setParentStdId(long parentStdId);

	/**
	 * Returns the state cd of this bridge publish state ex.
	 *
	 * @return the state cd of this bridge publish state ex
	 */
	@AutoEscape
	public String getStateCd();

	/**
	 * Sets the state cd of this bridge publish state ex.
	 *
	 * @param stateCd the state cd of this bridge publish state ex
	 */
	public void setStateCd(String stateCd);

	/**
	 * Returns the type of this bridge publish state ex.
	 *
	 * @return the type of this bridge publish state ex
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this bridge publish state ex.
	 *
	 * @param type the type of this bridge publish state ex
	 */
	public void setType(String type);

	/**
	 * Returns the manual type of this bridge publish state ex.
	 *
	 * @return the manual type of this bridge publish state ex
	 */
	@AutoEscape
	public String getManualType();

	/**
	 * Sets the manual type of this bridge publish state ex.
	 *
	 * @param manualType the manual type of this bridge publish state ex
	 */
	public void setManualType(String manualType);

	/**
	 * Returns the count of this bridge publish state ex.
	 *
	 * @return the count of this bridge publish state ex
	 */
	public long getCount();

	/**
	 * Sets the count of this bridge publish state ex.
	 *
	 * @param count the count of this bridge publish state ex
	 */
	public void setCount(long count);

	/**
	 * Returns the display order of this bridge publish state ex.
	 *
	 * @return the display order of this bridge publish state ex
	 */
	public long getDisplayOrder();

	/**
	 * Sets the display order of this bridge publish state ex.
	 *
	 * @param displayOrder the display order of this bridge publish state ex
	 */
	public void setDisplayOrder(long displayOrder);

	/**
	 * Returns the taxonomy ID of this bridge publish state ex.
	 *
	 * @return the taxonomy ID of this bridge publish state ex
	 */
	public long getTaxonomyId();

	/**
	 * Sets the taxonomy ID of this bridge publish state ex.
	 *
	 * @param taxonomyId the taxonomy ID of this bridge publish state ex
	 */
	public void setTaxonomyId(long taxonomyId);

	/**
	 * Returns the parent taxonomy ID of this bridge publish state ex.
	 *
	 * @return the parent taxonomy ID of this bridge publish state ex
	 */
	public long getParentTaxonomyId();

	/**
	 * Sets the parent taxonomy ID of this bridge publish state ex.
	 *
	 * @param parentTaxonomyId the parent taxonomy ID of this bridge publish state ex
	 */
	public void setParentTaxonomyId(long parentTaxonomyId);

	/**
	 * Returns the index order of this bridge publish state ex.
	 *
	 * @return the index order of this bridge publish state ex
	 */
	public long getIndexOrder();

	/**
	 * Sets the index order of this bridge publish state ex.
	 *
	 * @param indexOrder the index order of this bridge publish state ex
	 */
	public void setIndexOrder(long indexOrder);

	/**
	 * Returns the level of this bridge publish state ex.
	 *
	 * @return the level of this bridge publish state ex
	 */
	public long getLevel();

	/**
	 * Sets the level of this bridge publish state ex.
	 *
	 * @param level the level of this bridge publish state ex
	 */
	public void setLevel(long level);

	/**
	 * Returns the level sort order of this bridge publish state ex.
	 *
	 * @return the level sort order of this bridge publish state ex
	 */
	public long getLevelSortOrder();

	/**
	 * Sets the level sort order of this bridge publish state ex.
	 *
	 * @param levelSortOrder the level sort order of this bridge publish state ex
	 */
	public void setLevelSortOrder(long levelSortOrder);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BridgePublishStateEx bridgePublishStateEx);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BridgePublishStateEx> toCacheModel();

	@Override
	public BridgePublishStateEx toEscapedModel();

	@Override
	public BridgePublishStateEx toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}