/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TaxonomyStandards service. Represents a row in the &quot;TAXONOMY_STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.TaxonomyStandardsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.TaxonomyStandardsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see TaxonomyStandards
 * @see com.ihg.brandstandards.db.model.impl.TaxonomyStandardsImpl
 * @see com.ihg.brandstandards.db.model.impl.TaxonomyStandardsModelImpl
 * @generated
 */
public interface TaxonomyStandardsModel extends BaseModel<TaxonomyStandards> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a taxonomy standards model instance should use the {@link TaxonomyStandards} interface instead.
	 */

	/**
	 * Returns the primary key of this taxonomy standards.
	 *
	 * @return the primary key of this taxonomy standards
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this taxonomy standards.
	 *
	 * @param primaryKey the primary key of this taxonomy standards
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the std ID of this taxonomy standards.
	 *
	 * @return the std ID of this taxonomy standards
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this taxonomy standards.
	 *
	 * @param stdId the std ID of this taxonomy standards
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the tax ID of this taxonomy standards.
	 *
	 * @return the tax ID of this taxonomy standards
	 */
	public long getTaxId();

	/**
	 * Sets the tax ID of this taxonomy standards.
	 *
	 * @param taxId the tax ID of this taxonomy standards
	 */
	public void setTaxId(long taxId);

	/**
	 * Returns the creator ID of this taxonomy standards.
	 *
	 * @return the creator ID of this taxonomy standards
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this taxonomy standards.
	 *
	 * @param creatorId the creator ID of this taxonomy standards
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this taxonomy standards.
	 *
	 * @return the created date of this taxonomy standards
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this taxonomy standards.
	 *
	 * @param createdDate the created date of this taxonomy standards
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this taxonomy standards.
	 *
	 * @return the updated by of this taxonomy standards
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this taxonomy standards.
	 *
	 * @param updatedBy the updated by of this taxonomy standards
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this taxonomy standards.
	 *
	 * @return the updated date of this taxonomy standards
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this taxonomy standards.
	 *
	 * @param updatedDate the updated date of this taxonomy standards
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TaxonomyStandards taxonomyStandards);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TaxonomyStandards> toCacheModel();

	@Override
	public TaxonomyStandards toEscapedModel();

	@Override
	public TaxonomyStandards toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}