/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BridgePublishCountry service. Represents a row in the &quot;BRIDGE_PUBLISH_CTRY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.BridgePublishCountryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.BridgePublishCountryImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see BridgePublishCountry
 * @see com.ihg.brandstandards.db.model.impl.BridgePublishCountryImpl
 * @see com.ihg.brandstandards.db.model.impl.BridgePublishCountryModelImpl
 * @generated
 */
public interface BridgePublishCountryModel extends BaseModel<BridgePublishCountry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bridge publish country model instance should use the {@link BridgePublishCountry} interface instead.
	 */

	/**
	 * Returns the primary key of this bridge publish country.
	 *
	 * @return the primary key of this bridge publish country
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bridge publish country.
	 *
	 * @param primaryKey the primary key of this bridge publish country
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the publish ctry ID of this bridge publish country.
	 *
	 * @return the publish ctry ID of this bridge publish country
	 */
	public long getPublishCtryId();

	/**
	 * Sets the publish ctry ID of this bridge publish country.
	 *
	 * @param publishCtryId the publish ctry ID of this bridge publish country
	 */
	public void setPublishCtryId(long publishCtryId);

	/**
	 * Returns the bridge publish ID of this bridge publish country.
	 *
	 * @return the bridge publish ID of this bridge publish country
	 */
	public long getBridgePublishId();

	/**
	 * Sets the bridge publish ID of this bridge publish country.
	 *
	 * @param bridgePublishId the bridge publish ID of this bridge publish country
	 */
	public void setBridgePublishId(long bridgePublishId);

	/**
	 * Returns the country code of this bridge publish country.
	 *
	 * @return the country code of this bridge publish country
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this bridge publish country.
	 *
	 * @param countryCode the country code of this bridge publish country
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the status code of this bridge publish country.
	 *
	 * @return the status code of this bridge publish country
	 */
	@AutoEscape
	public String getStatusCode();

	/**
	 * Sets the status code of this bridge publish country.
	 *
	 * @param statusCode the status code of this bridge publish country
	 */
	public void setStatusCode(String statusCode);

	/**
	 * Returns the publish ind of this bridge publish country.
	 *
	 * @return the publish ind of this bridge publish country
	 */
	@AutoEscape
	public String getPublishInd();

	/**
	 * Sets the publish ind of this bridge publish country.
	 *
	 * @param publishInd the publish ind of this bridge publish country
	 */
	public void setPublishInd(String publishInd);

	/**
	 * Returns the creator ID of this bridge publish country.
	 *
	 * @return the creator ID of this bridge publish country
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this bridge publish country.
	 *
	 * @param creatorId the creator ID of this bridge publish country
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this bridge publish country.
	 *
	 * @return the created date of this bridge publish country
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this bridge publish country.
	 *
	 * @param createdDate the created date of this bridge publish country
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this bridge publish country.
	 *
	 * @return the updated by of this bridge publish country
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this bridge publish country.
	 *
	 * @param updatedBy the updated by of this bridge publish country
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this bridge publish country.
	 *
	 * @return the updated date of this bridge publish country
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this bridge publish country.
	 *
	 * @param updatedDate the updated date of this bridge publish country
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BridgePublishCountry bridgePublishCountry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BridgePublishCountry> toCacheModel();

	@Override
	public BridgePublishCountry toEscapedModel();

	@Override
	public BridgePublishCountry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}