/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BridgePublishImport service. Represents a row in the &quot;BRIDGE_PUBLISH_IMPORT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.BridgePublishImportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.BridgePublishImportImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see BridgePublishImport
 * @see com.ihg.brandstandards.db.model.impl.BridgePublishImportImpl
 * @see com.ihg.brandstandards.db.model.impl.BridgePublishImportModelImpl
 * @generated
 */
public interface BridgePublishImportModel extends BaseModel<BridgePublishImport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bridge publish import model instance should use the {@link BridgePublishImport} interface instead.
	 */

	/**
	 * Returns the primary key of this bridge publish import.
	 *
	 * @return the primary key of this bridge publish import
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bridge publish import.
	 *
	 * @param primaryKey the primary key of this bridge publish import
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the publish import ID of this bridge publish import.
	 *
	 * @return the publish import ID of this bridge publish import
	 */
	public long getPublishImportId();

	/**
	 * Sets the publish import ID of this bridge publish import.
	 *
	 * @param publishImportId the publish import ID of this bridge publish import
	 */
	public void setPublishImportId(long publishImportId);

	/**
	 * Returns the publish ID of this bridge publish import.
	 *
	 * @return the publish ID of this bridge publish import
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this bridge publish import.
	 *
	 * @param publishId the publish ID of this bridge publish import
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the std ID of this bridge publish import.
	 *
	 * @return the std ID of this bridge publish import
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this bridge publish import.
	 *
	 * @param stdId the std ID of this bridge publish import
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the select ind of this bridge publish import.
	 *
	 * @return the select ind of this bridge publish import
	 */
	@AutoEscape
	public String getSelectInd();

	/**
	 * Sets the select ind of this bridge publish import.
	 *
	 * @param selectInd the select ind of this bridge publish import
	 */
	public void setSelectInd(String selectInd);

	/**
	 * Returns the region ID of this bridge publish import.
	 *
	 * @return the region ID of this bridge publish import
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this bridge publish import.
	 *
	 * @param regionId the region ID of this bridge publish import
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the status of this bridge publish import.
	 *
	 * @return the status of this bridge publish import
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this bridge publish import.
	 *
	 * @param status the status of this bridge publish import
	 */
	public void setStatus(String status);

	/**
	 * Returns the creator ID of this bridge publish import.
	 *
	 * @return the creator ID of this bridge publish import
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this bridge publish import.
	 *
	 * @param creatorId the creator ID of this bridge publish import
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this bridge publish import.
	 *
	 * @return the created date of this bridge publish import
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this bridge publish import.
	 *
	 * @param createdDate the created date of this bridge publish import
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this bridge publish import.
	 *
	 * @return the updated by of this bridge publish import
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this bridge publish import.
	 *
	 * @param updatedBy the updated by of this bridge publish import
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this bridge publish import.
	 *
	 * @return the updated date of this bridge publish import
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this bridge publish import.
	 *
	 * @param updatedDate the updated date of this bridge publish import
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BridgePublishImport bridgePublishImport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BridgePublishImport> toCacheModel();

	@Override
	public BridgePublishImport toEscapedModel();

	@Override
	public BridgePublishImport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}