/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ChainAttachmentsStandards service. Represents a row in the &quot;STD_ATTACHMENT_CHAIN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.ChainAttachmentsStandardsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.ChainAttachmentsStandardsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see ChainAttachmentsStandards
 * @see com.ihg.brandstandards.db.model.impl.ChainAttachmentsStandardsImpl
 * @see com.ihg.brandstandards.db.model.impl.ChainAttachmentsStandardsModelImpl
 * @generated
 */
public interface ChainAttachmentsStandardsModel extends BaseModel<ChainAttachmentsStandards> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chain attachments standards model instance should use the {@link ChainAttachmentsStandards} interface instead.
	 */

	/**
	 * Returns the primary key of this chain attachments standards.
	 *
	 * @return the primary key of this chain attachments standards
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this chain attachments standards.
	 *
	 * @param primaryKey the primary key of this chain attachments standards
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the chain attachment ID of this chain attachments standards.
	 *
	 * @return the chain attachment ID of this chain attachments standards
	 */
	public long getChainAttachmentId();

	/**
	 * Sets the chain attachment ID of this chain attachments standards.
	 *
	 * @param chainAttachmentId the chain attachment ID of this chain attachments standards
	 */
	public void setChainAttachmentId(long chainAttachmentId);

	/**
	 * Returns the attachment ID of this chain attachments standards.
	 *
	 * @return the attachment ID of this chain attachments standards
	 */
	public long getAttachmentId();

	/**
	 * Sets the attachment ID of this chain attachments standards.
	 *
	 * @param attachmentId the attachment ID of this chain attachments standards
	 */
	public void setAttachmentId(long attachmentId);

	/**
	 * Returns the locale code of this chain attachments standards.
	 *
	 * @return the locale code of this chain attachments standards
	 */
	@AutoEscape
	public String getLocaleCode();

	/**
	 * Sets the locale code of this chain attachments standards.
	 *
	 * @param localeCode the locale code of this chain attachments standards
	 */
	public void setLocaleCode(String localeCode);

	/**
	 * Returns the chain code of this chain attachments standards.
	 *
	 * @return the chain code of this chain attachments standards
	 */
	@AutoEscape
	public String getChainCode();

	/**
	 * Sets the chain code of this chain attachments standards.
	 *
	 * @param chainCode the chain code of this chain attachments standards
	 */
	public void setChainCode(String chainCode);

	/**
	 * Returns the creator ID of this chain attachments standards.
	 *
	 * @return the creator ID of this chain attachments standards
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this chain attachments standards.
	 *
	 * @param creatorId the creator ID of this chain attachments standards
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this chain attachments standards.
	 *
	 * @return the created date of this chain attachments standards
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this chain attachments standards.
	 *
	 * @param createdDate the created date of this chain attachments standards
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this chain attachments standards.
	 *
	 * @return the updated by of this chain attachments standards
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this chain attachments standards.
	 *
	 * @param updatedBy the updated by of this chain attachments standards
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this chain attachments standards.
	 *
	 * @return the updated date of this chain attachments standards
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this chain attachments standards.
	 *
	 * @param updatedDate the updated date of this chain attachments standards
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ChainAttachmentsStandards chainAttachmentsStandards);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ChainAttachmentsStandards> toCacheModel();

	@Override
	public ChainAttachmentsStandards toEscapedModel();

	@Override
	public ChainAttachmentsStandards toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}