/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.ihg.brandstandards.db.service.persistence.CountryStandardsExtPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CountryStandardsExt service. Represents a row in the &quot;CTRY_STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.CountryStandardsExtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.CountryStandardsExtImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see CountryStandardsExt
 * @see com.ihg.brandstandards.db.model.impl.CountryStandardsExtImpl
 * @see com.ihg.brandstandards.db.model.impl.CountryStandardsExtModelImpl
 * @generated
 */
public interface CountryStandardsExtModel extends BaseModel<CountryStandardsExt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a country standards ext model instance should use the {@link CountryStandardsExt} interface instead.
	 */

	/**
	 * Returns the primary key of this country standards ext.
	 *
	 * @return the primary key of this country standards ext
	 */
	public CountryStandardsExtPK getPrimaryKey();

	/**
	 * Sets the primary key of this country standards ext.
	 *
	 * @param primaryKey the primary key of this country standards ext
	 */
	public void setPrimaryKey(CountryStandardsExtPK primaryKey);

	/**
	 * Returns the country code of this country standards ext.
	 *
	 * @return the country code of this country standards ext
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this country standards ext.
	 *
	 * @param countryCode the country code of this country standards ext
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the std ID of this country standards ext.
	 *
	 * @return the std ID of this country standards ext
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this country standards ext.
	 *
	 * @param stdId the std ID of this country standards ext
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the region ID of this country standards ext.
	 *
	 * @return the region ID of this country standards ext
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this country standards ext.
	 *
	 * @param regionId the region ID of this country standards ext
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the region code of this country standards ext.
	 *
	 * @return the region code of this country standards ext
	 */
	@AutoEscape
	public String getRegionCode();

	/**
	 * Sets the region code of this country standards ext.
	 *
	 * @param regionCode the region code of this country standards ext
	 */
	public void setRegionCode(String regionCode);

	/**
	 * Returns the region name of this country standards ext.
	 *
	 * @return the region name of this country standards ext
	 */
	@AutoEscape
	public String getRegionName();

	/**
	 * Sets the region name of this country standards ext.
	 *
	 * @param regionName the region name of this country standards ext
	 */
	public void setRegionName(String regionName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CountryStandardsExt countryStandardsExt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CountryStandardsExt> toCacheModel();

	@Override
	public CountryStandardsExt toEscapedModel();

	@Override
	public CountryStandardsExt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}