/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ErrNotification service. Represents a row in the &quot;ERR_NOTIFICATION&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.ErrNotificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.ErrNotificationImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see ErrNotification
 * @see com.ihg.brandstandards.db.model.impl.ErrNotificationImpl
 * @see com.ihg.brandstandards.db.model.impl.ErrNotificationModelImpl
 * @generated
 */
public interface ErrNotificationModel extends BaseModel<ErrNotification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a err notification model instance should use the {@link ErrNotification} interface instead.
	 */

	/**
	 * Returns the primary key of this err notification.
	 *
	 * @return the primary key of this err notification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this err notification.
	 *
	 * @param primaryKey the primary key of this err notification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the notification ID of this err notification.
	 *
	 * @return the notification ID of this err notification
	 */
	public long getNotificationId();

	/**
	 * Sets the notification ID of this err notification.
	 *
	 * @param notificationId the notification ID of this err notification
	 */
	public void setNotificationId(long notificationId);

	/**
	 * Returns the component name of this err notification.
	 *
	 * @return the component name of this err notification
	 */
	@AutoEscape
	public String getComponentName();

	/**
	 * Sets the component name of this err notification.
	 *
	 * @param componentName the component name of this err notification
	 */
	public void setComponentName(String componentName);

	/**
	 * Returns the reference ID of this err notification.
	 *
	 * @return the reference ID of this err notification
	 */
	public long getReferenceId();

	/**
	 * Sets the reference ID of this err notification.
	 *
	 * @param referenceId the reference ID of this err notification
	 */
	public void setReferenceId(long referenceId);

	/**
	 * Returns the severity of this err notification.
	 *
	 * @return the severity of this err notification
	 */
	@AutoEscape
	public String getSeverity();

	/**
	 * Sets the severity of this err notification.
	 *
	 * @param severity the severity of this err notification
	 */
	public void setSeverity(String severity);

	/**
	 * Returns the title of this err notification.
	 *
	 * @return the title of this err notification
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this err notification.
	 *
	 * @param title the title of this err notification
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this err notification.
	 *
	 * @return the description of this err notification
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this err notification.
	 *
	 * @param description the description of this err notification
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this err notification.
	 *
	 * @return the status of this err notification
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this err notification.
	 *
	 * @param status the status of this err notification
	 */
	public void setStatus(String status);

	/**
	 * Returns the publish ID of this err notification.
	 *
	 * @return the publish ID of this err notification
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this err notification.
	 *
	 * @param publishId the publish ID of this err notification
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the region ID of this err notification.
	 *
	 * @return the region ID of this err notification
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this err notification.
	 *
	 * @param regionId the region ID of this err notification
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the creator ID of this err notification.
	 *
	 * @return the creator ID of this err notification
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this err notification.
	 *
	 * @param creatorId the creator ID of this err notification
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this err notification.
	 *
	 * @return the created date of this err notification
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this err notification.
	 *
	 * @param createdDate the created date of this err notification
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this err notification.
	 *
	 * @return the updated by of this err notification
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this err notification.
	 *
	 * @param updatedBy the updated by of this err notification
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this err notification.
	 *
	 * @return the updated date of this err notification
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this err notification.
	 *
	 * @param updatedDate the updated date of this err notification
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ErrNotification errNotification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ErrNotification> toCacheModel();

	@Override
	public ErrNotification toEscapedModel();

	@Override
	public ErrNotification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}