/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the JobQueue service. Represents a row in the &quot;JOB_QUEUE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.JobQueueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.JobQueueImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see JobQueue
 * @see com.ihg.brandstandards.db.model.impl.JobQueueImpl
 * @see com.ihg.brandstandards.db.model.impl.JobQueueModelImpl
 * @generated
 */
public interface JobQueueModel extends BaseModel<JobQueue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job queue model instance should use the {@link JobQueue} interface instead.
	 */

	/**
	 * Returns the primary key of this job queue.
	 *
	 * @return the primary key of this job queue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job queue.
	 *
	 * @param primaryKey the primary key of this job queue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job ID of this job queue.
	 *
	 * @return the job ID of this job queue
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this job queue.
	 *
	 * @param jobId the job ID of this job queue
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the job owner of this job queue.
	 *
	 * @return the job owner of this job queue
	 */
	@AutoEscape
	public String getJobOwner();

	/**
	 * Sets the job owner of this job queue.
	 *
	 * @param jobOwner the job owner of this job queue
	 */
	public void setJobOwner(String jobOwner);

	/**
	 * Returns the job type of this job queue.
	 *
	 * @return the job type of this job queue
	 */
	@AutoEscape
	public String getJobType();

	/**
	 * Sets the job type of this job queue.
	 *
	 * @param jobType the job type of this job queue
	 */
	public void setJobType(String jobType);

	/**
	 * Returns the metadata of this job queue.
	 *
	 * @return the metadata of this job queue
	 */
	@AutoEscape
	public String getMetadata();

	/**
	 * Sets the metadata of this job queue.
	 *
	 * @param metadata the metadata of this job queue
	 */
	public void setMetadata(String metadata);

	/**
	 * Returns the link of this job queue.
	 *
	 * @return the link of this job queue
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this job queue.
	 *
	 * @param link the link of this job queue
	 */
	public void setLink(String link);

	/**
	 * Returns the notification email of this job queue.
	 *
	 * @return the notification email of this job queue
	 */
	@AutoEscape
	public String getNotificationEmail();

	/**
	 * Sets the notification email of this job queue.
	 *
	 * @param notificationEmail the notification email of this job queue
	 */
	public void setNotificationEmail(String notificationEmail);

	/**
	 * Returns the start time of this job queue.
	 *
	 * @return the start time of this job queue
	 */
	public Date getStartTime();

	/**
	 * Sets the start time of this job queue.
	 *
	 * @param startTime the start time of this job queue
	 */
	public void setStartTime(Date startTime);

	/**
	 * Returns the end time of this job queue.
	 *
	 * @return the end time of this job queue
	 */
	public Date getEndTime();

	/**
	 * Sets the end time of this job queue.
	 *
	 * @param endTime the end time of this job queue
	 */
	public void setEndTime(Date endTime);

	/**
	 * Returns the status of this job queue.
	 *
	 * @return the status of this job queue
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this job queue.
	 *
	 * @param status the status of this job queue
	 */
	public void setStatus(String status);

	/**
	 * Returns the creator ID of this job queue.
	 *
	 * @return the creator ID of this job queue
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this job queue.
	 *
	 * @param creatorId the creator ID of this job queue
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this job queue.
	 *
	 * @return the created date of this job queue
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this job queue.
	 *
	 * @param createdDate the created date of this job queue
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this job queue.
	 *
	 * @return the updated by of this job queue
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this job queue.
	 *
	 * @param updatedBy the updated by of this job queue
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this job queue.
	 *
	 * @return the updated date of this job queue
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this job queue.
	 *
	 * @param updatedDate the updated date of this job queue
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JobQueue jobQueue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JobQueue> toCacheModel();

	@Override
	public JobQueue toEscapedModel();

	@Override
	public JobQueue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}