/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PublishQueue service. Represents a row in the &quot;PUBLISH_QUEUE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.PublishQueueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.PublishQueueImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see PublishQueue
 * @see com.ihg.brandstandards.db.model.impl.PublishQueueImpl
 * @see com.ihg.brandstandards.db.model.impl.PublishQueueModelImpl
 * @generated
 */
public interface PublishQueueModel extends BaseModel<PublishQueue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a publish queue model instance should use the {@link PublishQueue} interface instead.
	 */

	/**
	 * Returns the primary key of this publish queue.
	 *
	 * @return the primary key of this publish queue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this publish queue.
	 *
	 * @param primaryKey the primary key of this publish queue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the publish queue ID of this publish queue.
	 *
	 * @return the publish queue ID of this publish queue
	 */
	public long getPublishQueueId();

	/**
	 * Sets the publish queue ID of this publish queue.
	 *
	 * @param publishQueueId the publish queue ID of this publish queue
	 */
	public void setPublishQueueId(long publishQueueId);

	/**
	 * Returns the publish file text of this publish queue.
	 *
	 * @return the publish file text of this publish queue
	 */
	@AutoEscape
	public String getPublishFileText();

	/**
	 * Sets the publish file text of this publish queue.
	 *
	 * @param publishFileText the publish file text of this publish queue
	 */
	public void setPublishFileText(String publishFileText);

	/**
	 * Returns the publish environment of this publish queue.
	 *
	 * @return the publish environment of this publish queue
	 */
	@AutoEscape
	public String getPublishEnvironment();

	/**
	 * Sets the publish environment of this publish queue.
	 *
	 * @param publishEnvironment the publish environment of this publish queue
	 */
	public void setPublishEnvironment(String publishEnvironment);

	/**
	 * Returns the schedule publish of this publish queue.
	 *
	 * @return the schedule publish of this publish queue
	 */
	public Date getSchedulePublish();

	/**
	 * Sets the schedule publish of this publish queue.
	 *
	 * @param schedulePublish the schedule publish of this publish queue
	 */
	public void setSchedulePublish(Date schedulePublish);

	/**
	 * Returns the queue stat cd of this publish queue.
	 *
	 * @return the queue stat cd of this publish queue
	 */
	@AutoEscape
	public String getQueueStatCd();

	/**
	 * Sets the queue stat cd of this publish queue.
	 *
	 * @param queueStatCd the queue stat cd of this publish queue
	 */
	public void setQueueStatCd(String queueStatCd);

	/**
	 * Returns the chain cd of this publish queue.
	 *
	 * @return the chain cd of this publish queue
	 */
	@AutoEscape
	public String getChainCd();

	/**
	 * Sets the chain cd of this publish queue.
	 *
	 * @param chainCd the chain cd of this publish queue
	 */
	public void setChainCd(String chainCd);

	/**
	 * Returns the notification email ID of this publish queue.
	 *
	 * @return the notification email ID of this publish queue
	 */
	@AutoEscape
	public String getNotificationEmailId();

	/**
	 * Sets the notification email ID of this publish queue.
	 *
	 * @param notificationEmailId the notification email ID of this publish queue
	 */
	public void setNotificationEmailId(String notificationEmailId);

	/**
	 * Returns the schedule start of this publish queue.
	 *
	 * @return the schedule start of this publish queue
	 */
	public Date getScheduleStart();

	/**
	 * Sets the schedule start of this publish queue.
	 *
	 * @param scheduleStart the schedule start of this publish queue
	 */
	public void setScheduleStart(Date scheduleStart);

	/**
	 * Returns the schedule end of this publish queue.
	 *
	 * @return the schedule end of this publish queue
	 */
	public Date getScheduleEnd();

	/**
	 * Sets the schedule end of this publish queue.
	 *
	 * @param scheduleEnd the schedule end of this publish queue
	 */
	public void setScheduleEnd(Date scheduleEnd);

	/**
	 * Returns the expected prod publish dt of this publish queue.
	 *
	 * @return the expected prod publish dt of this publish queue
	 */
	public Date getExpectedProdPublishDt();

	/**
	 * Sets the expected prod publish dt of this publish queue.
	 *
	 * @param expectedProdPublishDt the expected prod publish dt of this publish queue
	 */
	public void setExpectedProdPublishDt(Date expectedProdPublishDt);

	/**
	 * Returns the publish ID of this publish queue.
	 *
	 * @return the publish ID of this publish queue
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this publish queue.
	 *
	 * @param publishId the publish ID of this publish queue
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the publish locale list of this publish queue.
	 *
	 * @return the publish locale list of this publish queue
	 */
	@AutoEscape
	public String getPublishLocaleList();

	/**
	 * Sets the publish locale list of this publish queue.
	 *
	 * @param publishLocaleList the publish locale list of this publish queue
	 */
	public void setPublishLocaleList(String publishLocaleList);

	/**
	 * Returns the creator ID of this publish queue.
	 *
	 * @return the creator ID of this publish queue
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this publish queue.
	 *
	 * @param creatorId the creator ID of this publish queue
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this publish queue.
	 *
	 * @return the created date of this publish queue
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this publish queue.
	 *
	 * @param createdDate the created date of this publish queue
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this publish queue.
	 *
	 * @return the updated by of this publish queue
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this publish queue.
	 *
	 * @param updatedBy the updated by of this publish queue
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this publish queue.
	 *
	 * @return the updated date of this publish queue
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this publish queue.
	 *
	 * @param updatedDate the updated date of this publish queue
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PublishQueue publishQueue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PublishQueue> toCacheModel();

	@Override
	public PublishQueue toEscapedModel();

	@Override
	public PublishQueue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}