/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.ihg.brandstandards.db.service.persistence.StandardsDisplayOrderPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsDisplayOrder service. Represents a row in the &quot;STD_DISPLAY_ORDER&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsDisplayOrderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsDisplayOrderImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsDisplayOrder
 * @see com.ihg.brandstandards.db.model.impl.StandardsDisplayOrderImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsDisplayOrderModelImpl
 * @generated
 */
public interface StandardsDisplayOrderModel extends BaseModel<StandardsDisplayOrder> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards display order model instance should use the {@link StandardsDisplayOrder} interface instead.
	 */

	/**
	 * Returns the primary key of this standards display order.
	 *
	 * @return the primary key of this standards display order
	 */
	public StandardsDisplayOrderPK getPrimaryKey();

	/**
	 * Sets the primary key of this standards display order.
	 *
	 * @param primaryKey the primary key of this standards display order
	 */
	public void setPrimaryKey(StandardsDisplayOrderPK primaryKey);

	/**
	 * Returns the std ID of this standards display order.
	 *
	 * @return the std ID of this standards display order
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this standards display order.
	 *
	 * @param stdId the std ID of this standards display order
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the region code of this standards display order.
	 *
	 * @return the region code of this standards display order
	 */
	@AutoEscape
	public String getRegionCode();

	/**
	 * Sets the region code of this standards display order.
	 *
	 * @param regionCode the region code of this standards display order
	 */
	public void setRegionCode(String regionCode);

	/**
	 * Returns the chain code of this standards display order.
	 *
	 * @return the chain code of this standards display order
	 */
	@AutoEscape
	public String getChainCode();

	/**
	 * Sets the chain code of this standards display order.
	 *
	 * @param chainCode the chain code of this standards display order
	 */
	public void setChainCode(String chainCode);

	/**
	 * Returns the display order of this standards display order.
	 *
	 * @return the display order of this standards display order
	 */
	public long getDisplayOrder();

	/**
	 * Sets the display order of this standards display order.
	 *
	 * @param displayOrder the display order of this standards display order
	 */
	public void setDisplayOrder(long displayOrder);

	/**
	 * Returns the creator ID of this standards display order.
	 *
	 * @return the creator ID of this standards display order
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards display order.
	 *
	 * @param creatorId the creator ID of this standards display order
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards display order.
	 *
	 * @return the created date of this standards display order
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards display order.
	 *
	 * @param createdDate the created date of this standards display order
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards display order.
	 *
	 * @return the updated by of this standards display order
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards display order.
	 *
	 * @param updatedBy the updated by of this standards display order
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards display order.
	 *
	 * @return the updated date of this standards display order
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards display order.
	 *
	 * @param updatedDate the updated date of this standards display order
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsDisplayOrder standardsDisplayOrder);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsDisplayOrder> toCacheModel();

	@Override
	public StandardsDisplayOrder toEscapedModel();

	@Override
	public StandardsDisplayOrder toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}