/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.ihg.brandstandards.db.service.persistence.StandardsTranslatePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsTranslate service. Represents a row in the &quot;STD_XLAT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsTranslateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsTranslateImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsTranslate
 * @see com.ihg.brandstandards.db.model.impl.StandardsTranslateImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsTranslateModelImpl
 * @generated
 */
public interface StandardsTranslateModel extends BaseModel<StandardsTranslate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards translate model instance should use the {@link StandardsTranslate} interface instead.
	 */

	/**
	 * Returns the primary key of this standards translate.
	 *
	 * @return the primary key of this standards translate
	 */
	public StandardsTranslatePK getPrimaryKey();

	/**
	 * Sets the primary key of this standards translate.
	 *
	 * @param primaryKey the primary key of this standards translate
	 */
	public void setPrimaryKey(StandardsTranslatePK primaryKey);

	/**
	 * Returns the std ID of this standards translate.
	 *
	 * @return the std ID of this standards translate
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this standards translate.
	 *
	 * @param stdId the std ID of this standards translate
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the locale code of this standards translate.
	 *
	 * @return the locale code of this standards translate
	 */
	@AutoEscape
	public String getLocaleCode();

	/**
	 * Sets the locale code of this standards translate.
	 *
	 * @param localeCode the locale code of this standards translate
	 */
	public void setLocaleCode(String localeCode);

	/**
	 * Returns the title of this standards translate.
	 *
	 * @return the title of this standards translate
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this standards translate.
	 *
	 * @param title the title of this standards translate
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this standards translate.
	 *
	 * @return the description of this standards translate
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this standards translate.
	 *
	 * @param description the description of this standards translate
	 */
	public void setDescription(String description);

	/**
	 * Returns the note of this standards translate.
	 *
	 * @return the note of this standards translate
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this standards translate.
	 *
	 * @param note the note of this standards translate
	 */
	public void setNote(String note);

	/**
	 * Returns the comment of this standards translate.
	 *
	 * @return the comment of this standards translate
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this standards translate.
	 *
	 * @param comment the comment of this standards translate
	 */
	public void setComment(String comment);

	/**
	 * Returns the creator ID of this standards translate.
	 *
	 * @return the creator ID of this standards translate
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards translate.
	 *
	 * @param creatorId the creator ID of this standards translate
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards translate.
	 *
	 * @return the created date of this standards translate
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards translate.
	 *
	 * @param createdDate the created date of this standards translate
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards translate.
	 *
	 * @return the updated by of this standards translate
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards translate.
	 *
	 * @param updatedBy the updated by of this standards translate
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards translate.
	 *
	 * @return the updated date of this standards translate
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards translate.
	 *
	 * @param updatedDate the updated date of this standards translate
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the is valid txt of this standards translate.
	 *
	 * @return the is valid txt of this standards translate
	 */
	@AutoEscape
	public String getIsValidTxt();

	/**
	 * Sets the is valid txt of this standards translate.
	 *
	 * @param isValidTxt the is valid txt of this standards translate
	 */
	public void setIsValidTxt(String isValidTxt);

	/**
	 * Returns the is valid cntxt of this standards translate.
	 *
	 * @return the is valid cntxt of this standards translate
	 */
	@AutoEscape
	public String getIsValidCntxt();

	/**
	 * Sets the is valid cntxt of this standards translate.
	 *
	 * @param isValidCntxt the is valid cntxt of this standards translate
	 */
	public void setIsValidCntxt(String isValidCntxt);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsTranslate standardsTranslate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsTranslate> toCacheModel();

	@Override
	public StandardsTranslate toEscapedModel();

	@Override
	public StandardsTranslate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}