/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.ihg.brandstandards.db.service.persistence.StandardsRegionLocalePK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsRegionLocale service. Represents a row in the &quot;BRNDSTND_RGN_LOCALE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsRegionLocaleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsRegionLocaleImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsRegionLocale
 * @see com.ihg.brandstandards.db.model.impl.StandardsRegionLocaleImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsRegionLocaleModelImpl
 * @generated
 */
public interface StandardsRegionLocaleModel extends BaseModel<StandardsRegionLocale> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards region locale model instance should use the {@link StandardsRegionLocale} interface instead.
	 */

	/**
	 * Returns the primary key of this standards region locale.
	 *
	 * @return the primary key of this standards region locale
	 */
	public StandardsRegionLocalePK getPrimaryKey();

	/**
	 * Sets the primary key of this standards region locale.
	 *
	 * @param primaryKey the primary key of this standards region locale
	 */
	public void setPrimaryKey(StandardsRegionLocalePK primaryKey);

	/**
	 * Returns the region ID of this standards region locale.
	 *
	 * @return the region ID of this standards region locale
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this standards region locale.
	 *
	 * @param regionId the region ID of this standards region locale
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the locale code of this standards region locale.
	 *
	 * @return the locale code of this standards region locale
	 */
	@AutoEscape
	public String getLocaleCode();

	/**
	 * Sets the locale code of this standards region locale.
	 *
	 * @param localeCode the locale code of this standards region locale
	 */
	public void setLocaleCode(String localeCode);

	/**
	 * Returns the is default of this standards region locale.
	 *
	 * @return the is default of this standards region locale
	 */
	@AutoEscape
	public String getIsDefault();

	/**
	 * Sets the is default of this standards region locale.
	 *
	 * @param isDefault the is default of this standards region locale
	 */
	public void setIsDefault(String isDefault);

	/**
	 * Returns the creator ID of this standards region locale.
	 *
	 * @return the creator ID of this standards region locale
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards region locale.
	 *
	 * @param creatorId the creator ID of this standards region locale
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards region locale.
	 *
	 * @return the created date of this standards region locale
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards region locale.
	 *
	 * @param createdDate the created date of this standards region locale
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards region locale.
	 *
	 * @return the updated by of this standards region locale
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards region locale.
	 *
	 * @param updatedBy the updated by of this standards region locale
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards region locale.
	 *
	 * @return the updated date of this standards region locale
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards region locale.
	 *
	 * @param updatedDate the updated date of this standards region locale
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsRegionLocale standardsRegionLocale);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsRegionLocale> toCacheModel();

	@Override
	public StandardsRegionLocale toEscapedModel();

	@Override
	public StandardsRegionLocale toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}