/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.GEMMeasurementType;
import com.ihg.brandstandards.db.model.GEMMeasurementTypeModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the GEMMeasurementType service. Represents a row in the &quot;GEM_MSRMNT_TYP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.GEMMeasurementTypeModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GEMMeasurementTypeImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMMeasurementTypeImpl
 * @see com.ihg.brandstandards.db.model.GEMMeasurementType
 * @see com.ihg.brandstandards.db.model.GEMMeasurementTypeModel
 * @generated
 */
public class GEMMeasurementTypeModelImpl extends BaseModelImpl<GEMMeasurementType>
	implements GEMMeasurementTypeModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a g e m measurement type model instance should use the {@link com.ihg.brandstandards.db.model.GEMMeasurementType} interface instead.
	 */
	public static final String TABLE_NAME = "GEM_MSRMNT_TYP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "GEM_MSRMNT_TYP_CD", Types.VARCHAR },
			{ "GEM_MSRMNT_TYP_DESC", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table GEM_MSRMNT_TYP (GEM_MSRMNT_TYP_CD VARCHAR(75) not null primary key,GEM_MSRMNT_TYP_DESC VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table GEM_MSRMNT_TYP";
	public static final String ORDER_BY_JPQL = " ORDER BY gemMeasurementType.measurementType ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GEM_MSRMNT_TYP.GEM_MSRMNT_TYP_CD ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.GEMMeasurementType"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.GEMMeasurementType"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.GEMMeasurementType"));

	public GEMMeasurementTypeModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _measurementType;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setMeasurementType(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _measurementType;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return GEMMeasurementType.class;
	}

	@Override
	public String getModelClassName() {
		return GEMMeasurementType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("measurementType", getMeasurementType());
		attributes.put("measurementTypeDesc", getMeasurementTypeDesc());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String measurementType = (String)attributes.get("measurementType");

		if (measurementType != null) {
			setMeasurementType(measurementType);
		}

		String measurementTypeDesc = (String)attributes.get(
				"measurementTypeDesc");

		if (measurementTypeDesc != null) {
			setMeasurementTypeDesc(measurementTypeDesc);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public String getMeasurementType() {
		if (_measurementType == null) {
			return StringPool.BLANK;
		}
		else {
			return _measurementType;
		}
	}

	@Override
	public void setMeasurementType(String measurementType) {
		_measurementType = measurementType;
	}

	@Override
	public String getMeasurementTypeDesc() {
		if (_measurementTypeDesc == null) {
			return StringPool.BLANK;
		}
		else {
			return _measurementTypeDesc;
		}
	}

	@Override
	public void setMeasurementTypeDesc(String measurementTypeDesc) {
		_measurementTypeDesc = measurementTypeDesc;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@Override
	public GEMMeasurementType toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (GEMMeasurementType)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GEMMeasurementTypeImpl gemMeasurementTypeImpl = new GEMMeasurementTypeImpl();

		gemMeasurementTypeImpl.setMeasurementType(getMeasurementType());
		gemMeasurementTypeImpl.setMeasurementTypeDesc(getMeasurementTypeDesc());
		gemMeasurementTypeImpl.setCreatorId(getCreatorId());
		gemMeasurementTypeImpl.setCreatedDate(getCreatedDate());
		gemMeasurementTypeImpl.setUpdatedBy(getUpdatedBy());
		gemMeasurementTypeImpl.setUpdatedDate(getUpdatedDate());

		gemMeasurementTypeImpl.resetOriginalValues();

		return gemMeasurementTypeImpl;
	}

	@Override
	public int compareTo(GEMMeasurementType gemMeasurementType) {
		String primaryKey = gemMeasurementType.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GEMMeasurementType)) {
			return false;
		}

		GEMMeasurementType gemMeasurementType = (GEMMeasurementType)obj;

		String primaryKey = gemMeasurementType.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<GEMMeasurementType> toCacheModel() {
		GEMMeasurementTypeCacheModel gemMeasurementTypeCacheModel = new GEMMeasurementTypeCacheModel();

		gemMeasurementTypeCacheModel.measurementType = getMeasurementType();

		String measurementType = gemMeasurementTypeCacheModel.measurementType;

		if ((measurementType != null) && (measurementType.length() == 0)) {
			gemMeasurementTypeCacheModel.measurementType = null;
		}

		gemMeasurementTypeCacheModel.measurementTypeDesc = getMeasurementTypeDesc();

		String measurementTypeDesc = gemMeasurementTypeCacheModel.measurementTypeDesc;

		if ((measurementTypeDesc != null) &&
				(measurementTypeDesc.length() == 0)) {
			gemMeasurementTypeCacheModel.measurementTypeDesc = null;
		}

		gemMeasurementTypeCacheModel.creatorId = getCreatorId();

		String creatorId = gemMeasurementTypeCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			gemMeasurementTypeCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			gemMeasurementTypeCacheModel.createdDate = createdDate.getTime();
		}
		else {
			gemMeasurementTypeCacheModel.createdDate = Long.MIN_VALUE;
		}

		gemMeasurementTypeCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = gemMeasurementTypeCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			gemMeasurementTypeCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			gemMeasurementTypeCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			gemMeasurementTypeCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return gemMeasurementTypeCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{measurementType=");
		sb.append(getMeasurementType());
		sb.append(", measurementTypeDesc=");
		sb.append(getMeasurementTypeDesc());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.GEMMeasurementType");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>measurementType</column-name><column-value><![CDATA[");
		sb.append(getMeasurementType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>measurementTypeDesc</column-name><column-value><![CDATA[");
		sb.append(getMeasurementTypeDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = GEMMeasurementType.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			GEMMeasurementType.class
		};
	private String _measurementType;
	private String _measurementTypeDesc;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private GEMMeasurementType _escapedModel;
}