/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BridgeGlobalPublish service. Represents a row in the &quot;BRIDGE_GBL_PUBLISH&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.BridgeGlobalPublishModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.BridgeGlobalPublishImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see BridgeGlobalPublish
 * @see com.ihg.brandstandards.db.model.impl.BridgeGlobalPublishImpl
 * @see com.ihg.brandstandards.db.model.impl.BridgeGlobalPublishModelImpl
 * @generated
 */
public interface BridgeGlobalPublishModel extends BaseModel<BridgeGlobalPublish> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bridge global publish model instance should use the {@link BridgeGlobalPublish} interface instead.
	 */

	/**
	 * Returns the primary key of this bridge global publish.
	 *
	 * @return the primary key of this bridge global publish
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bridge global publish.
	 *
	 * @param primaryKey the primary key of this bridge global publish
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the global publish ID of this bridge global publish.
	 *
	 * @return the global publish ID of this bridge global publish
	 */
	public long getGlobalPublishId();

	/**
	 * Sets the global publish ID of this bridge global publish.
	 *
	 * @param globalPublishId the global publish ID of this bridge global publish
	 */
	public void setGlobalPublishId(long globalPublishId);

	/**
	 * Returns the publish ID of this bridge global publish.
	 *
	 * @return the publish ID of this bridge global publish
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this bridge global publish.
	 *
	 * @param publishId the publish ID of this bridge global publish
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the std ID of this bridge global publish.
	 *
	 * @return the std ID of this bridge global publish
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this bridge global publish.
	 *
	 * @param stdId the std ID of this bridge global publish
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the must publish ind of this bridge global publish.
	 *
	 * @return the must publish ind of this bridge global publish
	 */
	@AutoEscape
	public String getMustPublishInd();

	/**
	 * Sets the must publish ind of this bridge global publish.
	 *
	 * @param mustPublishInd the must publish ind of this bridge global publish
	 */
	public void setMustPublishInd(String mustPublishInd);

	/**
	 * Returns the creator ID of this bridge global publish.
	 *
	 * @return the creator ID of this bridge global publish
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this bridge global publish.
	 *
	 * @param creatorId the creator ID of this bridge global publish
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this bridge global publish.
	 *
	 * @return the created date of this bridge global publish
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this bridge global publish.
	 *
	 * @param createdDate the created date of this bridge global publish
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this bridge global publish.
	 *
	 * @return the updated by of this bridge global publish
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this bridge global publish.
	 *
	 * @param updatedBy the updated by of this bridge global publish
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this bridge global publish.
	 *
	 * @return the updated date of this bridge global publish
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this bridge global publish.
	 *
	 * @param updatedDate the updated date of this bridge global publish
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BridgeGlobalPublish bridgeGlobalPublish);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BridgeGlobalPublish> toCacheModel();

	@Override
	public BridgeGlobalPublish toEscapedModel();

	@Override
	public BridgeGlobalPublish toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}