/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the BridgeProgressCategory service. Represents a row in the &quot;BRIDGE_PUBLISH_PROGRESS_CATGY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.BridgeProgressCategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.BridgeProgressCategoryImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see BridgeProgressCategory
 * @see com.ihg.brandstandards.db.model.impl.BridgeProgressCategoryImpl
 * @see com.ihg.brandstandards.db.model.impl.BridgeProgressCategoryModelImpl
 * @generated
 */
public interface BridgeProgressCategoryModel extends BaseModel<BridgeProgressCategory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bridge progress category model instance should use the {@link BridgeProgressCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this bridge progress category.
	 *
	 * @return the primary key of this bridge progress category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bridge progress category.
	 *
	 * @param primaryKey the primary key of this bridge progress category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the progress category ID of this bridge progress category.
	 *
	 * @return the progress category ID of this bridge progress category
	 */
	public long getProgressCategoryId();

	/**
	 * Sets the progress category ID of this bridge progress category.
	 *
	 * @param progressCategoryId the progress category ID of this bridge progress category
	 */
	public void setProgressCategoryId(long progressCategoryId);

	/**
	 * Returns the progress category name of this bridge progress category.
	 *
	 * @return the progress category name of this bridge progress category
	 */
	@AutoEscape
	public String getProgressCategoryName();

	/**
	 * Sets the progress category name of this bridge progress category.
	 *
	 * @param progressCategoryName the progress category name of this bridge progress category
	 */
	public void setProgressCategoryName(String progressCategoryName);

	/**
	 * Returns the display order number of this bridge progress category.
	 *
	 * @return the display order number of this bridge progress category
	 */
	public long getDisplayOrderNumber();

	/**
	 * Sets the display order number of this bridge progress category.
	 *
	 * @param displayOrderNumber the display order number of this bridge progress category
	 */
	public void setDisplayOrderNumber(long displayOrderNumber);

	/**
	 * Returns the creator ID of this bridge progress category.
	 *
	 * @return the creator ID of this bridge progress category
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this bridge progress category.
	 *
	 * @param creatorId the creator ID of this bridge progress category
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this bridge progress category.
	 *
	 * @return the created date of this bridge progress category
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this bridge progress category.
	 *
	 * @param createdDate the created date of this bridge progress category
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this bridge progress category.
	 *
	 * @return the updated by of this bridge progress category
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this bridge progress category.
	 *
	 * @param updatedBy the updated by of this bridge progress category
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this bridge progress category.
	 *
	 * @return the updated date of this bridge progress category
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this bridge progress category.
	 *
	 * @param updatedDate the updated date of this bridge progress category
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(BridgeProgressCategory bridgeProgressCategory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<BridgeProgressCategory> toCacheModel();

	@Override
	public BridgeProgressCategory toEscapedModel();

	@Override
	public BridgeProgressCategory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}