/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.ihg.brandstandards.db.service.persistence.FlagStandardsPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FlagStandards service. Represents a row in the &quot;FLAG_STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.FlagStandardsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.FlagStandardsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see FlagStandards
 * @see com.ihg.brandstandards.db.model.impl.FlagStandardsImpl
 * @see com.ihg.brandstandards.db.model.impl.FlagStandardsModelImpl
 * @generated
 */
public interface FlagStandardsModel extends BaseModel<FlagStandards> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a flag standards model instance should use the {@link FlagStandards} interface instead.
	 */

	/**
	 * Returns the primary key of this flag standards.
	 *
	 * @return the primary key of this flag standards
	 */
	public FlagStandardsPK getPrimaryKey();

	/**
	 * Sets the primary key of this flag standards.
	 *
	 * @param primaryKey the primary key of this flag standards
	 */
	public void setPrimaryKey(FlagStandardsPK primaryKey);

	/**
	 * Returns the flag cat ID of this flag standards.
	 *
	 * @return the flag cat ID of this flag standards
	 */
	public long getFlagCatId();

	/**
	 * Sets the flag cat ID of this flag standards.
	 *
	 * @param flagCatId the flag cat ID of this flag standards
	 */
	public void setFlagCatId(long flagCatId);

	/**
	 * Returns the std ID of this flag standards.
	 *
	 * @return the std ID of this flag standards
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this flag standards.
	 *
	 * @param stdId the std ID of this flag standards
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the creator ID of this flag standards.
	 *
	 * @return the creator ID of this flag standards
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this flag standards.
	 *
	 * @param creatorId the creator ID of this flag standards
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this flag standards.
	 *
	 * @return the created date of this flag standards
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this flag standards.
	 *
	 * @param createdDate the created date of this flag standards
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this flag standards.
	 *
	 * @return the updated by of this flag standards
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this flag standards.
	 *
	 * @param updatedBy the updated by of this flag standards
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this flag standards.
	 *
	 * @return the updated date of this flag standards
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this flag standards.
	 *
	 * @param updatedDate the updated date of this flag standards
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FlagStandards flagStandards);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FlagStandards> toCacheModel();

	@Override
	public FlagStandards toEscapedModel();

	@Override
	public FlagStandards toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}