/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMMeasurementFormulaValue service. Represents a row in the &quot;GEM_MSRMNT_FORMULA_DTL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMMeasurementFormulaValueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMMeasurementFormulaValueImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMMeasurementFormulaValue
 * @see com.ihg.brandstandards.db.model.impl.GEMMeasurementFormulaValueImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMMeasurementFormulaValueModelImpl
 * @generated
 */
public interface GEMMeasurementFormulaValueModel extends BaseModel<GEMMeasurementFormulaValue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m measurement formula value model instance should use the {@link GEMMeasurementFormulaValue} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m measurement formula value.
	 *
	 * @return the primary key of this g e m measurement formula value
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m measurement formula value.
	 *
	 * @param primaryKey the primary key of this g e m measurement formula value
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the formula value ID of this g e m measurement formula value.
	 *
	 * @return the formula value ID of this g e m measurement formula value
	 */
	public long getFormulaValueId();

	/**
	 * Sets the formula value ID of this g e m measurement formula value.
	 *
	 * @param formulaValueId the formula value ID of this g e m measurement formula value
	 */
	public void setFormulaValueId(long formulaValueId);

	/**
	 * Returns the formula ID of this g e m measurement formula value.
	 *
	 * @return the formula ID of this g e m measurement formula value
	 */
	public long getFormulaId();

	/**
	 * Sets the formula ID of this g e m measurement formula value.
	 *
	 * @param formulaId the formula ID of this g e m measurement formula value
	 */
	public void setFormulaId(long formulaId);

	/**
	 * Returns the formula type of this g e m measurement formula value.
	 *
	 * @return the formula type of this g e m measurement formula value
	 */
	@AutoEscape
	public String getFormulaType();

	/**
	 * Sets the formula type of this g e m measurement formula value.
	 *
	 * @param formulaType the formula type of this g e m measurement formula value
	 */
	public void setFormulaType(String formulaType);

	/**
	 * Returns the formula value of this g e m measurement formula value.
	 *
	 * @return the formula value of this g e m measurement formula value
	 */
	@AutoEscape
	public String getFormulaValue();

	/**
	 * Sets the formula value of this g e m measurement formula value.
	 *
	 * @param formulaValue the formula value of this g e m measurement formula value
	 */
	public void setFormulaValue(String formulaValue);

	/**
	 * Returns the creator ID of this g e m measurement formula value.
	 *
	 * @return the creator ID of this g e m measurement formula value
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m measurement formula value.
	 *
	 * @param creatorId the creator ID of this g e m measurement formula value
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m measurement formula value.
	 *
	 * @return the created date of this g e m measurement formula value
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m measurement formula value.
	 *
	 * @param createdDate the created date of this g e m measurement formula value
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m measurement formula value.
	 *
	 * @return the updated by of this g e m measurement formula value
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m measurement formula value.
	 *
	 * @param updatedBy the updated by of this g e m measurement formula value
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m measurement formula value.
	 *
	 * @return the updated date of this g e m measurement formula value
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m measurement formula value.
	 *
	 * @param updatedDate the updated date of this g e m measurement formula value
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMMeasurementFormulaValue gemMeasurementFormulaValue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMMeasurementFormulaValue> toCacheModel();

	@Override
	public GEMMeasurementFormulaValue toEscapedModel();

	@Override
	public GEMMeasurementFormulaValue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}