/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMManagementBucket service. Represents a row in the &quot;GEM_MGT_BUCKET&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMManagementBucketModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMManagementBucketImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMManagementBucket
 * @see com.ihg.brandstandards.db.model.impl.GEMManagementBucketImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMManagementBucketModelImpl
 * @generated
 */
public interface GEMManagementBucketModel extends BaseModel<GEMManagementBucket> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m management bucket model instance should use the {@link GEMManagementBucket} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m management bucket.
	 *
	 * @return the primary key of this g e m management bucket
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m management bucket.
	 *
	 * @param primaryKey the primary key of this g e m management bucket
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bucket ID of this g e m management bucket.
	 *
	 * @return the bucket ID of this g e m management bucket
	 */
	public long getBucketId();

	/**
	 * Sets the bucket ID of this g e m management bucket.
	 *
	 * @param bucketId the bucket ID of this g e m management bucket
	 */
	public void setBucketId(long bucketId);

	/**
	 * Returns the bucket name of this g e m management bucket.
	 *
	 * @return the bucket name of this g e m management bucket
	 */
	@AutoEscape
	public String getBucketName();

	/**
	 * Sets the bucket name of this g e m management bucket.
	 *
	 * @param bucketName the bucket name of this g e m management bucket
	 */
	public void setBucketName(String bucketName);

	/**
	 * Returns the department ID of this g e m management bucket.
	 *
	 * @return the department ID of this g e m management bucket
	 */
	public long getDepartmentId();

	/**
	 * Sets the department ID of this g e m management bucket.
	 *
	 * @param departmentId the department ID of this g e m management bucket
	 */
	public void setDepartmentId(long departmentId);

	/**
	 * Returns the active ind of this g e m management bucket.
	 *
	 * @return the active ind of this g e m management bucket
	 */
	@AutoEscape
	public String getActiveInd();

	/**
	 * Sets the active ind of this g e m management bucket.
	 *
	 * @param activeInd the active ind of this g e m management bucket
	 */
	public void setActiveInd(String activeInd);

	/**
	 * Returns the display order number of this g e m management bucket.
	 *
	 * @return the display order number of this g e m management bucket
	 */
	public long getDisplayOrderNumber();

	/**
	 * Sets the display order number of this g e m management bucket.
	 *
	 * @param displayOrderNumber the display order number of this g e m management bucket
	 */
	public void setDisplayOrderNumber(long displayOrderNumber);

	/**
	 * Returns the bucket code of this g e m management bucket.
	 *
	 * @return the bucket code of this g e m management bucket
	 */
	@AutoEscape
	public String getBucketCode();

	/**
	 * Sets the bucket code of this g e m management bucket.
	 *
	 * @param bucketCode the bucket code of this g e m management bucket
	 */
	public void setBucketCode(String bucketCode);

	/**
	 * Returns the creator ID of this g e m management bucket.
	 *
	 * @return the creator ID of this g e m management bucket
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m management bucket.
	 *
	 * @param creatorId the creator ID of this g e m management bucket
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m management bucket.
	 *
	 * @return the created date of this g e m management bucket
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m management bucket.
	 *
	 * @param createdDate the created date of this g e m management bucket
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m management bucket.
	 *
	 * @return the updated by of this g e m management bucket
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m management bucket.
	 *
	 * @param updatedBy the updated by of this g e m management bucket
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m management bucket.
	 *
	 * @return the updated date of this g e m management bucket
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m management bucket.
	 *
	 * @param updatedDate the updated date of this g e m management bucket
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMManagementBucket gemManagementBucket);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMManagementBucket> toCacheModel();

	@Override
	public GEMManagementBucket toEscapedModel();

	@Override
	public GEMManagementBucket toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}