/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMRole service. Represents a row in the &quot;GEM_GRP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMRoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMRoleImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMRole
 * @see com.ihg.brandstandards.db.model.impl.GEMRoleImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMRoleModelImpl
 * @generated
 */
public interface GEMRoleModel extends BaseModel<GEMRole> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m role model instance should use the {@link GEMRole} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m role.
	 *
	 * @return the primary key of this g e m role
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m role.
	 *
	 * @param primaryKey the primary key of this g e m role
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the gem grp ID of this g e m role.
	 *
	 * @return the gem grp ID of this g e m role
	 */
	public long getGemGrpId();

	/**
	 * Sets the gem grp ID of this g e m role.
	 *
	 * @param gemGrpId the gem grp ID of this g e m role
	 */
	public void setGemGrpId(long gemGrpId);

	/**
	 * Returns the region ID of this g e m role.
	 *
	 * @return the region ID of this g e m role
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this g e m role.
	 *
	 * @param regionId the region ID of this g e m role
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the chain code of this g e m role.
	 *
	 * @return the chain code of this g e m role
	 */
	@AutoEscape
	public String getChainCode();

	/**
	 * Sets the chain code of this g e m role.
	 *
	 * @param chainCode the chain code of this g e m role
	 */
	public void setChainCode(String chainCode);

	/**
	 * Returns the gem grp code of this g e m role.
	 *
	 * @return the gem grp code of this g e m role
	 */
	@AutoEscape
	public String getGemGrpCode();

	/**
	 * Sets the gem grp code of this g e m role.
	 *
	 * @param gemGrpCode the gem grp code of this g e m role
	 */
	public void setGemGrpCode(String gemGrpCode);

	/**
	 * Returns the owner grp ID of this g e m role.
	 *
	 * @return the owner grp ID of this g e m role
	 */
	@AutoEscape
	public String getOwnerGrpId();

	/**
	 * Sets the owner grp ID of this g e m role.
	 *
	 * @param ownerGrpId the owner grp ID of this g e m role
	 */
	public void setOwnerGrpId(String ownerGrpId);

	/**
	 * Returns the owner grp name of this g e m role.
	 *
	 * @return the owner grp name of this g e m role
	 */
	@AutoEscape
	public String getOwnerGrpName();

	/**
	 * Sets the owner grp name of this g e m role.
	 *
	 * @param ownerGrpName the owner grp name of this g e m role
	 */
	public void setOwnerGrpName(String ownerGrpName);

	/**
	 * Returns the bus owner name of this g e m role.
	 *
	 * @return the bus owner name of this g e m role
	 */
	@AutoEscape
	public String getBusOwnerName();

	/**
	 * Sets the bus owner name of this g e m role.
	 *
	 * @param busOwnerName the bus owner name of this g e m role
	 */
	public void setBusOwnerName(String busOwnerName);

	/**
	 * Returns the deligate1 name of this g e m role.
	 *
	 * @return the deligate1 name of this g e m role
	 */
	@AutoEscape
	public String getDeligate1Name();

	/**
	 * Sets the deligate1 name of this g e m role.
	 *
	 * @param deligate1Name the deligate1 name of this g e m role
	 */
	public void setDeligate1Name(String deligate1Name);

	/**
	 * Returns the deligate2 name of this g e m role.
	 *
	 * @return the deligate2 name of this g e m role
	 */
	@AutoEscape
	public String getDeligate2Name();

	/**
	 * Sets the deligate2 name of this g e m role.
	 *
	 * @param deligate2Name the deligate2 name of this g e m role
	 */
	public void setDeligate2Name(String deligate2Name);

	/**
	 * Returns the creator ID of this g e m role.
	 *
	 * @return the creator ID of this g e m role
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m role.
	 *
	 * @param creatorId the creator ID of this g e m role
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m role.
	 *
	 * @return the created date of this g e m role
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m role.
	 *
	 * @param createdDate the created date of this g e m role
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m role.
	 *
	 * @return the updated by of this g e m role
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m role.
	 *
	 * @param updatedBy the updated by of this g e m role
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m role.
	 *
	 * @return the updated date of this g e m role
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m role.
	 *
	 * @param updatedDate the updated date of this g e m role
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMRole gemRole);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMRole> toCacheModel();

	@Override
	public GEMRole toEscapedModel();

	@Override
	public GEMRole toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}