/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMTemplateReference service. Represents a row in the &quot;GEM_PUB_REF_TEMPLATE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMTemplateReferenceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMTemplateReferenceImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMTemplateReference
 * @see com.ihg.brandstandards.db.model.impl.GEMTemplateReferenceImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMTemplateReferenceModelImpl
 * @generated
 */
public interface GEMTemplateReferenceModel extends BaseModel<GEMTemplateReference> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m template reference model instance should use the {@link GEMTemplateReference} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m template reference.
	 *
	 * @return the primary key of this g e m template reference
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m template reference.
	 *
	 * @param primaryKey the primary key of this g e m template reference
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the template ref ID of this g e m template reference.
	 *
	 * @return the template ref ID of this g e m template reference
	 */
	public long getTemplateRefId();

	/**
	 * Sets the template ref ID of this g e m template reference.
	 *
	 * @param templateRefId the template ref ID of this g e m template reference
	 */
	public void setTemplateRefId(long templateRefId);

	/**
	 * Returns the template ID of this g e m template reference.
	 *
	 * @return the template ID of this g e m template reference
	 */
	public long getTemplateId();

	/**
	 * Sets the template ID of this g e m template reference.
	 *
	 * @param templateId the template ID of this g e m template reference
	 */
	public void setTemplateId(long templateId);

	/**
	 * Returns the publish dept ID of this g e m template reference.
	 *
	 * @return the publish dept ID of this g e m template reference
	 */
	public long getPublishDeptId();

	/**
	 * Sets the publish dept ID of this g e m template reference.
	 *
	 * @param publishDeptId the publish dept ID of this g e m template reference
	 */
	public void setPublishDeptId(long publishDeptId);

	/**
	 * Returns the region ID of this g e m template reference.
	 *
	 * @return the region ID of this g e m template reference
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this g e m template reference.
	 *
	 * @param regionId the region ID of this g e m template reference
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the creator ID of this g e m template reference.
	 *
	 * @return the creator ID of this g e m template reference
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m template reference.
	 *
	 * @param creatorId the creator ID of this g e m template reference
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m template reference.
	 *
	 * @return the created date of this g e m template reference
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m template reference.
	 *
	 * @param createdDate the created date of this g e m template reference
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m template reference.
	 *
	 * @return the updated by of this g e m template reference
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m template reference.
	 *
	 * @param updatedBy the updated by of this g e m template reference
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m template reference.
	 *
	 * @return the updated date of this g e m template reference
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m template reference.
	 *
	 * @param updatedDate the updated date of this g e m template reference
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMTemplateReference gemTemplateReference);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMTemplateReference> toCacheModel();

	@Override
	public GEMTemplateReference toEscapedModel();

	@Override
	public GEMTemplateReference toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}