/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Image service. Represents a row in the &quot;IMAGE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.ImageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.ImageImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see Image
 * @see com.ihg.brandstandards.db.model.impl.ImageImpl
 * @see com.ihg.brandstandards.db.model.impl.ImageModelImpl
 * @generated
 */
public interface ImageModel extends BaseModel<Image> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a image model instance should use the {@link Image} interface instead.
	 */

	/**
	 * Returns the primary key of this image.
	 *
	 * @return the primary key of this image
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this image.
	 *
	 * @param primaryKey the primary key of this image
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the image ID of this image.
	 *
	 * @return the image ID of this image
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this image.
	 *
	 * @param imageId the image ID of this image
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the image uu ID of this image.
	 *
	 * @return the image uu ID of this image
	 */
	@AutoEscape
	public String getImageUuId();

	/**
	 * Sets the image uu ID of this image.
	 *
	 * @param imageUuId the image uu ID of this image
	 */
	public void setImageUuId(String imageUuId);

	/**
	 * Returns the image desc of this image.
	 *
	 * @return the image desc of this image
	 */
	@AutoEscape
	public String getImageDesc();

	/**
	 * Sets the image desc of this image.
	 *
	 * @param imageDesc the image desc of this image
	 */
	public void setImageDesc(String imageDesc);

	/**
	 * Returns the image title of this image.
	 *
	 * @return the image title of this image
	 */
	@AutoEscape
	public String getImageTitle();

	/**
	 * Sets the image title of this image.
	 *
	 * @param imageTitle the image title of this image
	 */
	public void setImageTitle(String imageTitle);

	/**
	 * Returns the image size of this image.
	 *
	 * @return the image size of this image
	 */
	@AutoEscape
	public String getImageSize();

	/**
	 * Sets the image size of this image.
	 *
	 * @param imageSize the image size of this image
	 */
	public void setImageSize(String imageSize);

	/**
	 * Returns the image type of this image.
	 *
	 * @return the image type of this image
	 */
	@AutoEscape
	public String getImageType();

	/**
	 * Sets the image type of this image.
	 *
	 * @param imageType the image type of this image
	 */
	public void setImageType(String imageType);

	/**
	 * Returns the small image ID of this image.
	 *
	 * @return the small image ID of this image
	 */
	@AutoEscape
	public String getSmallImageId();

	/**
	 * Sets the small image ID of this image.
	 *
	 * @param smallImageId the small image ID of this image
	 */
	public void setSmallImageId(String smallImageId);

	/**
	 * Returns the image dimension of this image.
	 *
	 * @return the image dimension of this image
	 */
	@AutoEscape
	public String getImageDimension();

	/**
	 * Sets the image dimension of this image.
	 *
	 * @param imageDimension the image dimension of this image
	 */
	public void setImageDimension(String imageDimension);

	/**
	 * Returns the creator ID of this image.
	 *
	 * @return the creator ID of this image
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this image.
	 *
	 * @param creatorId the creator ID of this image
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this image.
	 *
	 * @return the created date of this image
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this image.
	 *
	 * @param createdDate the created date of this image
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this image.
	 *
	 * @return the updated by of this image
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this image.
	 *
	 * @param updatedBy the updated by of this image
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this image.
	 *
	 * @return the updated date of this image
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this image.
	 *
	 * @param updatedDate the updated date of this image
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Image image);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Image> toCacheModel();

	@Override
	public Image toEscapedModel();

	@Override
	public Image toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}