/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PublishedPdfList service. Represents a row in the &quot;PUBLISHED_PDF_LIST&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.PublishedPdfListModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.PublishedPdfListImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see PublishedPdfList
 * @see com.ihg.brandstandards.db.model.impl.PublishedPdfListImpl
 * @see com.ihg.brandstandards.db.model.impl.PublishedPdfListModelImpl
 * @generated
 */
public interface PublishedPdfListModel extends BaseModel<PublishedPdfList> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a published pdf list model instance should use the {@link PublishedPdfList} interface instead.
	 */

	/**
	 * Returns the primary key of this published pdf list.
	 *
	 * @return the primary key of this published pdf list
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this published pdf list.
	 *
	 * @param primaryKey the primary key of this published pdf list
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the pdf ID of this published pdf list.
	 *
	 * @return the pdf ID of this published pdf list
	 */
	public long getPdfId();

	/**
	 * Sets the pdf ID of this published pdf list.
	 *
	 * @param pdfId the pdf ID of this published pdf list
	 */
	public void setPdfId(long pdfId);

	/**
	 * Returns the pdf chain code of this published pdf list.
	 *
	 * @return the pdf chain code of this published pdf list
	 */
	@AutoEscape
	public String getPdfChainCode();

	/**
	 * Sets the pdf chain code of this published pdf list.
	 *
	 * @param pdfChainCode the pdf chain code of this published pdf list
	 */
	public void setPdfChainCode(String pdfChainCode);

	/**
	 * Returns the pdf ctry code of this published pdf list.
	 *
	 * @return the pdf ctry code of this published pdf list
	 */
	@AutoEscape
	public String getPdfCtryCode();

	/**
	 * Sets the pdf ctry code of this published pdf list.
	 *
	 * @param pdfCtryCode the pdf ctry code of this published pdf list
	 */
	public void setPdfCtryCode(String pdfCtryCode);

	/**
	 * Returns the pdf build type of this published pdf list.
	 *
	 * @return the pdf build type of this published pdf list
	 */
	@AutoEscape
	public String getPdfBuildType();

	/**
	 * Sets the pdf build type of this published pdf list.
	 *
	 * @param pdfBuildType the pdf build type of this published pdf list
	 */
	public void setPdfBuildType(String pdfBuildType);

	/**
	 * Returns the pdf year number of this published pdf list.
	 *
	 * @return the pdf year number of this published pdf list
	 */
	public int getPdfYearNumber();

	/**
	 * Sets the pdf year number of this published pdf list.
	 *
	 * @param pdfYearNumber the pdf year number of this published pdf list
	 */
	public void setPdfYearNumber(int pdfYearNumber);

	/**
	 * Returns the pdf locale code of this published pdf list.
	 *
	 * @return the pdf locale code of this published pdf list
	 */
	@AutoEscape
	public String getPdfLocaleCode();

	/**
	 * Sets the pdf locale code of this published pdf list.
	 *
	 * @param pdfLocaleCode the pdf locale code of this published pdf list
	 */
	public void setPdfLocaleCode(String pdfLocaleCode);

	/**
	 * Returns the pdf version number of this published pdf list.
	 *
	 * @return the pdf version number of this published pdf list
	 */
	public long getPdfVersionNumber();

	/**
	 * Sets the pdf version number of this published pdf list.
	 *
	 * @param pdfVersionNumber the pdf version number of this published pdf list
	 */
	public void setPdfVersionNumber(long pdfVersionNumber);

	/**
	 * Returns the pdf file name of this published pdf list.
	 *
	 * @return the pdf file name of this published pdf list
	 */
	@AutoEscape
	public String getPdfFileName();

	/**
	 * Sets the pdf file name of this published pdf list.
	 *
	 * @param pdfFileName the pdf file name of this published pdf list
	 */
	public void setPdfFileName(String pdfFileName);

	/**
	 * Returns the pdf file u r l text of this published pdf list.
	 *
	 * @return the pdf file u r l text of this published pdf list
	 */
	@AutoEscape
	public String getPdfFileURLText();

	/**
	 * Sets the pdf file u r l text of this published pdf list.
	 *
	 * @param pdfFileURLText the pdf file u r l text of this published pdf list
	 */
	public void setPdfFileURLText(String pdfFileURLText);

	/**
	 * Returns the publish ID of this published pdf list.
	 *
	 * @return the publish ID of this published pdf list
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this published pdf list.
	 *
	 * @param publishId the publish ID of this published pdf list
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the page size orientation type of this published pdf list.
	 *
	 * @return the page size orientation type of this published pdf list
	 */
	@AutoEscape
	public String getPageSizeOrientationType();

	/**
	 * Sets the page size orientation type of this published pdf list.
	 *
	 * @param pageSizeOrientationType the page size orientation type of this published pdf list
	 */
	public void setPageSizeOrientationType(String pageSizeOrientationType);

	/**
	 * Returns the created by of this published pdf list.
	 *
	 * @return the created by of this published pdf list
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this published pdf list.
	 *
	 * @param createdBy the created by of this published pdf list
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the created date of this published pdf list.
	 *
	 * @return the created date of this published pdf list
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this published pdf list.
	 *
	 * @param createdDate the created date of this published pdf list
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this published pdf list.
	 *
	 * @return the updated by of this published pdf list
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this published pdf list.
	 *
	 * @param updatedBy the updated by of this published pdf list
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this published pdf list.
	 *
	 * @return the updated date of this published pdf list
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this published pdf list.
	 *
	 * @param updatedDate the updated date of this published pdf list
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PublishedPdfList publishedPdfList);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PublishedPdfList> toCacheModel();

	@Override
	public PublishedPdfList toEscapedModel();

	@Override
	public PublishedPdfList toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}