/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsCountry service. Represents a row in the &quot;BRNDSTND_CTRY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsCountryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsCountryImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsCountry
 * @see com.ihg.brandstandards.db.model.impl.StandardsCountryImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsCountryModelImpl
 * @generated
 */
public interface StandardsCountryModel extends BaseModel<StandardsCountry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards country model instance should use the {@link StandardsCountry} interface instead.
	 */

	/**
	 * Returns the primary key of this standards country.
	 *
	 * @return the primary key of this standards country
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this standards country.
	 *
	 * @param primaryKey the primary key of this standards country
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the country name code of this standards country.
	 *
	 * @return the country name code of this standards country
	 */
	@AutoEscape
	public String getCountryNameCode();

	/**
	 * Sets the country name code of this standards country.
	 *
	 * @param countryNameCode the country name code of this standards country
	 */
	public void setCountryNameCode(String countryNameCode);

	/**
	 * Returns the region ID of this standards country.
	 *
	 * @return the region ID of this standards country
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this standards country.
	 *
	 * @param regionId the region ID of this standards country
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the creator ID of this standards country.
	 *
	 * @return the creator ID of this standards country
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards country.
	 *
	 * @param creatorId the creator ID of this standards country
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards country.
	 *
	 * @return the created date of this standards country
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards country.
	 *
	 * @param createdDate the created date of this standards country
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards country.
	 *
	 * @return the updated by of this standards country
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards country.
	 *
	 * @param updatedBy the updated by of this standards country
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards country.
	 *
	 * @return the updated date of this standards country
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards country.
	 *
	 * @param updatedDate the updated date of this standards country
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the sub region ID of this standards country.
	 *
	 * @return the sub region ID of this standards country
	 */
	public long getSubRegionId();

	/**
	 * Sets the sub region ID of this standards country.
	 *
	 * @param subRegionId the sub region ID of this standards country
	 */
	public void setSubRegionId(long subRegionId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsCountry standardsCountry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsCountry> toCacheModel();

	@Override
	public StandardsCountry toEscapedModel();

	@Override
	public StandardsCountry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}