/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.ChainAttachmentsStandards;
import com.ihg.brandstandards.db.model.ChainAttachmentsStandardsModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ChainAttachmentsStandards service. Represents a row in the &quot;STD_ATTACHMENT_CHAIN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.ChainAttachmentsStandardsModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChainAttachmentsStandardsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see ChainAttachmentsStandardsImpl
 * @see com.ihg.brandstandards.db.model.ChainAttachmentsStandards
 * @see com.ihg.brandstandards.db.model.ChainAttachmentsStandardsModel
 * @generated
 */
public class ChainAttachmentsStandardsModelImpl extends BaseModelImpl<ChainAttachmentsStandards>
	implements ChainAttachmentsStandardsModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a chain attachments standards model instance should use the {@link com.ihg.brandstandards.db.model.ChainAttachmentsStandards} interface instead.
	 */
	public static final String TABLE_NAME = "STD_ATTACHMENT_CHAIN";
	public static final Object[][] TABLE_COLUMNS = {
			{ "STD_ATTACHMENT_CHAIN_ID", Types.BIGINT },
			{ "STD_ATTACHEMENT_ID", Types.BIGINT },
			{ "LOCALE_CD", Types.VARCHAR },
			{ "CHAIN_CD", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table STD_ATTACHMENT_CHAIN (STD_ATTACHMENT_CHAIN_ID LONG not null primary key,STD_ATTACHEMENT_ID LONG,LOCALE_CD VARCHAR(75) null,CHAIN_CD VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table STD_ATTACHMENT_CHAIN";
	public static final String ORDER_BY_JPQL = " ORDER BY chainAttachmentsStandards.chainAttachmentId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY STD_ATTACHMENT_CHAIN.STD_ATTACHMENT_CHAIN_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.ChainAttachmentsStandards"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.ChainAttachmentsStandards"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.ChainAttachmentsStandards"),
			true);
	public static long ATTACHMENTID_COLUMN_BITMASK = 1L;
	public static long CHAINATTACHMENTID_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.ChainAttachmentsStandards"));

	public ChainAttachmentsStandardsModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _chainAttachmentId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setChainAttachmentId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _chainAttachmentId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChainAttachmentsStandards.class;
	}

	@Override
	public String getModelClassName() {
		return ChainAttachmentsStandards.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("chainAttachmentId", getChainAttachmentId());
		attributes.put("attachmentId", getAttachmentId());
		attributes.put("localeCode", getLocaleCode());
		attributes.put("chainCode", getChainCode());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long chainAttachmentId = (Long)attributes.get("chainAttachmentId");

		if (chainAttachmentId != null) {
			setChainAttachmentId(chainAttachmentId);
		}

		Long attachmentId = (Long)attributes.get("attachmentId");

		if (attachmentId != null) {
			setAttachmentId(attachmentId);
		}

		String localeCode = (String)attributes.get("localeCode");

		if (localeCode != null) {
			setLocaleCode(localeCode);
		}

		String chainCode = (String)attributes.get("chainCode");

		if (chainCode != null) {
			setChainCode(chainCode);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getChainAttachmentId() {
		return _chainAttachmentId;
	}

	@Override
	public void setChainAttachmentId(long chainAttachmentId) {
		_chainAttachmentId = chainAttachmentId;
	}

	@Override
	public long getAttachmentId() {
		return _attachmentId;
	}

	@Override
	public void setAttachmentId(long attachmentId) {
		_columnBitmask |= ATTACHMENTID_COLUMN_BITMASK;

		if (!_setOriginalAttachmentId) {
			_setOriginalAttachmentId = true;

			_originalAttachmentId = _attachmentId;
		}

		_attachmentId = attachmentId;
	}

	public long getOriginalAttachmentId() {
		return _originalAttachmentId;
	}

	@Override
	public String getLocaleCode() {
		if (_localeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _localeCode;
		}
	}

	@Override
	public void setLocaleCode(String localeCode) {
		_localeCode = localeCode;
	}

	@Override
	public String getChainCode() {
		if (_chainCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _chainCode;
		}
	}

	@Override
	public void setChainCode(String chainCode) {
		_chainCode = chainCode;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ChainAttachmentsStandards.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChainAttachmentsStandards toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ChainAttachmentsStandards)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChainAttachmentsStandardsImpl chainAttachmentsStandardsImpl = new ChainAttachmentsStandardsImpl();

		chainAttachmentsStandardsImpl.setChainAttachmentId(getChainAttachmentId());
		chainAttachmentsStandardsImpl.setAttachmentId(getAttachmentId());
		chainAttachmentsStandardsImpl.setLocaleCode(getLocaleCode());
		chainAttachmentsStandardsImpl.setChainCode(getChainCode());
		chainAttachmentsStandardsImpl.setCreatorId(getCreatorId());
		chainAttachmentsStandardsImpl.setCreatedDate(getCreatedDate());
		chainAttachmentsStandardsImpl.setUpdatedBy(getUpdatedBy());
		chainAttachmentsStandardsImpl.setUpdatedDate(getUpdatedDate());

		chainAttachmentsStandardsImpl.resetOriginalValues();

		return chainAttachmentsStandardsImpl;
	}

	@Override
	public int compareTo(ChainAttachmentsStandards chainAttachmentsStandards) {
		long primaryKey = chainAttachmentsStandards.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ChainAttachmentsStandards)) {
			return false;
		}

		ChainAttachmentsStandards chainAttachmentsStandards = (ChainAttachmentsStandards)obj;

		long primaryKey = chainAttachmentsStandards.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		ChainAttachmentsStandardsModelImpl chainAttachmentsStandardsModelImpl = this;

		chainAttachmentsStandardsModelImpl._originalAttachmentId = chainAttachmentsStandardsModelImpl._attachmentId;

		chainAttachmentsStandardsModelImpl._setOriginalAttachmentId = false;

		chainAttachmentsStandardsModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChainAttachmentsStandards> toCacheModel() {
		ChainAttachmentsStandardsCacheModel chainAttachmentsStandardsCacheModel = new ChainAttachmentsStandardsCacheModel();

		chainAttachmentsStandardsCacheModel.chainAttachmentId = getChainAttachmentId();

		chainAttachmentsStandardsCacheModel.attachmentId = getAttachmentId();

		chainAttachmentsStandardsCacheModel.localeCode = getLocaleCode();

		String localeCode = chainAttachmentsStandardsCacheModel.localeCode;

		if ((localeCode != null) && (localeCode.length() == 0)) {
			chainAttachmentsStandardsCacheModel.localeCode = null;
		}

		chainAttachmentsStandardsCacheModel.chainCode = getChainCode();

		String chainCode = chainAttachmentsStandardsCacheModel.chainCode;

		if ((chainCode != null) && (chainCode.length() == 0)) {
			chainAttachmentsStandardsCacheModel.chainCode = null;
		}

		chainAttachmentsStandardsCacheModel.creatorId = getCreatorId();

		String creatorId = chainAttachmentsStandardsCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			chainAttachmentsStandardsCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			chainAttachmentsStandardsCacheModel.createdDate = createdDate.getTime();
		}
		else {
			chainAttachmentsStandardsCacheModel.createdDate = Long.MIN_VALUE;
		}

		chainAttachmentsStandardsCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = chainAttachmentsStandardsCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			chainAttachmentsStandardsCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			chainAttachmentsStandardsCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			chainAttachmentsStandardsCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return chainAttachmentsStandardsCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{chainAttachmentId=");
		sb.append(getChainAttachmentId());
		sb.append(", attachmentId=");
		sb.append(getAttachmentId());
		sb.append(", localeCode=");
		sb.append(getLocaleCode());
		sb.append(", chainCode=");
		sb.append(getChainCode());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.ChainAttachmentsStandards");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>chainAttachmentId</column-name><column-value><![CDATA[");
		sb.append(getChainAttachmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>attachmentId</column-name><column-value><![CDATA[");
		sb.append(getAttachmentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>localeCode</column-name><column-value><![CDATA[");
		sb.append(getLocaleCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>chainCode</column-name><column-value><![CDATA[");
		sb.append(getChainCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = ChainAttachmentsStandards.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			ChainAttachmentsStandards.class
		};
	private long _chainAttachmentId;
	private long _attachmentId;
	private long _originalAttachmentId;
	private boolean _setOriginalAttachmentId;
	private String _localeCode;
	private String _chainCode;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private ChainAttachmentsStandards _escapedModel;
}