/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.GEMUniqueGroup;
import com.ihg.brandstandards.db.model.GEMUniqueGroupModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the GEMUniqueGroup service. Represents a row in the &quot;GEM_UNIQUE_GRP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.GEMUniqueGroupModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GEMUniqueGroupImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMUniqueGroupImpl
 * @see com.ihg.brandstandards.db.model.GEMUniqueGroup
 * @see com.ihg.brandstandards.db.model.GEMUniqueGroupModel
 * @generated
 */
public class GEMUniqueGroupModelImpl extends BaseModelImpl<GEMUniqueGroup>
	implements GEMUniqueGroupModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a g e m unique group model instance should use the {@link com.ihg.brandstandards.db.model.GEMUniqueGroup} interface instead.
	 */
	public static final String TABLE_NAME = "GEM_UNIQUE_GRP";
	public static final Object[][] TABLE_COLUMNS = {
			{ "GEM_UNIQUE_GRP_ID", Types.BIGINT },
			{ "GEM_PUBLISH_DEPT_ID", Types.BIGINT },
			{ "PUBLISH_ID", Types.BIGINT },
			{ "GEM_GRP_NM", Types.VARCHAR },
			{ "RGN_ID", Types.BIGINT },
			{ "GEM_PLCY_ID", Types.VARCHAR },
			{ "GEM_LVL_ID", Types.VARCHAR },
			{ "GRP_TYP", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table GEM_UNIQUE_GRP (GEM_UNIQUE_GRP_ID LONG not null primary key,GEM_PUBLISH_DEPT_ID LONG,PUBLISH_ID LONG,GEM_GRP_NM VARCHAR(75) null,RGN_ID LONG,GEM_PLCY_ID VARCHAR(75) null,GEM_LVL_ID VARCHAR(75) null,GRP_TYP VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table GEM_UNIQUE_GRP";
	public static final String ORDER_BY_JPQL = " ORDER BY gemUniqueGroup.uniqueGroupId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GEM_UNIQUE_GRP.GEM_UNIQUE_GRP_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.GEMUniqueGroup"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.GEMUniqueGroup"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.ihg.brandstandards.db.model.GEMUniqueGroup"),
			true);
	public static long GROUPTYPE_COLUMN_BITMASK = 1L;
	public static long PUBLISHID_COLUMN_BITMASK = 2L;
	public static long REGIONID_COLUMN_BITMASK = 4L;
	public static long UNIQUEGROUPID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.GEMUniqueGroup"));

	public GEMUniqueGroupModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _uniqueGroupId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setUniqueGroupId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _uniqueGroupId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return GEMUniqueGroup.class;
	}

	@Override
	public String getModelClassName() {
		return GEMUniqueGroup.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uniqueGroupId", getUniqueGroupId());
		attributes.put("publishDeptId", getPublishDeptId());
		attributes.put("publishId", getPublishId());
		attributes.put("groupName", getGroupName());
		attributes.put("regionId", getRegionId());
		attributes.put("policyId", getPolicyId());
		attributes.put("levelId", getLevelId());
		attributes.put("groupType", getGroupType());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long uniqueGroupId = (Long)attributes.get("uniqueGroupId");

		if (uniqueGroupId != null) {
			setUniqueGroupId(uniqueGroupId);
		}

		Long publishDeptId = (Long)attributes.get("publishDeptId");

		if (publishDeptId != null) {
			setPublishDeptId(publishDeptId);
		}

		Long publishId = (Long)attributes.get("publishId");

		if (publishId != null) {
			setPublishId(publishId);
		}

		String groupName = (String)attributes.get("groupName");

		if (groupName != null) {
			setGroupName(groupName);
		}

		Long regionId = (Long)attributes.get("regionId");

		if (regionId != null) {
			setRegionId(regionId);
		}

		String policyId = (String)attributes.get("policyId");

		if (policyId != null) {
			setPolicyId(policyId);
		}

		String levelId = (String)attributes.get("levelId");

		if (levelId != null) {
			setLevelId(levelId);
		}

		String groupType = (String)attributes.get("groupType");

		if (groupType != null) {
			setGroupType(groupType);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getUniqueGroupId() {
		return _uniqueGroupId;
	}

	@Override
	public void setUniqueGroupId(long uniqueGroupId) {
		_uniqueGroupId = uniqueGroupId;
	}

	@Override
	public long getPublishDeptId() {
		return _publishDeptId;
	}

	@Override
	public void setPublishDeptId(long publishDeptId) {
		_publishDeptId = publishDeptId;
	}

	@Override
	public long getPublishId() {
		return _publishId;
	}

	@Override
	public void setPublishId(long publishId) {
		_columnBitmask |= PUBLISHID_COLUMN_BITMASK;

		if (!_setOriginalPublishId) {
			_setOriginalPublishId = true;

			_originalPublishId = _publishId;
		}

		_publishId = publishId;
	}

	public long getOriginalPublishId() {
		return _originalPublishId;
	}

	@Override
	public String getGroupName() {
		if (_groupName == null) {
			return StringPool.BLANK;
		}
		else {
			return _groupName;
		}
	}

	@Override
	public void setGroupName(String groupName) {
		_groupName = groupName;
	}

	@Override
	public long getRegionId() {
		return _regionId;
	}

	@Override
	public void setRegionId(long regionId) {
		_columnBitmask |= REGIONID_COLUMN_BITMASK;

		if (!_setOriginalRegionId) {
			_setOriginalRegionId = true;

			_originalRegionId = _regionId;
		}

		_regionId = regionId;
	}

	public long getOriginalRegionId() {
		return _originalRegionId;
	}

	@Override
	public String getPolicyId() {
		if (_policyId == null) {
			return StringPool.BLANK;
		}
		else {
			return _policyId;
		}
	}

	@Override
	public void setPolicyId(String policyId) {
		_policyId = policyId;
	}

	@Override
	public String getLevelId() {
		if (_levelId == null) {
			return StringPool.BLANK;
		}
		else {
			return _levelId;
		}
	}

	@Override
	public void setLevelId(String levelId) {
		_levelId = levelId;
	}

	@Override
	public String getGroupType() {
		if (_groupType == null) {
			return StringPool.BLANK;
		}
		else {
			return _groupType;
		}
	}

	@Override
	public void setGroupType(String groupType) {
		_columnBitmask |= GROUPTYPE_COLUMN_BITMASK;

		if (_originalGroupType == null) {
			_originalGroupType = _groupType;
		}

		_groupType = groupType;
	}

	public String getOriginalGroupType() {
		return GetterUtil.getString(_originalGroupType);
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			GEMUniqueGroup.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public GEMUniqueGroup toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (GEMUniqueGroup)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		GEMUniqueGroupImpl gemUniqueGroupImpl = new GEMUniqueGroupImpl();

		gemUniqueGroupImpl.setUniqueGroupId(getUniqueGroupId());
		gemUniqueGroupImpl.setPublishDeptId(getPublishDeptId());
		gemUniqueGroupImpl.setPublishId(getPublishId());
		gemUniqueGroupImpl.setGroupName(getGroupName());
		gemUniqueGroupImpl.setRegionId(getRegionId());
		gemUniqueGroupImpl.setPolicyId(getPolicyId());
		gemUniqueGroupImpl.setLevelId(getLevelId());
		gemUniqueGroupImpl.setGroupType(getGroupType());
		gemUniqueGroupImpl.setCreatorId(getCreatorId());
		gemUniqueGroupImpl.setCreatedDate(getCreatedDate());
		gemUniqueGroupImpl.setUpdatedBy(getUpdatedBy());
		gemUniqueGroupImpl.setUpdatedDate(getUpdatedDate());

		gemUniqueGroupImpl.resetOriginalValues();

		return gemUniqueGroupImpl;
	}

	@Override
	public int compareTo(GEMUniqueGroup gemUniqueGroup) {
		long primaryKey = gemUniqueGroup.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof GEMUniqueGroup)) {
			return false;
		}

		GEMUniqueGroup gemUniqueGroup = (GEMUniqueGroup)obj;

		long primaryKey = gemUniqueGroup.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		GEMUniqueGroupModelImpl gemUniqueGroupModelImpl = this;

		gemUniqueGroupModelImpl._originalPublishId = gemUniqueGroupModelImpl._publishId;

		gemUniqueGroupModelImpl._setOriginalPublishId = false;

		gemUniqueGroupModelImpl._originalRegionId = gemUniqueGroupModelImpl._regionId;

		gemUniqueGroupModelImpl._setOriginalRegionId = false;

		gemUniqueGroupModelImpl._originalGroupType = gemUniqueGroupModelImpl._groupType;

		gemUniqueGroupModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<GEMUniqueGroup> toCacheModel() {
		GEMUniqueGroupCacheModel gemUniqueGroupCacheModel = new GEMUniqueGroupCacheModel();

		gemUniqueGroupCacheModel.uniqueGroupId = getUniqueGroupId();

		gemUniqueGroupCacheModel.publishDeptId = getPublishDeptId();

		gemUniqueGroupCacheModel.publishId = getPublishId();

		gemUniqueGroupCacheModel.groupName = getGroupName();

		String groupName = gemUniqueGroupCacheModel.groupName;

		if ((groupName != null) && (groupName.length() == 0)) {
			gemUniqueGroupCacheModel.groupName = null;
		}

		gemUniqueGroupCacheModel.regionId = getRegionId();

		gemUniqueGroupCacheModel.policyId = getPolicyId();

		String policyId = gemUniqueGroupCacheModel.policyId;

		if ((policyId != null) && (policyId.length() == 0)) {
			gemUniqueGroupCacheModel.policyId = null;
		}

		gemUniqueGroupCacheModel.levelId = getLevelId();

		String levelId = gemUniqueGroupCacheModel.levelId;

		if ((levelId != null) && (levelId.length() == 0)) {
			gemUniqueGroupCacheModel.levelId = null;
		}

		gemUniqueGroupCacheModel.groupType = getGroupType();

		String groupType = gemUniqueGroupCacheModel.groupType;

		if ((groupType != null) && (groupType.length() == 0)) {
			gemUniqueGroupCacheModel.groupType = null;
		}

		gemUniqueGroupCacheModel.creatorId = getCreatorId();

		String creatorId = gemUniqueGroupCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			gemUniqueGroupCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			gemUniqueGroupCacheModel.createdDate = createdDate.getTime();
		}
		else {
			gemUniqueGroupCacheModel.createdDate = Long.MIN_VALUE;
		}

		gemUniqueGroupCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = gemUniqueGroupCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			gemUniqueGroupCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			gemUniqueGroupCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			gemUniqueGroupCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return gemUniqueGroupCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(25);

		sb.append("{uniqueGroupId=");
		sb.append(getUniqueGroupId());
		sb.append(", publishDeptId=");
		sb.append(getPublishDeptId());
		sb.append(", publishId=");
		sb.append(getPublishId());
		sb.append(", groupName=");
		sb.append(getGroupName());
		sb.append(", regionId=");
		sb.append(getRegionId());
		sb.append(", policyId=");
		sb.append(getPolicyId());
		sb.append(", levelId=");
		sb.append(getLevelId());
		sb.append(", groupType=");
		sb.append(getGroupType());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(40);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.GEMUniqueGroup");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uniqueGroupId</column-name><column-value><![CDATA[");
		sb.append(getUniqueGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publishDeptId</column-name><column-value><![CDATA[");
		sb.append(getPublishDeptId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>publishId</column-name><column-value><![CDATA[");
		sb.append(getPublishId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupName</column-name><column-value><![CDATA[");
		sb.append(getGroupName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>regionId</column-name><column-value><![CDATA[");
		sb.append(getRegionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>policyId</column-name><column-value><![CDATA[");
		sb.append(getPolicyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>levelId</column-name><column-value><![CDATA[");
		sb.append(getLevelId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupType</column-name><column-value><![CDATA[");
		sb.append(getGroupType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = GEMUniqueGroup.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			GEMUniqueGroup.class
		};
	private long _uniqueGroupId;
	private long _publishDeptId;
	private long _publishId;
	private long _originalPublishId;
	private boolean _setOriginalPublishId;
	private String _groupName;
	private long _regionId;
	private long _originalRegionId;
	private boolean _setOriginalRegionId;
	private String _policyId;
	private String _levelId;
	private String _groupType;
	private String _originalGroupType;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private long _columnBitmask;
	private GEMUniqueGroup _escapedModel;
}