/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.TaxonomyTranslate;
import com.ihg.brandstandards.db.model.TaxonomyTranslateModel;
import com.ihg.brandstandards.db.service.persistence.TaxonomyTranslatePK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the TaxonomyTranslate service. Represents a row in the &quot;TAXONOMY_XLAT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.TaxonomyTranslateModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TaxonomyTranslateImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see TaxonomyTranslateImpl
 * @see com.ihg.brandstandards.db.model.TaxonomyTranslate
 * @see com.ihg.brandstandards.db.model.TaxonomyTranslateModel
 * @generated
 */
public class TaxonomyTranslateModelImpl extends BaseModelImpl<TaxonomyTranslate>
	implements TaxonomyTranslateModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a taxonomy translate model instance should use the {@link com.ihg.brandstandards.db.model.TaxonomyTranslate} interface instead.
	 */
	public static final String TABLE_NAME = "TAXONOMY_XLAT";
	public static final Object[][] TABLE_COLUMNS = {
			{ "TAXONOMY_ID", Types.BIGINT },
			{ "LOCALE_CD", Types.VARCHAR },
			{ "TITLE_TXT", Types.VARCHAR },
			{ "TAXONOMY_DESC", Types.VARCHAR },
			{ "IMAGE_PATH_TXT", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table TAXONOMY_XLAT (TAXONOMY_ID LONG not null,LOCALE_CD VARCHAR(75) not null,TITLE_TXT VARCHAR(75) null,TAXONOMY_DESC VARCHAR(75) null,IMAGE_PATH_TXT VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null,primary key (TAXONOMY_ID, LOCALE_CD))";
	public static final String TABLE_SQL_DROP = "drop table TAXONOMY_XLAT";
	public static final String ORDER_BY_JPQL = " ORDER BY taxonomyTranslate.id.taxId ASC, taxonomyTranslate.id.localeCode ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TAXONOMY_XLAT.TAXONOMY_ID ASC, TAXONOMY_XLAT.LOCALE_CD ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.TaxonomyTranslate"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.TaxonomyTranslate"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.TaxonomyTranslate"));

	public TaxonomyTranslateModelImpl() {
	}

	@Override
	public TaxonomyTranslatePK getPrimaryKey() {
		return new TaxonomyTranslatePK(_taxId, _localeCode);
	}

	@Override
	public void setPrimaryKey(TaxonomyTranslatePK primaryKey) {
		setTaxId(primaryKey.taxId);
		setLocaleCode(primaryKey.localeCode);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new TaxonomyTranslatePK(_taxId, _localeCode);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((TaxonomyTranslatePK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return TaxonomyTranslate.class;
	}

	@Override
	public String getModelClassName() {
		return TaxonomyTranslate.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("taxId", getTaxId());
		attributes.put("localeCode", getLocaleCode());
		attributes.put("title", getTitle());
		attributes.put("desc", getDesc());
		attributes.put("imageLoc", getImageLoc());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long taxId = (Long)attributes.get("taxId");

		if (taxId != null) {
			setTaxId(taxId);
		}

		String localeCode = (String)attributes.get("localeCode");

		if (localeCode != null) {
			setLocaleCode(localeCode);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String desc = (String)attributes.get("desc");

		if (desc != null) {
			setDesc(desc);
		}

		String imageLoc = (String)attributes.get("imageLoc");

		if (imageLoc != null) {
			setImageLoc(imageLoc);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getTaxId() {
		return _taxId;
	}

	@Override
	public void setTaxId(long taxId) {
		_taxId = taxId;
	}

	@Override
	public String getLocaleCode() {
		if (_localeCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _localeCode;
		}
	}

	@Override
	public void setLocaleCode(String localeCode) {
		_localeCode = localeCode;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getDesc() {
		if (_desc == null) {
			return StringPool.BLANK;
		}
		else {
			return _desc;
		}
	}

	@Override
	public void setDesc(String desc) {
		_desc = desc;
	}

	@Override
	public String getImageLoc() {
		if (_imageLoc == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageLoc;
		}
	}

	@Override
	public void setImageLoc(String imageLoc) {
		_imageLoc = imageLoc;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@Override
	public TaxonomyTranslate toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TaxonomyTranslate)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TaxonomyTranslateImpl taxonomyTranslateImpl = new TaxonomyTranslateImpl();

		taxonomyTranslateImpl.setTaxId(getTaxId());
		taxonomyTranslateImpl.setLocaleCode(getLocaleCode());
		taxonomyTranslateImpl.setTitle(getTitle());
		taxonomyTranslateImpl.setDesc(getDesc());
		taxonomyTranslateImpl.setImageLoc(getImageLoc());
		taxonomyTranslateImpl.setCreatorId(getCreatorId());
		taxonomyTranslateImpl.setCreatedDate(getCreatedDate());
		taxonomyTranslateImpl.setUpdatedBy(getUpdatedBy());
		taxonomyTranslateImpl.setUpdatedDate(getUpdatedDate());

		taxonomyTranslateImpl.resetOriginalValues();

		return taxonomyTranslateImpl;
	}

	@Override
	public int compareTo(TaxonomyTranslate taxonomyTranslate) {
		TaxonomyTranslatePK primaryKey = taxonomyTranslate.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TaxonomyTranslate)) {
			return false;
		}

		TaxonomyTranslate taxonomyTranslate = (TaxonomyTranslate)obj;

		TaxonomyTranslatePK primaryKey = taxonomyTranslate.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TaxonomyTranslate> toCacheModel() {
		TaxonomyTranslateCacheModel taxonomyTranslateCacheModel = new TaxonomyTranslateCacheModel();

		taxonomyTranslateCacheModel.taxId = getTaxId();

		taxonomyTranslateCacheModel.localeCode = getLocaleCode();

		String localeCode = taxonomyTranslateCacheModel.localeCode;

		if ((localeCode != null) && (localeCode.length() == 0)) {
			taxonomyTranslateCacheModel.localeCode = null;
		}

		taxonomyTranslateCacheModel.title = getTitle();

		String title = taxonomyTranslateCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			taxonomyTranslateCacheModel.title = null;
		}

		taxonomyTranslateCacheModel.desc = getDesc();

		String desc = taxonomyTranslateCacheModel.desc;

		if ((desc != null) && (desc.length() == 0)) {
			taxonomyTranslateCacheModel.desc = null;
		}

		taxonomyTranslateCacheModel.imageLoc = getImageLoc();

		String imageLoc = taxonomyTranslateCacheModel.imageLoc;

		if ((imageLoc != null) && (imageLoc.length() == 0)) {
			taxonomyTranslateCacheModel.imageLoc = null;
		}

		taxonomyTranslateCacheModel.creatorId = getCreatorId();

		String creatorId = taxonomyTranslateCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			taxonomyTranslateCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			taxonomyTranslateCacheModel.createdDate = createdDate.getTime();
		}
		else {
			taxonomyTranslateCacheModel.createdDate = Long.MIN_VALUE;
		}

		taxonomyTranslateCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = taxonomyTranslateCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			taxonomyTranslateCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			taxonomyTranslateCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			taxonomyTranslateCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return taxonomyTranslateCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{taxId=");
		sb.append(getTaxId());
		sb.append(", localeCode=");
		sb.append(getLocaleCode());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", desc=");
		sb.append(getDesc());
		sb.append(", imageLoc=");
		sb.append(getImageLoc());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.TaxonomyTranslate");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>taxId</column-name><column-value><![CDATA[");
		sb.append(getTaxId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>localeCode</column-name><column-value><![CDATA[");
		sb.append(getLocaleCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>desc</column-name><column-value><![CDATA[");
		sb.append(getDesc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageLoc</column-name><column-value><![CDATA[");
		sb.append(getImageLoc());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TaxonomyTranslate.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			TaxonomyTranslate.class
		};
	private long _taxId;
	private String _localeCode;
	private String _title;
	private String _desc;
	private String _imageLoc;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private TaxonomyTranslate _escapedModel;
}