/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PublishExtStd service. Represents a row in the &quot;PUBLISH_STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.PublishExtStdModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.PublishExtStdImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see PublishExtStd
 * @see com.ihg.brandstandards.db.model.impl.PublishExtStdImpl
 * @see com.ihg.brandstandards.db.model.impl.PublishExtStdModelImpl
 * @generated
 */
public interface PublishExtStdModel extends BaseModel<PublishExtStd> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables. model instance should use the {@link PublishExtStd} interface instead.
	 */

	/**
	 * Returns the primary key of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the primary key of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param primaryKey the primary key of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the comp date of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the comp date of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public Date getCompDate();

	/**
	 * Sets the comp date of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param compDate the comp date of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setCompDate(Date compDate);

	/**
	 * Returns the std ID of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the std ID of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param stdId the std ID of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the parent ID of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the parent ID of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public long getParentId();

	/**
	 * Sets the parent ID of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param parentId the parent ID of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setParentId(long parentId);

	/**
	 * Returns the title of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the title of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param title the title of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setTitle(String title);

	/**
	 * Returns the expired IDs of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the expired IDs of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	@AutoEscape
	public String getExpiredIds();

	/**
	 * Sets the expired IDs of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param expiredIds the expired IDs of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setExpiredIds(String expiredIds);

	/**
	 * Returns the region code of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the region code of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	@AutoEscape
	public String getRegionCode();

	/**
	 * Sets the region code of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param regionCode the region code of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setRegionCode(String regionCode);

	/**
	 * Returns the is global of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the is global of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	@AutoEscape
	public String getIsGlobal();

	/**
	 * Sets the is global of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param isGlobal the is global of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setIsGlobal(String isGlobal);

	/**
	 * Returns the framework of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @return the framework of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	@AutoEscape
	public String getFramework();

	/**
	 * Sets the framework of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables..
	 *
	 * @param framework the framework of this Custom Query mapping between PUBLISH_STD and STD_CTRY_CHAIN tables.
	 */
	public void setFramework(String framework);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PublishExtStd publishExtStd);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PublishExtStd> toCacheModel();

	@Override
	public PublishExtStd toEscapedModel();

	@Override
	public PublishExtStd toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}