/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.UniqueGroupCountry;
import com.ihg.brandstandards.db.model.UniqueGroupCountryModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the UniqueGroupCountry service. Represents a row in the &quot;UNIQUE_GRP_CTRY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.UniqueGroupCountryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UniqueGroupCountryImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see UniqueGroupCountryImpl
 * @see com.ihg.brandstandards.db.model.UniqueGroupCountry
 * @see com.ihg.brandstandards.db.model.UniqueGroupCountryModel
 * @generated
 */
public class UniqueGroupCountryModelImpl extends BaseModelImpl<UniqueGroupCountry>
	implements UniqueGroupCountryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unique group country model instance should use the {@link com.ihg.brandstandards.db.model.UniqueGroupCountry} interface instead.
	 */
	public static final String TABLE_NAME = "UNIQUE_GRP_CTRY";
	public static final Object[][] TABLE_COLUMNS = {
			{ "UNIQUE_GRP_CTRY_ID", Types.BIGINT },
			{ "UNIQUE_GRP_ID", Types.BIGINT },
			{ "CTRY_NM_CD", Types.VARCHAR },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table UNIQUE_GRP_CTRY (UNIQUE_GRP_CTRY_ID LONG not null primary key,UNIQUE_GRP_ID LONG,CTRY_NM_CD VARCHAR(75) null,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table UNIQUE_GRP_CTRY";
	public static final String ORDER_BY_JPQL = " ORDER BY uniqueGroupCountry.groupCountryId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY UNIQUE_GRP_CTRY.UNIQUE_GRP_CTRY_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.UniqueGroupCountry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.UniqueGroupCountry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.UniqueGroupCountry"));

	public UniqueGroupCountryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _groupCountryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGroupCountryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _groupCountryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UniqueGroupCountry.class;
	}

	@Override
	public String getModelClassName() {
		return UniqueGroupCountry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("groupCountryId", getGroupCountryId());
		attributes.put("uniqueGroupId", getUniqueGroupId());
		attributes.put("countryCode", getCountryCode());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long groupCountryId = (Long)attributes.get("groupCountryId");

		if (groupCountryId != null) {
			setGroupCountryId(groupCountryId);
		}

		Long uniqueGroupId = (Long)attributes.get("uniqueGroupId");

		if (uniqueGroupId != null) {
			setUniqueGroupId(uniqueGroupId);
		}

		String countryCode = (String)attributes.get("countryCode");

		if (countryCode != null) {
			setCountryCode(countryCode);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getGroupCountryId() {
		return _groupCountryId;
	}

	@Override
	public void setGroupCountryId(long groupCountryId) {
		_groupCountryId = groupCountryId;
	}

	@Override
	public long getUniqueGroupId() {
		return _uniqueGroupId;
	}

	@Override
	public void setUniqueGroupId(long uniqueGroupId) {
		_uniqueGroupId = uniqueGroupId;
	}

	@Override
	public String getCountryCode() {
		if (_countryCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _countryCode;
		}
	}

	@Override
	public void setCountryCode(String countryCode) {
		_countryCode = countryCode;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			UniqueGroupCountry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UniqueGroupCountry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UniqueGroupCountry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UniqueGroupCountryImpl uniqueGroupCountryImpl = new UniqueGroupCountryImpl();

		uniqueGroupCountryImpl.setGroupCountryId(getGroupCountryId());
		uniqueGroupCountryImpl.setUniqueGroupId(getUniqueGroupId());
		uniqueGroupCountryImpl.setCountryCode(getCountryCode());
		uniqueGroupCountryImpl.setCreatorId(getCreatorId());
		uniqueGroupCountryImpl.setCreatedDate(getCreatedDate());
		uniqueGroupCountryImpl.setUpdatedBy(getUpdatedBy());
		uniqueGroupCountryImpl.setUpdatedDate(getUpdatedDate());

		uniqueGroupCountryImpl.resetOriginalValues();

		return uniqueGroupCountryImpl;
	}

	@Override
	public int compareTo(UniqueGroupCountry uniqueGroupCountry) {
		long primaryKey = uniqueGroupCountry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UniqueGroupCountry)) {
			return false;
		}

		UniqueGroupCountry uniqueGroupCountry = (UniqueGroupCountry)obj;

		long primaryKey = uniqueGroupCountry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UniqueGroupCountry> toCacheModel() {
		UniqueGroupCountryCacheModel uniqueGroupCountryCacheModel = new UniqueGroupCountryCacheModel();

		uniqueGroupCountryCacheModel.groupCountryId = getGroupCountryId();

		uniqueGroupCountryCacheModel.uniqueGroupId = getUniqueGroupId();

		uniqueGroupCountryCacheModel.countryCode = getCountryCode();

		String countryCode = uniqueGroupCountryCacheModel.countryCode;

		if ((countryCode != null) && (countryCode.length() == 0)) {
			uniqueGroupCountryCacheModel.countryCode = null;
		}

		uniqueGroupCountryCacheModel.creatorId = getCreatorId();

		String creatorId = uniqueGroupCountryCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			uniqueGroupCountryCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			uniqueGroupCountryCacheModel.createdDate = createdDate.getTime();
		}
		else {
			uniqueGroupCountryCacheModel.createdDate = Long.MIN_VALUE;
		}

		uniqueGroupCountryCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = uniqueGroupCountryCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			uniqueGroupCountryCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			uniqueGroupCountryCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			uniqueGroupCountryCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return uniqueGroupCountryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{groupCountryId=");
		sb.append(getGroupCountryId());
		sb.append(", uniqueGroupId=");
		sb.append(getUniqueGroupId());
		sb.append(", countryCode=");
		sb.append(getCountryCode());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.UniqueGroupCountry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>groupCountryId</column-name><column-value><![CDATA[");
		sb.append(getGroupCountryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>uniqueGroupId</column-name><column-value><![CDATA[");
		sb.append(getUniqueGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>countryCode</column-name><column-value><![CDATA[");
		sb.append(getCountryCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UniqueGroupCountry.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UniqueGroupCountry.class
		};
	private long _groupCountryId;
	private long _uniqueGroupId;
	private String _countryCode;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private UniqueGroupCountry _escapedModel;
}