/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model.impl;

import com.ihg.brandstandards.db.model.UniqueGroupStandard;
import com.ihg.brandstandards.db.model.UniqueGroupStandardModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the UniqueGroupStandard service. Represents a row in the &quot;UNIQUE_GRP_STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ihg.brandstandards.db.model.UniqueGroupStandardModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link UniqueGroupStandardImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see UniqueGroupStandardImpl
 * @see com.ihg.brandstandards.db.model.UniqueGroupStandard
 * @see com.ihg.brandstandards.db.model.UniqueGroupStandardModel
 * @generated
 */
public class UniqueGroupStandardModelImpl extends BaseModelImpl<UniqueGroupStandard>
	implements UniqueGroupStandardModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a unique group standard model instance should use the {@link com.ihg.brandstandards.db.model.UniqueGroupStandard} interface instead.
	 */
	public static final String TABLE_NAME = "UNIQUE_GRP_STD";
	public static final Object[][] TABLE_COLUMNS = {
			{ "UNIQUE_GRP_STD_ID", Types.BIGINT },
			{ "UNIQUE_GRP_ID", Types.BIGINT },
			{ "STD_ID", Types.BIGINT },
			{ "CREAT_USR_ID", Types.VARCHAR },
			{ "CREAT_TS", Types.TIMESTAMP },
			{ "LST_UPDT_USR_ID", Types.VARCHAR },
			{ "LST_UPDT_TS", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table UNIQUE_GRP_STD (UNIQUE_GRP_STD_ID LONG not null primary key,UNIQUE_GRP_ID LONG,STD_ID LONG,CREAT_USR_ID VARCHAR(75) null,CREAT_TS DATE null,LST_UPDT_USR_ID VARCHAR(75) null,LST_UPDT_TS DATE null)";
	public static final String TABLE_SQL_DROP = "drop table UNIQUE_GRP_STD";
	public static final String ORDER_BY_JPQL = " ORDER BY uniqueGroupStandard.groupStandardId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY UNIQUE_GRP_STD.UNIQUE_GRP_STD_ID ASC";
	public static final String DATA_SOURCE = "brandstandDataSource";
	public static final String SESSION_FACTORY = "BRNDSTNDSessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ihg.brandstandards.db.model.UniqueGroupStandard"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ihg.brandstandards.db.model.UniqueGroupStandard"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ihg.brandstandards.db.model.UniqueGroupStandard"));

	public UniqueGroupStandardModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _groupStandardId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGroupStandardId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _groupStandardId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return UniqueGroupStandard.class;
	}

	@Override
	public String getModelClassName() {
		return UniqueGroupStandard.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("groupStandardId", getGroupStandardId());
		attributes.put("groupId", getGroupId());
		attributes.put("stdId", getStdId());
		attributes.put("creatorId", getCreatorId());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("updatedBy", getUpdatedBy());
		attributes.put("updatedDate", getUpdatedDate());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long groupStandardId = (Long)attributes.get("groupStandardId");

		if (groupStandardId != null) {
			setGroupStandardId(groupStandardId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long stdId = (Long)attributes.get("stdId");

		if (stdId != null) {
			setStdId(stdId);
		}

		String creatorId = (String)attributes.get("creatorId");

		if (creatorId != null) {
			setCreatorId(creatorId);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		String updatedBy = (String)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}
	}

	@Override
	public long getGroupStandardId() {
		return _groupStandardId;
	}

	@Override
	public void setGroupStandardId(long groupStandardId) {
		_groupStandardId = groupStandardId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@Override
	public long getStdId() {
		return _stdId;
	}

	@Override
	public void setStdId(long stdId) {
		_stdId = stdId;
	}

	@Override
	public String getCreatorId() {
		if (_creatorId == null) {
			return StringPool.BLANK;
		}
		else {
			return _creatorId;
		}
	}

	@Override
	public void setCreatorId(String creatorId) {
		_creatorId = creatorId;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public String getUpdatedBy() {
		if (_updatedBy == null) {
			return StringPool.BLANK;
		}
		else {
			return _updatedBy;
		}
	}

	@Override
	public void setUpdatedBy(String updatedBy) {
		_updatedBy = updatedBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			UniqueGroupStandard.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public UniqueGroupStandard toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (UniqueGroupStandard)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		UniqueGroupStandardImpl uniqueGroupStandardImpl = new UniqueGroupStandardImpl();

		uniqueGroupStandardImpl.setGroupStandardId(getGroupStandardId());
		uniqueGroupStandardImpl.setGroupId(getGroupId());
		uniqueGroupStandardImpl.setStdId(getStdId());
		uniqueGroupStandardImpl.setCreatorId(getCreatorId());
		uniqueGroupStandardImpl.setCreatedDate(getCreatedDate());
		uniqueGroupStandardImpl.setUpdatedBy(getUpdatedBy());
		uniqueGroupStandardImpl.setUpdatedDate(getUpdatedDate());

		uniqueGroupStandardImpl.resetOriginalValues();

		return uniqueGroupStandardImpl;
	}

	@Override
	public int compareTo(UniqueGroupStandard uniqueGroupStandard) {
		long primaryKey = uniqueGroupStandard.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof UniqueGroupStandard)) {
			return false;
		}

		UniqueGroupStandard uniqueGroupStandard = (UniqueGroupStandard)obj;

		long primaryKey = uniqueGroupStandard.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<UniqueGroupStandard> toCacheModel() {
		UniqueGroupStandardCacheModel uniqueGroupStandardCacheModel = new UniqueGroupStandardCacheModel();

		uniqueGroupStandardCacheModel.groupStandardId = getGroupStandardId();

		uniqueGroupStandardCacheModel.groupId = getGroupId();

		uniqueGroupStandardCacheModel.stdId = getStdId();

		uniqueGroupStandardCacheModel.creatorId = getCreatorId();

		String creatorId = uniqueGroupStandardCacheModel.creatorId;

		if ((creatorId != null) && (creatorId.length() == 0)) {
			uniqueGroupStandardCacheModel.creatorId = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			uniqueGroupStandardCacheModel.createdDate = createdDate.getTime();
		}
		else {
			uniqueGroupStandardCacheModel.createdDate = Long.MIN_VALUE;
		}

		uniqueGroupStandardCacheModel.updatedBy = getUpdatedBy();

		String updatedBy = uniqueGroupStandardCacheModel.updatedBy;

		if ((updatedBy != null) && (updatedBy.length() == 0)) {
			uniqueGroupStandardCacheModel.updatedBy = null;
		}

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			uniqueGroupStandardCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			uniqueGroupStandardCacheModel.updatedDate = Long.MIN_VALUE;
		}

		return uniqueGroupStandardCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{groupStandardId=");
		sb.append(getGroupStandardId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", stdId=");
		sb.append(getStdId());
		sb.append(", creatorId=");
		sb.append(getCreatorId());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("com.ihg.brandstandards.db.model.UniqueGroupStandard");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>groupStandardId</column-name><column-value><![CDATA[");
		sb.append(getGroupStandardId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stdId</column-name><column-value><![CDATA[");
		sb.append(getStdId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>creatorId</column-name><column-value><![CDATA[");
		sb.append(getCreatorId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = UniqueGroupStandard.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			UniqueGroupStandard.class
		};
	private long _groupStandardId;
	private long _groupId;
	private long _stdId;
	private String _creatorId;
	private Date _createdDate;
	private String _updatedBy;
	private Date _updatedDate;
	private UniqueGroupStandard _escapedModel;
}