/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SpreadSheetAttributeUpdate service. Represents a row in the &quot;SPREADSHEET_ATTR_UPDT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.SpreadSheetAttributeUpdateModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.SpreadSheetAttributeUpdateImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see SpreadSheetAttributeUpdate
 * @see com.ihg.brandstandards.db.model.impl.SpreadSheetAttributeUpdateImpl
 * @see com.ihg.brandstandards.db.model.impl.SpreadSheetAttributeUpdateModelImpl
 * @generated
 */
public interface SpreadSheetAttributeUpdateModel extends BaseModel<SpreadSheetAttributeUpdate> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a spread sheet attribute update model instance should use the {@link SpreadSheetAttributeUpdate} interface instead.
	 */

	/**
	 * Returns the primary key of this spread sheet attribute update.
	 *
	 * @return the primary key of this spread sheet attribute update
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this spread sheet attribute update.
	 *
	 * @param primaryKey the primary key of this spread sheet attribute update
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the speard sheet ID of this spread sheet attribute update.
	 *
	 * @return the speard sheet ID of this spread sheet attribute update
	 */
	public long getSpeardSheetId();

	/**
	 * Sets the speard sheet ID of this spread sheet attribute update.
	 *
	 * @param speardSheetId the speard sheet ID of this spread sheet attribute update
	 */
	public void setSpeardSheetId(long speardSheetId);

	/**
	 * Returns the request title of this spread sheet attribute update.
	 *
	 * @return the request title of this spread sheet attribute update
	 */
	@AutoEscape
	public String getRequestTitle();

	/**
	 * Sets the request title of this spread sheet attribute update.
	 *
	 * @param requestTitle the request title of this spread sheet attribute update
	 */
	public void setRequestTitle(String requestTitle);

	/**
	 * Returns the status of this spread sheet attribute update.
	 *
	 * @return the status of this spread sheet attribute update
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this spread sheet attribute update.
	 *
	 * @param status the status of this spread sheet attribute update
	 */
	public void setStatus(String status);

	/**
	 * Returns the creator ID of this spread sheet attribute update.
	 *
	 * @return the creator ID of this spread sheet attribute update
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this spread sheet attribute update.
	 *
	 * @param creatorId the creator ID of this spread sheet attribute update
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this spread sheet attribute update.
	 *
	 * @return the created date of this spread sheet attribute update
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this spread sheet attribute update.
	 *
	 * @param createdDate the created date of this spread sheet attribute update
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this spread sheet attribute update.
	 *
	 * @return the updated by of this spread sheet attribute update
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this spread sheet attribute update.
	 *
	 * @param updatedBy the updated by of this spread sheet attribute update
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this spread sheet attribute update.
	 *
	 * @return the updated date of this spread sheet attribute update
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this spread sheet attribute update.
	 *
	 * @param updatedDate the updated date of this spread sheet attribute update
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the spread sheet of this spread sheet attribute update.
	 *
	 * @return the spread sheet of this spread sheet attribute update
	 */
	@AutoEscape
	public String getSpreadSheet();

	/**
	 * Sets the spread sheet of this spread sheet attribute update.
	 *
	 * @param spreadSheet the spread sheet of this spread sheet attribute update
	 */
	public void setSpreadSheet(String spreadSheet);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SpreadSheetAttributeUpdate spreadSheetAttributeUpdate);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SpreadSheetAttributeUpdate> toCacheModel();

	@Override
	public SpreadSheetAttributeUpdate toEscapedModel();

	@Override
	public SpreadSheetAttributeUpdate toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}