create table GRS_COMM.PORTAL_FEEDBACK_DTL (
	PORTAL_FEEDBACK_DTL_ID INTEGER not null primary key,
	PORTAL_USR_ID INTEGER,
	FEEDBACK_TYP_NM VARCHAR(75) null,
	SUBJECT_NM VARCHAR(75) null,
	MSG_TXT VARCHAR(75) null,
	FILE_NM VARCHAR(75) null,
	FILE_BLOB BLOB,
	CREAT_USR_ID VARCHAR(75) null,
	CREAT_TS DATE null,
	LST_UPDT_USR_ID VARCHAR(75) null,
	LST_UPDT_TS DATE null
);

create table GRS_COMM.PORTAL_USR (
	PORTAL_USR_ID INTEGER not null primary key,
	USR_FRST_NM VARCHAR(75) null,
	USR_LST_NM VARCHAR(75) null,
	BUS_TITLE_NM VARCHAR(75) null,
	USR_EMAIL_ID VARCHAR(75) null,
	CREAT_USR_ID VARCHAR(75) null,
	CREAT_TS DATE null,
	LST_UPDT_USR_ID VARCHAR(75) null,
	LST_UPDT_TS DATE null
);

create table GRS_COMM.TEAM_MBR (
	TEAM_MBR_ID INTEGER not null primary key,
	TEAM_MBR_FRST_NM VARCHAR(75) null,
	TEAM_MBR_LST_NM VARCHAR(75) null,
	BUS_TITLE_NM VARCHAR(75) null,
	RGN_NM VARCHAR(75) null,
	ROLE_NM VARCHAR(75) null,
	ROLE_TYP_NM VARCHAR(75) null,
	ORG_NM VARCHAR(75) null,
	PHOTO_URL_TXT VARCHAR(75) null,
	CREAT_USR_ID VARCHAR(75) null,
	CREAT_TS DATE null,
	LST_UPDT_USR_ID VARCHAR(75) null,
	LST_UPDT_TS DATE null
);