/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.grs.common.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Directory service. Represents a row in the &quot;GRS_COMM.TEAM_MBR&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.grs.common.model.impl.DirectoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.grs.common.model.impl.DirectoryImpl}.
 * </p>
 *
 * @author gulam.vora
 * @see Directory
 * @see com.ihg.grs.common.model.impl.DirectoryImpl
 * @see com.ihg.grs.common.model.impl.DirectoryModelImpl
 * @generated
 */
public interface DirectoryModel extends BaseModel<Directory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a directory model instance should use the {@link Directory} interface instead.
	 */

	/**
	 * Returns the primary key of this directory.
	 *
	 * @return the primary key of this directory
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this directory.
	 *
	 * @param primaryKey the primary key of this directory
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the directory ID of this directory.
	 *
	 * @return the directory ID of this directory
	 */
	public int getDirectoryId();

	/**
	 * Sets the directory ID of this directory.
	 *
	 * @param directoryId the directory ID of this directory
	 */
	public void setDirectoryId(int directoryId);

	/**
	 * Returns the first name of this directory.
	 *
	 * @return the first name of this directory
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this directory.
	 *
	 * @param firstName the first name of this directory
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this directory.
	 *
	 * @return the last name of this directory
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this directory.
	 *
	 * @param lastName the last name of this directory
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the business title of this directory.
	 *
	 * @return the business title of this directory
	 */
	@AutoEscape
	public String getBusinessTitle();

	/**
	 * Sets the business title of this directory.
	 *
	 * @param businessTitle the business title of this directory
	 */
	public void setBusinessTitle(String businessTitle);

	/**
	 * Returns the geo region of this directory.
	 *
	 * @return the geo region of this directory
	 */
	@AutoEscape
	public String getGeoRegion();

	/**
	 * Sets the geo region of this directory.
	 *
	 * @param geoRegion the geo region of this directory
	 */
	public void setGeoRegion(String geoRegion);

	/**
	 * Returns the role of this directory.
	 *
	 * @return the role of this directory
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this directory.
	 *
	 * @param role the role of this directory
	 */
	public void setRole(String role);

	/**
	 * Returns the region type of this directory.
	 *
	 * @return the region type of this directory
	 */
	@AutoEscape
	public String getRegionType();

	/**
	 * Sets the region type of this directory.
	 *
	 * @param regionType the region type of this directory
	 */
	public void setRegionType(String regionType);

	/**
	 * Returns the organization name of this directory.
	 *
	 * @return the organization name of this directory
	 */
	@AutoEscape
	public String getOrganizationName();

	/**
	 * Sets the organization name of this directory.
	 *
	 * @param organizationName the organization name of this directory
	 */
	public void setOrganizationName(String organizationName);

	/**
	 * Returns the portrait u r l of this directory.
	 *
	 * @return the portrait u r l of this directory
	 */
	@AutoEscape
	public String getPortraitURL();

	/**
	 * Sets the portrait u r l of this directory.
	 *
	 * @param portraitURL the portrait u r l of this directory
	 */
	public void setPortraitURL(String portraitURL);

	/**
	 * Returns the createdate of this directory.
	 *
	 * @return the createdate of this directory
	 */
	public Date getCreatedate();

	/**
	 * Sets the createdate of this directory.
	 *
	 * @param createdate the createdate of this directory
	 */
	public void setCreatedate(Date createdate);

	/**
	 * Returns the create user ID of this directory.
	 *
	 * @return the create user ID of this directory
	 */
	@AutoEscape
	public String getCreateUserId();

	/**
	 * Sets the create user ID of this directory.
	 *
	 * @param createUserId the create user ID of this directory
	 */
	public void setCreateUserId(String createUserId);

	/**
	 * Returns the last update user ID of this directory.
	 *
	 * @return the last update user ID of this directory
	 */
	@AutoEscape
	public String getLastUpdateUserId();

	/**
	 * Sets the last update user ID of this directory.
	 *
	 * @param lastUpdateUserId the last update user ID of this directory
	 */
	public void setLastUpdateUserId(String lastUpdateUserId);

	/**
	 * Returns the updatedate of this directory.
	 *
	 * @return the updatedate of this directory
	 */
	public Date getUpdatedate();

	/**
	 * Sets the updatedate of this directory.
	 *
	 * @param updatedate the updatedate of this directory
	 */
	public void setUpdatedate(Date updatedate);

	/**
	 * Returns the email of this directory.
	 *
	 * @return the email of this directory
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this directory.
	 *
	 * @param email the email of this directory
	 */
	public void setEmail(String email);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.ihg.grs.common.model.Directory directory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.ihg.grs.common.model.Directory> toCacheModel();

	@Override
	public com.ihg.grs.common.model.Directory toEscapedModel();

	@Override
	public com.ihg.grs.common.model.Directory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}