<%@include file="/html/init.jsp" %>
<%@page import="javax.portlet.PortletURL" %>
<%@page import="java.util.Map"%>
<%@page import="java.util.List" %>
<%@page import="java.util.ArrayList" %>
<%@page import="java.util.Calendar" %>
<%@page import="java.util.Collections" %>
<%@page import="java.util.LinkedHashMap"%>
<%@page import="com.liferay.portal.kernel.util.HtmlUtil" %>
<%@page import="com.liferay.portal.kernel.util.ParamUtil" %>
<%@page import="com.liferay.portal.kernel.dao.search.SearchContainer" %>
<%@page import="com.liferay.portal.kernel.search.SearchContext" %>
<%@page import="com.liferay.portal.kernel.search.SearchContextFactory" %>
<%@page import="com.liferay.portal.kernel.search.Hits" %>
<%@page import="com.liferay.portal.kernel.util.ListUtil" %>
<%@page import="com.ihg.brandstandards.util.BrandStandardsUtil"%>
<%@page import="com.ihg.brandstandards.util.StandardsStatusUtil"%>
<%@page import="com.ihg.brandstandards.db.model.Standards"%>
<%@page import="com.ihg.brandstandards.db.model.FlagCategory"%>
<%@page import="com.ihg.brandstandards.db.service.TaxonomyExtLocalServiceUtil"%>
<%@page import="com.ihg.brandstandards.bsadmin.model.StandardsView"%>
<%@page import="com.ihg.brandstandards.util.StandardsUtil"%>
<%@page import="com.liferay.portal.service.UserLocalServiceUtil" %>
<%@page import="com.liferay.portal.model.User"%>
<%@page import="com.ihg.brandstandards.db.model.Workflow"%>