/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PublishDept service. Represents a row in the &quot;GEM_PUBLISH_DEPT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.PublishDeptModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.PublishDeptImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see PublishDept
 * @see com.ihg.brandstandards.db.model.impl.PublishDeptImpl
 * @see com.ihg.brandstandards.db.model.impl.PublishDeptModelImpl
 * @generated
 */
public interface PublishDeptModel extends BaseModel<PublishDept> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a publish dept model instance should use the {@link PublishDept} interface instead.
	 */

	/**
	 * Returns the primary key of this publish dept.
	 *
	 * @return the primary key of this publish dept
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this publish dept.
	 *
	 * @param primaryKey the primary key of this publish dept
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the publish dept ID of this publish dept.
	 *
	 * @return the publish dept ID of this publish dept
	 */
	public long getPublishDeptId();

	/**
	 * Sets the publish dept ID of this publish dept.
	 *
	 * @param publishDeptId the publish dept ID of this publish dept
	 */
	public void setPublishDeptId(long publishDeptId);

	/**
	 * Returns the dept ID of this publish dept.
	 *
	 * @return the dept ID of this publish dept
	 */
	public long getDeptId();

	/**
	 * Sets the dept ID of this publish dept.
	 *
	 * @param deptId the dept ID of this publish dept
	 */
	public void setDeptId(long deptId);

	/**
	 * Returns the publish ID of this publish dept.
	 *
	 * @return the publish ID of this publish dept
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this publish dept.
	 *
	 * @param publishId the publish ID of this publish dept
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the creator ID of this publish dept.
	 *
	 * @return the creator ID of this publish dept
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this publish dept.
	 *
	 * @param creatorId the creator ID of this publish dept
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this publish dept.
	 *
	 * @return the created date of this publish dept
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this publish dept.
	 *
	 * @param createdDate the created date of this publish dept
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this publish dept.
	 *
	 * @return the updated by of this publish dept
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this publish dept.
	 *
	 * @param updatedBy the updated by of this publish dept
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this publish dept.
	 *
	 * @return the updated date of this publish dept
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this publish dept.
	 *
	 * @param updatedDate the updated date of this publish dept
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PublishDept publishDept);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PublishDept> toCacheModel();

	@Override
	public PublishDept toEscapedModel();

	@Override
	public PublishDept toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}