/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsStatus service. Represents a row in the &quot;STAT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsStatusModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsStatusImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsStatus
 * @see com.ihg.brandstandards.db.model.impl.StandardsStatusImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsStatusModelImpl
 * @generated
 */
public interface StandardsStatusModel extends BaseModel<StandardsStatus> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards status model instance should use the {@link StandardsStatus} interface instead.
	 */

	/**
	 * Returns the primary key of this standards status.
	 *
	 * @return the primary key of this standards status
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this standards status.
	 *
	 * @param primaryKey the primary key of this standards status
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the status ID of this standards status.
	 *
	 * @return the status ID of this standards status
	 */
	public long getStatusId();

	/**
	 * Sets the status ID of this standards status.
	 *
	 * @param statusId the status ID of this standards status
	 */
	public void setStatusId(long statusId);

	/**
	 * Returns the status code of this standards status.
	 *
	 * @return the status code of this standards status
	 */
	@AutoEscape
	public String getStatusCode();

	/**
	 * Sets the status code of this standards status.
	 *
	 * @param statusCode the status code of this standards status
	 */
	public void setStatusCode(String statusCode);

	/**
	 * Returns the title of this standards status.
	 *
	 * @return the title of this standards status
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this standards status.
	 *
	 * @param title the title of this standards status
	 */
	public void setTitle(String title);

	/**
	 * Returns the region ID of this standards status.
	 *
	 * @return the region ID of this standards status
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this standards status.
	 *
	 * @param regionId the region ID of this standards status
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the creator ID of this standards status.
	 *
	 * @return the creator ID of this standards status
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards status.
	 *
	 * @param creatorId the creator ID of this standards status
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards status.
	 *
	 * @return the created date of this standards status
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards status.
	 *
	 * @param createdDate the created date of this standards status
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards status.
	 *
	 * @return the updated by of this standards status
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards status.
	 *
	 * @param updatedBy the updated by of this standards status
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards status.
	 *
	 * @return the updated date of this standards status
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards status.
	 *
	 * @param updatedDate the updated date of this standards status
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsStatus standardsStatus);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsStatus> toCacheModel();

	@Override
	public StandardsStatus toEscapedModel();

	@Override
	public StandardsStatus toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}