/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ExternalLinkStandards service. Represents a row in the &quot;STD_EXTL_LINK&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.ExternalLinkStandardsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.ExternalLinkStandardsImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see ExternalLinkStandards
 * @see com.ihg.brandstandards.db.model.impl.ExternalLinkStandardsImpl
 * @see com.ihg.brandstandards.db.model.impl.ExternalLinkStandardsModelImpl
 * @generated
 */
public interface ExternalLinkStandardsModel extends BaseModel<ExternalLinkStandards> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a external link standards model instance should use the {@link ExternalLinkStandards} interface instead.
	 */

	/**
	 * Returns the primary key of this external link standards.
	 *
	 * @return the primary key of this external link standards
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this external link standards.
	 *
	 * @param primaryKey the primary key of this external link standards
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ext link ID of this external link standards.
	 *
	 * @return the ext link ID of this external link standards
	 */
	public long getExtLinkId();

	/**
	 * Sets the ext link ID of this external link standards.
	 *
	 * @param extLinkId the ext link ID of this external link standards
	 */
	public void setExtLinkId(long extLinkId);

	/**
	 * Returns the parent ext link ID of this external link standards.
	 *
	 * @return the parent ext link ID of this external link standards
	 */
	public long getParentExtLinkId();

	/**
	 * Sets the parent ext link ID of this external link standards.
	 *
	 * @param parentExtLinkId the parent ext link ID of this external link standards
	 */
	public void setParentExtLinkId(long parentExtLinkId);

	/**
	 * Returns the std ID of this external link standards.
	 *
	 * @return the std ID of this external link standards
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this external link standards.
	 *
	 * @param stdId the std ID of this external link standards
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the url of this external link standards.
	 *
	 * @return the url of this external link standards
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this external link standards.
	 *
	 * @param url the url of this external link standards
	 */
	public void setUrl(String url);

	/**
	 * Returns the title of this external link standards.
	 *
	 * @return the title of this external link standards
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this external link standards.
	 *
	 * @param title the title of this external link standards
	 */
	public void setTitle(String title);

	/**
	 * Returns the translation indicator of this external link standards.
	 *
	 * @return the translation indicator of this external link standards
	 */
	@AutoEscape
	public String getTranslationIndicator();

	/**
	 * Sets the translation indicator of this external link standards.
	 *
	 * @param translationIndicator the translation indicator of this external link standards
	 */
	public void setTranslationIndicator(String translationIndicator);

	/**
	 * Returns the locale code of this external link standards.
	 *
	 * @return the locale code of this external link standards
	 */
	@AutoEscape
	public String getLocaleCode();

	/**
	 * Sets the locale code of this external link standards.
	 *
	 * @param localeCode the locale code of this external link standards
	 */
	public void setLocaleCode(String localeCode);

	/**
	 * Returns the creator ID of this external link standards.
	 *
	 * @return the creator ID of this external link standards
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this external link standards.
	 *
	 * @param creatorId the creator ID of this external link standards
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this external link standards.
	 *
	 * @return the created date of this external link standards
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this external link standards.
	 *
	 * @param createdDate the created date of this external link standards
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this external link standards.
	 *
	 * @return the updated by of this external link standards
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this external link standards.
	 *
	 * @param updatedBy the updated by of this external link standards
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this external link standards.
	 *
	 * @return the updated date of this external link standards
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this external link standards.
	 *
	 * @param updatedDate the updated date of this external link standards
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ExternalLinkStandards externalLinkStandards);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ExternalLinkStandards> toCacheModel();

	@Override
	public ExternalLinkStandards toEscapedModel();

	@Override
	public ExternalLinkStandards toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}