/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMMeasurementBucketChain service. Represents a row in the &quot;GEM_MSRMNT_BUCKET_CHAIN&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMMeasurementBucketChainModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMMeasurementBucketChainImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMMeasurementBucketChain
 * @see com.ihg.brandstandards.db.model.impl.GEMMeasurementBucketChainImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMMeasurementBucketChainModelImpl
 * @generated
 */
public interface GEMMeasurementBucketChainModel extends BaseModel<GEMMeasurementBucketChain> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m measurement bucket chain model instance should use the {@link GEMMeasurementBucketChain} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m measurement bucket chain.
	 *
	 * @return the primary key of this g e m measurement bucket chain
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m measurement bucket chain.
	 *
	 * @param primaryKey the primary key of this g e m measurement bucket chain
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the measurement bucket chain ID of this g e m measurement bucket chain.
	 *
	 * @return the measurement bucket chain ID of this g e m measurement bucket chain
	 */
	public long getMeasurementBucketChainId();

	/**
	 * Sets the measurement bucket chain ID of this g e m measurement bucket chain.
	 *
	 * @param measurementBucketChainId the measurement bucket chain ID of this g e m measurement bucket chain
	 */
	public void setMeasurementBucketChainId(long measurementBucketChainId);

	/**
	 * Returns the bucket ID of this g e m measurement bucket chain.
	 *
	 * @return the bucket ID of this g e m measurement bucket chain
	 */
	public long getBucketId();

	/**
	 * Sets the bucket ID of this g e m measurement bucket chain.
	 *
	 * @param bucketId the bucket ID of this g e m measurement bucket chain
	 */
	public void setBucketId(long bucketId);

	/**
	 * Returns the severity ID of this g e m measurement bucket chain.
	 *
	 * @return the severity ID of this g e m measurement bucket chain
	 */
	public long getSeverityId();

	/**
	 * Sets the severity ID of this g e m measurement bucket chain.
	 *
	 * @param severityId the severity ID of this g e m measurement bucket chain
	 */
	public void setSeverityId(long severityId);

	/**
	 * Returns the measurement ID of this g e m measurement bucket chain.
	 *
	 * @return the measurement ID of this g e m measurement bucket chain
	 */
	public long getMeasurementId();

	/**
	 * Sets the measurement ID of this g e m measurement bucket chain.
	 *
	 * @param measurementId the measurement ID of this g e m measurement bucket chain
	 */
	public void setMeasurementId(long measurementId);

	/**
	 * Returns the publish dept ID of this g e m measurement bucket chain.
	 *
	 * @return the publish dept ID of this g e m measurement bucket chain
	 */
	public long getPublishDeptId();

	/**
	 * Sets the publish dept ID of this g e m measurement bucket chain.
	 *
	 * @param publishDeptId the publish dept ID of this g e m measurement bucket chain
	 */
	public void setPublishDeptId(long publishDeptId);

	/**
	 * Returns the publish ID of this g e m measurement bucket chain.
	 *
	 * @return the publish ID of this g e m measurement bucket chain
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this g e m measurement bucket chain.
	 *
	 * @param publishId the publish ID of this g e m measurement bucket chain
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the region ID of this g e m measurement bucket chain.
	 *
	 * @return the region ID of this g e m measurement bucket chain
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this g e m measurement bucket chain.
	 *
	 * @param regionId the region ID of this g e m measurement bucket chain
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the sub region cd of this g e m measurement bucket chain.
	 *
	 * @return the sub region cd of this g e m measurement bucket chain
	 */
	@AutoEscape
	public String getSubRegionCd();

	/**
	 * Sets the sub region cd of this g e m measurement bucket chain.
	 *
	 * @param subRegionCd the sub region cd of this g e m measurement bucket chain
	 */
	public void setSubRegionCd(String subRegionCd);

	/**
	 * Returns the creator ID of this g e m measurement bucket chain.
	 *
	 * @return the creator ID of this g e m measurement bucket chain
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m measurement bucket chain.
	 *
	 * @param creatorId the creator ID of this g e m measurement bucket chain
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m measurement bucket chain.
	 *
	 * @return the created date of this g e m measurement bucket chain
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m measurement bucket chain.
	 *
	 * @param createdDate the created date of this g e m measurement bucket chain
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m measurement bucket chain.
	 *
	 * @return the updated by of this g e m measurement bucket chain
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m measurement bucket chain.
	 *
	 * @param updatedBy the updated by of this g e m measurement bucket chain
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m measurement bucket chain.
	 *
	 * @return the updated date of this g e m measurement bucket chain
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m measurement bucket chain.
	 *
	 * @param updatedDate the updated date of this g e m measurement bucket chain
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMMeasurementBucketChain gemMeasurementBucketChain);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMMeasurementBucketChain> toCacheModel();

	@Override
	public GEMMeasurementBucketChain toEscapedModel();

	@Override
	public GEMMeasurementBucketChain toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}