/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMMeasurement service. Represents a row in the &quot;GEM_MSRMNT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMMeasurementModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMMeasurementImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMMeasurement
 * @see com.ihg.brandstandards.db.model.impl.GEMMeasurementImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMMeasurementModelImpl
 * @generated
 */
public interface GEMMeasurementModel extends BaseModel<GEMMeasurement> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m measurement model instance should use the {@link GEMMeasurement} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m measurement.
	 *
	 * @return the primary key of this g e m measurement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m measurement.
	 *
	 * @param primaryKey the primary key of this g e m measurement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the measurement ID of this g e m measurement.
	 *
	 * @return the measurement ID of this g e m measurement
	 */
	public long getMeasurementId();

	/**
	 * Sets the measurement ID of this g e m measurement.
	 *
	 * @param measurementId the measurement ID of this g e m measurement
	 */
	public void setMeasurementId(long measurementId);

	/**
	 * Returns the measurement name of this g e m measurement.
	 *
	 * @return the measurement name of this g e m measurement
	 */
	@AutoEscape
	public String getMeasurementName();

	/**
	 * Sets the measurement name of this g e m measurement.
	 *
	 * @param measurementName the measurement name of this g e m measurement
	 */
	public void setMeasurementName(String measurementName);

	/**
	 * Returns the measurement type of this g e m measurement.
	 *
	 * @return the measurement type of this g e m measurement
	 */
	@AutoEscape
	public String getMeasurementType();

	/**
	 * Sets the measurement type of this g e m measurement.
	 *
	 * @param measurementType the measurement type of this g e m measurement
	 */
	public void setMeasurementType(String measurementType);

	/**
	 * Returns the display order number of this g e m measurement.
	 *
	 * @return the display order number of this g e m measurement
	 */
	public long getDisplayOrderNumber();

	/**
	 * Sets the display order number of this g e m measurement.
	 *
	 * @param displayOrderNumber the display order number of this g e m measurement
	 */
	public void setDisplayOrderNumber(long displayOrderNumber);

	/**
	 * Returns the template ID of this g e m measurement.
	 *
	 * @return the template ID of this g e m measurement
	 */
	public long getTemplateId();

	/**
	 * Sets the template ID of this g e m measurement.
	 *
	 * @param templateId the template ID of this g e m measurement
	 */
	public void setTemplateId(long templateId);

	/**
	 * Returns the multiplier qty of this g e m measurement.
	 *
	 * @return the multiplier qty of this g e m measurement
	 */
	public long getMultiplierQty();

	/**
	 * Sets the multiplier qty of this g e m measurement.
	 *
	 * @param multiplierQty the multiplier qty of this g e m measurement
	 */
	public void setMultiplierQty(long multiplierQty);

	/**
	 * Returns the creator ID of this g e m measurement.
	 *
	 * @return the creator ID of this g e m measurement
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m measurement.
	 *
	 * @param creatorId the creator ID of this g e m measurement
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m measurement.
	 *
	 * @return the created date of this g e m measurement
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m measurement.
	 *
	 * @param createdDate the created date of this g e m measurement
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m measurement.
	 *
	 * @return the updated by of this g e m measurement
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m measurement.
	 *
	 * @param updatedBy the updated by of this g e m measurement
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m measurement.
	 *
	 * @return the updated date of this g e m measurement
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m measurement.
	 *
	 * @param updatedDate the updated date of this g e m measurement
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMMeasurement gemMeasurement);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMMeasurement> toCacheModel();

	@Override
	public GEMMeasurement toEscapedModel();

	@Override
	public GEMMeasurement toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}