/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GEMUniqueGroupCountry service. Represents a row in the &quot;GEM_UNIQUE_GROUP_CTRY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GEMUniqueGroupCountryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GEMUniqueGroupCountryImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GEMUniqueGroupCountry
 * @see com.ihg.brandstandards.db.model.impl.GEMUniqueGroupCountryImpl
 * @see com.ihg.brandstandards.db.model.impl.GEMUniqueGroupCountryModelImpl
 * @generated
 */
public interface GEMUniqueGroupCountryModel extends BaseModel<GEMUniqueGroupCountry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a g e m unique group country model instance should use the {@link GEMUniqueGroupCountry} interface instead.
	 */

	/**
	 * Returns the primary key of this g e m unique group country.
	 *
	 * @return the primary key of this g e m unique group country
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this g e m unique group country.
	 *
	 * @param primaryKey the primary key of this g e m unique group country
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the group country ID of this g e m unique group country.
	 *
	 * @return the group country ID of this g e m unique group country
	 */
	public long getGroupCountryId();

	/**
	 * Sets the group country ID of this g e m unique group country.
	 *
	 * @param groupCountryId the group country ID of this g e m unique group country
	 */
	public void setGroupCountryId(long groupCountryId);

	/**
	 * Returns the unique group ID of this g e m unique group country.
	 *
	 * @return the unique group ID of this g e m unique group country
	 */
	public long getUniqueGroupId();

	/**
	 * Sets the unique group ID of this g e m unique group country.
	 *
	 * @param uniqueGroupId the unique group ID of this g e m unique group country
	 */
	public void setUniqueGroupId(long uniqueGroupId);

	/**
	 * Returns the country code of this g e m unique group country.
	 *
	 * @return the country code of this g e m unique group country
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this g e m unique group country.
	 *
	 * @param countryCode the country code of this g e m unique group country
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the creator ID of this g e m unique group country.
	 *
	 * @return the creator ID of this g e m unique group country
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this g e m unique group country.
	 *
	 * @param creatorId the creator ID of this g e m unique group country
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this g e m unique group country.
	 *
	 * @return the created date of this g e m unique group country
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this g e m unique group country.
	 *
	 * @param createdDate the created date of this g e m unique group country
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this g e m unique group country.
	 *
	 * @return the updated by of this g e m unique group country
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this g e m unique group country.
	 *
	 * @param updatedBy the updated by of this g e m unique group country
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this g e m unique group country.
	 *
	 * @return the updated date of this g e m unique group country
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this g e m unique group country.
	 *
	 * @param updatedDate the updated date of this g e m unique group country
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GEMUniqueGroupCountry gemUniqueGroupCountry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GEMUniqueGroupCountry> toCacheModel();

	@Override
	public GEMUniqueGroupCountry toEscapedModel();

	@Override
	public GEMUniqueGroupCountry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}