/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GlossaryRegionNav service. Represents a row in the &quot;GLOSSARY_RGN_NAV&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.GlossaryRegionNavModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.GlossaryRegionNavImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see GlossaryRegionNav
 * @see com.ihg.brandstandards.db.model.impl.GlossaryRegionNavImpl
 * @see com.ihg.brandstandards.db.model.impl.GlossaryRegionNavModelImpl
 * @generated
 */
public interface GlossaryRegionNavModel extends BaseModel<GlossaryRegionNav> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a glossary region nav model instance should use the {@link GlossaryRegionNav} interface instead.
	 */

	/**
	 * Returns the primary key of this glossary region nav.
	 *
	 * @return the primary key of this glossary region nav
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this glossary region nav.
	 *
	 * @param primaryKey the primary key of this glossary region nav
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the glossary rgn nav ID of this glossary region nav.
	 *
	 * @return the glossary rgn nav ID of this glossary region nav
	 */
	public long getGlossaryRgnNavId();

	/**
	 * Sets the glossary rgn nav ID of this glossary region nav.
	 *
	 * @param glossaryRgnNavId the glossary rgn nav ID of this glossary region nav
	 */
	public void setGlossaryRgnNavId(long glossaryRgnNavId);

	/**
	 * Returns the glossary ID of this glossary region nav.
	 *
	 * @return the glossary ID of this glossary region nav
	 */
	public long getGlossaryId();

	/**
	 * Sets the glossary ID of this glossary region nav.
	 *
	 * @param glossaryId the glossary ID of this glossary region nav
	 */
	public void setGlossaryId(long glossaryId);

	/**
	 * Returns the region ID of this glossary region nav.
	 *
	 * @return the region ID of this glossary region nav
	 */
	public long getRegionId();

	/**
	 * Sets the region ID of this glossary region nav.
	 *
	 * @param regionId the region ID of this glossary region nav
	 */
	public void setRegionId(long regionId);

	/**
	 * Returns the nav item text of this glossary region nav.
	 *
	 * @return the nav item text of this glossary region nav
	 */
	@AutoEscape
	public String getNavItemText();

	/**
	 * Sets the nav item text of this glossary region nav.
	 *
	 * @param navItemText the nav item text of this glossary region nav
	 */
	public void setNavItemText(String navItemText);

	/**
	 * Returns the active ind of this glossary region nav.
	 *
	 * @return the active ind of this glossary region nav
	 */
	@AutoEscape
	public String getActiveInd();

	/**
	 * Sets the active ind of this glossary region nav.
	 *
	 * @param activeInd the active ind of this glossary region nav
	 */
	public void setActiveInd(String activeInd);

	/**
	 * Returns the chain code of this glossary region nav.
	 *
	 * @return the chain code of this glossary region nav
	 */
	@AutoEscape
	public String getChainCode();

	/**
	 * Sets the chain code of this glossary region nav.
	 *
	 * @param chainCode the chain code of this glossary region nav
	 */
	public void setChainCode(String chainCode);

	/**
	 * Returns the creator ID of this glossary region nav.
	 *
	 * @return the creator ID of this glossary region nav
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this glossary region nav.
	 *
	 * @param creatorId the creator ID of this glossary region nav
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this glossary region nav.
	 *
	 * @return the created date of this glossary region nav
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this glossary region nav.
	 *
	 * @param createdDate the created date of this glossary region nav
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this glossary region nav.
	 *
	 * @return the updated by of this glossary region nav
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this glossary region nav.
	 *
	 * @param updatedBy the updated by of this glossary region nav
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this glossary region nav.
	 *
	 * @return the updated date of this glossary region nav
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this glossary region nav.
	 *
	 * @param updatedDate the updated date of this glossary region nav
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(GlossaryRegionNav glossaryRegionNav);

	@Override
	public int hashCode();

	@Override
	public CacheModel<GlossaryRegionNav> toCacheModel();

	@Override
	public GlossaryRegionNav toEscapedModel();

	@Override
	public GlossaryRegionNav toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}