/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PublishTaxonomy service. Represents a row in the &quot;PUBLISH_TAXONOMY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.PublishTaxonomyModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.PublishTaxonomyImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see PublishTaxonomy
 * @see com.ihg.brandstandards.db.model.impl.PublishTaxonomyImpl
 * @see com.ihg.brandstandards.db.model.impl.PublishTaxonomyModelImpl
 * @generated
 */
public interface PublishTaxonomyModel extends BaseModel<PublishTaxonomy> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a publish taxonomy model instance should use the {@link PublishTaxonomy} interface instead.
	 */

	/**
	 * Returns the primary key of this publish taxonomy.
	 *
	 * @return the primary key of this publish taxonomy
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this publish taxonomy.
	 *
	 * @param primaryKey the primary key of this publish taxonomy
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the publish tax ID of this publish taxonomy.
	 *
	 * @return the publish tax ID of this publish taxonomy
	 */
	public long getPublishTaxId();

	/**
	 * Sets the publish tax ID of this publish taxonomy.
	 *
	 * @param publishTaxId the publish tax ID of this publish taxonomy
	 */
	public void setPublishTaxId(long publishTaxId);

	/**
	 * Returns the publish ID of this publish taxonomy.
	 *
	 * @return the publish ID of this publish taxonomy
	 */
	public long getPublishId();

	/**
	 * Sets the publish ID of this publish taxonomy.
	 *
	 * @param publishId the publish ID of this publish taxonomy
	 */
	public void setPublishId(long publishId);

	/**
	 * Returns the tax ID of this publish taxonomy.
	 *
	 * @return the tax ID of this publish taxonomy
	 */
	public long getTaxId();

	/**
	 * Sets the tax ID of this publish taxonomy.
	 *
	 * @param taxId the tax ID of this publish taxonomy
	 */
	public void setTaxId(long taxId);

	/**
	 * Returns the publish parent ID of this publish taxonomy.
	 *
	 * @return the publish parent ID of this publish taxonomy
	 */
	public long getPublishParentId();

	/**
	 * Sets the publish parent ID of this publish taxonomy.
	 *
	 * @param publishParentId the publish parent ID of this publish taxonomy
	 */
	public void setPublishParentId(long publishParentId);

	/**
	 * Returns the title of this publish taxonomy.
	 *
	 * @return the title of this publish taxonomy
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this publish taxonomy.
	 *
	 * @param title the title of this publish taxonomy
	 */
	public void setTitle(String title);

	/**
	 * Returns the desc of this publish taxonomy.
	 *
	 * @return the desc of this publish taxonomy
	 */
	@AutoEscape
	public String getDesc();

	/**
	 * Sets the desc of this publish taxonomy.
	 *
	 * @param desc the desc of this publish taxonomy
	 */
	public void setDesc(String desc);

	/**
	 * Returns the image loc of this publish taxonomy.
	 *
	 * @return the image loc of this publish taxonomy
	 */
	@AutoEscape
	public String getImageLoc();

	/**
	 * Sets the image loc of this publish taxonomy.
	 *
	 * @param imageLoc the image loc of this publish taxonomy
	 */
	public void setImageLoc(String imageLoc);

	/**
	 * Returns the created by of this publish taxonomy.
	 *
	 * @return the created by of this publish taxonomy
	 */
	@AutoEscape
	public String getCreatedBy();

	/**
	 * Sets the created by of this publish taxonomy.
	 *
	 * @param createdBy the created by of this publish taxonomy
	 */
	public void setCreatedBy(String createdBy);

	/**
	 * Returns the position of this publish taxonomy.
	 *
	 * @return the position of this publish taxonomy
	 */
	public long getPosition();

	/**
	 * Sets the position of this publish taxonomy.
	 *
	 * @param position the position of this publish taxonomy
	 */
	public void setPosition(long position);

	/**
	 * Returns the creator ID of this publish taxonomy.
	 *
	 * @return the creator ID of this publish taxonomy
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this publish taxonomy.
	 *
	 * @param creatorId the creator ID of this publish taxonomy
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this publish taxonomy.
	 *
	 * @return the created date of this publish taxonomy
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this publish taxonomy.
	 *
	 * @param createdDate the created date of this publish taxonomy
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this publish taxonomy.
	 *
	 * @return the updated by of this publish taxonomy
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this publish taxonomy.
	 *
	 * @param updatedBy the updated by of this publish taxonomy
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this publish taxonomy.
	 *
	 * @return the updated date of this publish taxonomy
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this publish taxonomy.
	 *
	 * @param updatedDate the updated date of this publish taxonomy
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PublishTaxonomy publishTaxonomy);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PublishTaxonomy> toCacheModel();

	@Override
	public PublishTaxonomy toEscapedModel();

	@Override
	public PublishTaxonomy toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}