/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.ihg.brandstandards.db.service.persistence.StandardsExtPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsExt service. Represents a row in the &quot;STD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsExtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsExtImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsExt
 * @see com.ihg.brandstandards.db.model.impl.StandardsExtImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsExtModelImpl
 * @generated
 */
public interface StandardsExtModel extends BaseModel<StandardsExt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Custom Query mapping between STD and Taxonomy tables. model instance should use the {@link StandardsExt} interface instead.
	 */

	/**
	 * Returns the primary key of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the primary key of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public StandardsExtPK getPrimaryKey();

	/**
	 * Sets the primary key of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param primaryKey the primary key of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setPrimaryKey(StandardsExtPK primaryKey);

	/**
	 * Returns the std ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdId the std ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the audit log ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the audit log ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getAuditLogId();

	/**
	 * Sets the audit log ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param auditLogId the audit log ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAuditLogId(long auditLogId);

	/**
	 * Returns the std manual of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std manual of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdManual();

	/**
	 * Sets the std manual of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdManual the std manual of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdManual(String stdManual);

	/**
	 * Returns the std corporate department of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std corporate department of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdCorporateDepartment();

	/**
	 * Sets the std corporate department of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdCorporateDepartment the std corporate department of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdCorporateDepartment(String stdCorporateDepartment);

	/**
	 * Returns the std brand cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std brand cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdBrandCd();

	/**
	 * Sets the std brand cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdBrandCd the std brand cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdBrandCd(String stdBrandCd);

	/**
	 * Returns the bi impact assmnt ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the bi impact assmnt ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getBiImpactAssmntId();

	/**
	 * Sets the bi impact assmnt ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param biImpactAssmntId the bi impact assmnt ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setBiImpactAssmntId(long biImpactAssmntId);

	/**
	 * Returns the std country cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std country cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdCountryCd();

	/**
	 * Sets the std country cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdCountryCd the std country cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdCountryCd(String stdCountryCd);

	/**
	 * Returns the std prnt ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std prnt ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getStdPrntId();

	/**
	 * Sets the std prnt ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdPrntId the std prnt ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdPrntId(long stdPrntId);

	/**
	 * Returns the std orig std ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std orig std ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getStdOrigStdId();

	/**
	 * Sets the std orig std ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdOrigStdId the std orig std ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdOrigStdId(long stdOrigStdId);

	/**
	 * Returns the std pub stat cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std pub stat cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdPubStatCd();

	/**
	 * Sets the std pub stat cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdPubStatCd the std pub stat cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdPubStatCd(String stdPubStatCd);

	/**
	 * Returns the std type of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std type of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdType();

	/**
	 * Sets the std type of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdType the std type of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdType(String stdType);

	/**
	 * Returns the std title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdTitle();

	/**
	 * Sets the std title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdTitle the std title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdTitle(String stdTitle);

	/**
	 * Returns the std description of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std description of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdDescription();

	/**
	 * Sets the std description of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdDescription the std description of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdDescription(String stdDescription);

	/**
	 * Returns the std business owner of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std business owner of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdBusinessOwner();

	/**
	 * Sets the std business owner of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdBusinessOwner the std business owner of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdBusinessOwner(String stdBusinessOwner);

	/**
	 * Returns the std status of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std status of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdStatus();

	/**
	 * Sets the std status of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdStatus the std status of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdStatus(String stdStatus);

	/**
	 * Returns the std author of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std author of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdAuthor();

	/**
	 * Sets the std author of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdAuthor the std author of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdAuthor(String stdAuthor);

	/**
	 * Returns the std category of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std category of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdCategory();

	/**
	 * Sets the std category of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdCategory the std category of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdCategory(String stdCategory);

	/**
	 * Returns the std global of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std global of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdGlobal();

	/**
	 * Sets the std global of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdGlobal the std global of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdGlobal(String stdGlobal);

	/**
	 * Returns the std region code of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std region code of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdRegionCode();

	/**
	 * Sets the std region code of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdRegionCode the std region code of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdRegionCode(String stdRegionCode);

	/**
	 * Returns the std framework of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std framework of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdFramework();

	/**
	 * Sets the std framework of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdFramework the std framework of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdFramework(String stdFramework);

	/**
	 * Returns the std change of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std change of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdChange();

	/**
	 * Sets the std change of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdChange the std change of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdChange(String stdChange);

	/**
	 * Returns the std created by of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std created by of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdCreatedBy();

	/**
	 * Sets the std created by of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdCreatedBy the std created by of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdCreatedBy(String stdCreatedBy);

	/**
	 * Returns the std updated date of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std updated date of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public Date getStdUpdatedDate();

	/**
	 * Sets the std updated date of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdUpdatedDate the std updated date of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdUpdatedDate(Date stdUpdatedDate);

	/**
	 * Returns the std image count of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std image count of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getStdImageCount();

	/**
	 * Sets the std image count of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdImageCount the std image count of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdImageCount(long stdImageCount);

	/**
	 * Returns the std image title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std image title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdImageTitle();

	/**
	 * Sets the std image title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdImageTitle the std image title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdImageTitle(String stdImageTitle);

	/**
	 * Returns the std internal reference of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std internal reference of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdInternalReference();

	/**
	 * Sets the std internal reference of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdInternalReference the std internal reference of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdInternalReference(String stdInternalReference);

	/**
	 * Returns the std order number of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std order number of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getStdOrderNumber();

	/**
	 * Sets the std order number of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdOrderNumber the std order number of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdOrderNumber(long stdOrderNumber);

	/**
	 * Returns the index ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the index ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getIndexId();

	/**
	 * Sets the index ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param indexId the index ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setIndexId(long indexId);

	/**
	 * Returns the index orig ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the index orig ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getIndexOrigId();

	/**
	 * Sets the index orig ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param indexOrigId the index orig ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setIndexOrigId(long indexOrigId);

	/**
	 * Returns the index prnt ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the index prnt ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getIndexPrntId();

	/**
	 * Sets the index prnt ID of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param indexPrntId the index prnt ID of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setIndexPrntId(long indexPrntId);

	/**
	 * Returns the index title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the index title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getIndexTitle();

	/**
	 * Sets the index title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param indexTitle the index title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setIndexTitle(String indexTitle);

	/**
	 * Returns the index level of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the index level of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getIndexLevel();

	/**
	 * Sets the index level of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param indexLevel the index level of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setIndexLevel(long indexLevel);

	/**
	 * Returns the index level sort order of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the index level sort order of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getIndexLevelSortOrder();

	/**
	 * Sets the index level sort order of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param indexLevelSortOrder the index level sort order of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setIndexLevelSortOrder(long indexLevelSortOrder);

	/**
	 * Returns the index path of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the index path of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getIndexPath();

	/**
	 * Sets the index path of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param indexPath the index path of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setIndexPath(String indexPath);

	/**
	 * Returns the audit log comments of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the audit log comments of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getAuditLogComments();

	/**
	 * Sets the audit log comments of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param auditLogComments the audit log comments of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAuditLogComments(String auditLogComments);

	/**
	 * Returns the audit log title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the audit log title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getAuditLogTitle();

	/**
	 * Sets the audit log title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param auditLogTitle the audit log title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAuditLogTitle(String auditLogTitle);

	/**
	 * Returns the audit log date of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the audit log date of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public Date getAuditLogDate();

	/**
	 * Sets the audit log date of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param auditLogDate the audit log date of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAuditLogDate(Date auditLogDate);

	/**
	 * Returns the audit log status of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the audit log status of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getAuditLogStatus();

	/**
	 * Sets the audit log status of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param auditLogStatus the audit log status of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAuditLogStatus(String auditLogStatus);

	/**
	 * Returns the audit log prev status of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the audit log prev status of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getAuditLogPrevStatus();

	/**
	 * Sets the audit log prev status of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param auditLogPrevStatus the audit log prev status of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAuditLogPrevStatus(String auditLogPrevStatus);

	/**
	 * Returns the hist manual desc of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the hist manual desc of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getHistManualDesc();

	/**
	 * Sets the hist manual desc of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param histManualDesc the hist manual desc of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setHistManualDesc(String histManualDesc);

	/**
	 * Returns the sec lang index title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the sec lang index title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getSecLangIndexTitle();

	/**
	 * Sets the sec lang index title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param secLangIndexTitle the sec lang index title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setSecLangIndexTitle(String secLangIndexTitle);

	/**
	 * Returns the sec lang index desc of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the sec lang index desc of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getSecLangIndexDesc();

	/**
	 * Sets the sec lang index desc of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param secLangIndexDesc the sec lang index desc of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setSecLangIndexDesc(String secLangIndexDesc);

	/**
	 * Returns the sec lang index img path of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the sec lang index img path of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getSecLangIndexImgPath();

	/**
	 * Sets the sec lang index img path of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param secLangIndexImgPath the sec lang index img path of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setSecLangIndexImgPath(String secLangIndexImgPath);

	/**
	 * Returns the sec lang std title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the sec lang std title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getSecLangStdTitle();

	/**
	 * Sets the sec lang std title of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param secLangStdTitle the sec lang std title of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setSecLangStdTitle(String secLangStdTitle);

	/**
	 * Returns the sec lang std desc of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the sec lang std desc of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getSecLangStdDesc();

	/**
	 * Sets the sec lang std desc of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param secLangStdDesc the sec lang std desc of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setSecLangStdDesc(String secLangStdDesc);

	/**
	 * Returns the bi change type cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the bi change type cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getBiChangeTypeCd();

	/**
	 * Sets the bi change type cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param biChangeTypeCd the bi change type cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setBiChangeTypeCd(String biChangeTypeCd);

	/**
	 * Returns the bi region cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the bi region cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getBiRegionCd();

	/**
	 * Sets the bi region cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param biRegionCd the bi region cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setBiRegionCd(String biRegionCd);

	/**
	 * Returns the bi profile loss impact cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the bi profile loss impact cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getBiProfileLossImpactCd();

	/**
	 * Sets the bi profile loss impact cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param biProfileLossImpactCd the bi profile loss impact cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setBiProfileLossImpactCd(String biProfileLossImpactCd);

	/**
	 * Returns the bi cap expense impact cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the bi cap expense impact cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getBiCapExpenseImpactCd();

	/**
	 * Sets the bi cap expense impact cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param biCapExpenseImpactCd the bi cap expense impact cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setBiCapExpenseImpactCd(String biCapExpenseImpactCd);

	/**
	 * Returns the bi impl time scale cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the bi impl time scale cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getBiImplTimeScaleCd();

	/**
	 * Sets the bi impl time scale cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param biImplTimeScaleCd the bi impl time scale cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setBiImplTimeScaleCd(String biImplTimeScaleCd);

	/**
	 * Returns the bi comments of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the bi comments of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getBiComments();

	/**
	 * Sets the bi comments of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param biComments the bi comments of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setBiComments(String biComments);

	/**
	 * Returns the bi brand cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the bi brand cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getBiBrandCd();

	/**
	 * Sets the bi brand cd of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param biBrandCd the bi brand cd of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setBiBrandCd(String biBrandCd);

	/**
	 * Returns the std cross references of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the std cross references of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getStdCrossReferences();

	/**
	 * Sets the std cross references of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param stdCrossReferences the std cross references of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setStdCrossReferences(String stdCrossReferences);

	/**
	 * Returns the audit brand of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the audit brand of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getAuditBrand();

	/**
	 * Sets the audit brand of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param auditBrand the audit brand of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAuditBrand(String auditBrand);

	/**
	 * Returns the global rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the global rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getGlobalRule();

	/**
	 * Sets the global rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param globalRule the global rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setGlobalRule(long globalRule);

	/**
	 * Returns the amea rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the amea rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getAmeaRule();

	/**
	 * Sets the amea rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param ameaRule the amea rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAmeaRule(long ameaRule);

	/**
	 * Returns the amer rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the amer rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getAmerRule();

	/**
	 * Sets the amer rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param amerRule the amer rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setAmerRule(long amerRule);

	/**
	 * Returns the euro rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the euro rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getEuroRule();

	/**
	 * Sets the euro rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param euroRule the euro rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setEuroRule(long euroRule);

	/**
	 * Returns the gc rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the gc rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public long getGcRule();

	/**
	 * Sets the gc rule of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param gcRule the gc rule of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setGcRule(long gcRule);

	/**
	 * Returns the expires of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @return the expires of this Custom Query mapping between STD and Taxonomy tables.
	 */
	@AutoEscape
	public String getExpires();

	/**
	 * Sets the expires of this Custom Query mapping between STD and Taxonomy tables..
	 *
	 * @param expires the expires of this Custom Query mapping between STD and Taxonomy tables.
	 */
	public void setExpires(String expires);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsExt standardsExt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsExt> toCacheModel();

	@Override
	public StandardsExt toEscapedModel();

	@Override
	public StandardsExt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}