/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsComplianceExt service. Represents a row in the &quot;STD_CMPLY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsComplianceExtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsComplianceExtImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsComplianceExt
 * @see com.ihg.brandstandards.db.model.impl.StandardsComplianceExtImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsComplianceExtModelImpl
 * @generated
 */
public interface StandardsComplianceExtModel extends BaseModel<StandardsComplianceExt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards compliance ext model instance should use the {@link StandardsComplianceExt} interface instead.
	 */

	/**
	 * Returns the primary key of this standards compliance ext.
	 *
	 * @return the primary key of this standards compliance ext
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this standards compliance ext.
	 *
	 * @param primaryKey the primary key of this standards compliance ext
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the std compliance ID of this standards compliance ext.
	 *
	 * @return the std compliance ID of this standards compliance ext
	 */
	public long getStdComplianceId();

	/**
	 * Sets the std compliance ID of this standards compliance ext.
	 *
	 * @param stdComplianceId the std compliance ID of this standards compliance ext
	 */
	public void setStdComplianceId(long stdComplianceId);

	/**
	 * Returns the std ID of this standards compliance ext.
	 *
	 * @return the std ID of this standards compliance ext
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this standards compliance ext.
	 *
	 * @param stdId the std ID of this standards compliance ext
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the country code of this standards compliance ext.
	 *
	 * @return the country code of this standards compliance ext
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this standards compliance ext.
	 *
	 * @param countryCode the country code of this standards compliance ext
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the region code of this standards compliance ext.
	 *
	 * @return the region code of this standards compliance ext
	 */
	@AutoEscape
	public String getRegionCode();

	/**
	 * Sets the region code of this standards compliance ext.
	 *
	 * @param regionCode the region code of this standards compliance ext
	 */
	public void setRegionCode(String regionCode);

	/**
	 * Returns the chain code of this standards compliance ext.
	 *
	 * @return the chain code of this standards compliance ext
	 */
	@AutoEscape
	public String getChainCode();

	/**
	 * Sets the chain code of this standards compliance ext.
	 *
	 * @param chainCode the chain code of this standards compliance ext
	 */
	public void setChainCode(String chainCode);

	/**
	 * Returns the compliance expiry date of this standards compliance ext.
	 *
	 * @return the compliance expiry date of this standards compliance ext
	 */
	public Date getComplianceExpiryDate();

	/**
	 * Sets the compliance expiry date of this standards compliance ext.
	 *
	 * @param complianceExpiryDate the compliance expiry date of this standards compliance ext
	 */
	public void setComplianceExpiryDate(Date complianceExpiryDate);

	/**
	 * Returns the compliance expiry rule of this standards compliance ext.
	 *
	 * @return the compliance expiry rule of this standards compliance ext
	 */
	@AutoEscape
	public String getComplianceExpiryRule();

	/**
	 * Sets the compliance expiry rule of this standards compliance ext.
	 *
	 * @param complianceExpiryRule the compliance expiry rule of this standards compliance ext
	 */
	public void setComplianceExpiryRule(String complianceExpiryRule);

	/**
	 * Returns the compliance rule months of this standards compliance ext.
	 *
	 * @return the compliance rule months of this standards compliance ext
	 */
	public long getComplianceRuleMonths();

	/**
	 * Sets the compliance rule months of this standards compliance ext.
	 *
	 * @param complianceRuleMonths the compliance rule months of this standards compliance ext
	 */
	public void setComplianceRuleMonths(long complianceRuleMonths);

	/**
	 * Returns the rule date of this standards compliance ext.
	 *
	 * @return the rule date of this standards compliance ext
	 */
	@AutoEscape
	public String getRuleDate();

	/**
	 * Sets the rule date of this standards compliance ext.
	 *
	 * @param RuleDate the rule date of this standards compliance ext
	 */
	public void setRuleDate(String RuleDate);

	/**
	 * Returns the expiry date of this standards compliance ext.
	 *
	 * @return the expiry date of this standards compliance ext
	 */
	@AutoEscape
	public String getExpiryDate();

	/**
	 * Sets the expiry date of this standards compliance ext.
	 *
	 * @param expiryDate the expiry date of this standards compliance ext
	 */
	public void setExpiryDate(String expiryDate);

	/**
	 * Returns the compliance date string of this standards compliance ext.
	 *
	 * @return the compliance date string of this standards compliance ext
	 */
	@AutoEscape
	public String getComplianceDateString();

	/**
	 * Sets the compliance date string of this standards compliance ext.
	 *
	 * @param complianceDateString the compliance date string of this standards compliance ext
	 */
	public void setComplianceDateString(String complianceDateString);

	/**
	 * Returns the expiry date string of this standards compliance ext.
	 *
	 * @return the expiry date string of this standards compliance ext
	 */
	@AutoEscape
	public String getExpiryDateString();

	/**
	 * Sets the expiry date string of this standards compliance ext.
	 *
	 * @param expiryDateString the expiry date string of this standards compliance ext
	 */
	public void setExpiryDateString(String expiryDateString);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsComplianceExt standardsComplianceExt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsComplianceExt> toCacheModel();

	@Override
	public StandardsComplianceExt toEscapedModel();

	@Override
	public StandardsComplianceExt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}