/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.ihg.brandstandards.db.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the StandardsCompliance service. Represents a row in the &quot;STD_CMPLY&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ihg.brandstandards.db.model.impl.StandardsComplianceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ihg.brandstandards.db.model.impl.StandardsComplianceImpl}.
 * </p>
 *
 * @author Mummanedi
 * @see StandardsCompliance
 * @see com.ihg.brandstandards.db.model.impl.StandardsComplianceImpl
 * @see com.ihg.brandstandards.db.model.impl.StandardsComplianceModelImpl
 * @generated
 */
public interface StandardsComplianceModel extends BaseModel<StandardsCompliance> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a standards compliance model instance should use the {@link StandardsCompliance} interface instead.
	 */

	/**
	 * Returns the primary key of this standards compliance.
	 *
	 * @return the primary key of this standards compliance
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this standards compliance.
	 *
	 * @param primaryKey the primary key of this standards compliance
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the std compliance ID of this standards compliance.
	 *
	 * @return the std compliance ID of this standards compliance
	 */
	public long getStdComplianceId();

	/**
	 * Sets the std compliance ID of this standards compliance.
	 *
	 * @param stdComplianceId the std compliance ID of this standards compliance
	 */
	public void setStdComplianceId(long stdComplianceId);

	/**
	 * Returns the std ID of this standards compliance.
	 *
	 * @return the std ID of this standards compliance
	 */
	public long getStdId();

	/**
	 * Sets the std ID of this standards compliance.
	 *
	 * @param stdId the std ID of this standards compliance
	 */
	public void setStdId(long stdId);

	/**
	 * Returns the country code of this standards compliance.
	 *
	 * @return the country code of this standards compliance
	 */
	@AutoEscape
	public String getCountryCode();

	/**
	 * Sets the country code of this standards compliance.
	 *
	 * @param countryCode the country code of this standards compliance
	 */
	public void setCountryCode(String countryCode);

	/**
	 * Returns the chain code of this standards compliance.
	 *
	 * @return the chain code of this standards compliance
	 */
	@AutoEscape
	public String getChainCode();

	/**
	 * Sets the chain code of this standards compliance.
	 *
	 * @param chainCode the chain code of this standards compliance
	 */
	public void setChainCode(String chainCode);

	/**
	 * Returns the compliance expiry date of this standards compliance.
	 *
	 * @return the compliance expiry date of this standards compliance
	 */
	public Date getComplianceExpiryDate();

	/**
	 * Sets the compliance expiry date of this standards compliance.
	 *
	 * @param complianceExpiryDate the compliance expiry date of this standards compliance
	 */
	public void setComplianceExpiryDate(Date complianceExpiryDate);

	/**
	 * Returns the compliance expiry rule of this standards compliance.
	 *
	 * @return the compliance expiry rule of this standards compliance
	 */
	@AutoEscape
	public String getComplianceExpiryRule();

	/**
	 * Sets the compliance expiry rule of this standards compliance.
	 *
	 * @param complianceExpiryRule the compliance expiry rule of this standards compliance
	 */
	public void setComplianceExpiryRule(String complianceExpiryRule);

	/**
	 * Returns the compliance rule months of this standards compliance.
	 *
	 * @return the compliance rule months of this standards compliance
	 */
	public long getComplianceRuleMonths();

	/**
	 * Sets the compliance rule months of this standards compliance.
	 *
	 * @param complianceRuleMonths the compliance rule months of this standards compliance
	 */
	public void setComplianceRuleMonths(long complianceRuleMonths);

	/**
	 * Returns the rule date of this standards compliance.
	 *
	 * @return the rule date of this standards compliance
	 */
	@AutoEscape
	public String getRuleDate();

	/**
	 * Sets the rule date of this standards compliance.
	 *
	 * @param RuleDate the rule date of this standards compliance
	 */
	public void setRuleDate(String RuleDate);

	/**
	 * Returns the creator ID of this standards compliance.
	 *
	 * @return the creator ID of this standards compliance
	 */
	@AutoEscape
	public String getCreatorId();

	/**
	 * Sets the creator ID of this standards compliance.
	 *
	 * @param creatorId the creator ID of this standards compliance
	 */
	public void setCreatorId(String creatorId);

	/**
	 * Returns the created date of this standards compliance.
	 *
	 * @return the created date of this standards compliance
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this standards compliance.
	 *
	 * @param createdDate the created date of this standards compliance
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the updated by of this standards compliance.
	 *
	 * @return the updated by of this standards compliance
	 */
	@AutoEscape
	public String getUpdatedBy();

	/**
	 * Sets the updated by of this standards compliance.
	 *
	 * @param updatedBy the updated by of this standards compliance
	 */
	public void setUpdatedBy(String updatedBy);

	/**
	 * Returns the updated date of this standards compliance.
	 *
	 * @return the updated date of this standards compliance
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this standards compliance.
	 *
	 * @param updatedDate the updated date of this standards compliance
	 */
	public void setUpdatedDate(Date updatedDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StandardsCompliance standardsCompliance);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StandardsCompliance> toCacheModel();

	@Override
	public StandardsCompliance toEscapedModel();

	@Override
	public StandardsCompliance toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}